import type { Topic } from '@/content/types';

const topic: Topic = {
  id: 'active-passive',
  title: 'Active and passive voice',
  level: 'beginner',
  masteryMinutes: 60,
  reviseMinutes: 20,
  priority: 'high',
  weightage: { tier1: 1, tier2: 2 },
  tags: ['voice', 'passive', 'being', 'been', 'modals', 'imperative', 'let', 'by agent'],
  summary:
    'In the passive, the object moves to the front and the verb becomes a form of "be" + past participle. Keep the tense of the active sentence exactly; that is where most options go wrong.',
  keyPoints: [
    {
      title: 'The basic change',
      text: 'The object of the active sentence becomes the subject. The verb becomes a form of "be" + past participle (V3). The old subject goes after "by", in the object case.',
      formula: 'object + be + V3 + by + agent',
      example: 'Ram **writes** a letter. → A letter **is written** by Ram.',
    },
    {
      title: 'Keep the tense: "being" for continuous',
      text: 'The form of "be" carries the tense. Continuous tenses add **being** before V3: is being, are being, was being, were being.',
      formula: 'is / am / are / was / were + being + V3',
      example: 'They **are building** a house. → A house **is being built** by them.',
    },
    {
      title: '"Been" for perfect tenses',
      text: 'Perfect tenses add **been** before V3: has been, have been, had been, will have been. Perfect continuous tenses and the future continuous are not normally put into the passive.',
      formula: 'has / have / had / will have + been + V3',
      example: 'She **has finished** the work. → The work **has been finished** by her.',
    },
    {
      title: 'Modals: modal + be + V3',
      text: 'With can, could, may, might, must, should, would, shall, will and "ought to", keep the modal and add "be + V3".',
      formula: 'modal + be + V3',
      example: 'You **must obey** the rules. → The rules **must be obeyed** by you.',
    },
    {
      title: 'Imperatives: "Let" and "You are requested"',
      text: 'A command becomes "Let + object + be + V3". A negative command becomes "Let + object + not be + V3". A request with "please" or "kindly" becomes "You are requested to + V1".',
      formula: 'Let + object + be + V3',
      example: 'Shut the door. → Let the door be shut. Please help me. → You are requested to help me.',
    },
    {
      title: 'Questions stay questions',
      text: 'Keep the question form and the tense. Yes/no questions start with the helping verb. "Who" becomes "By whom", and other wh- words stay at the front.',
      example: 'Did he write the letter? → Was the letter written by him? Who broke the vase? → By whom was the vase broken?',
    },
    {
      title: 'Pronouns and dropping the agent',
      text: 'Pronouns change case: I → me, he → him, they → them (after "by"); me → I, him → he (as the new subject). Drop the "by" phrase when the doer is vague or obvious: people, someone, somebody, they (in general).',
      example: 'Someone has stolen my purse. → My purse has been stolen.',
    },
    {
      title: 'No object, no passive',
      text: 'Only a transitive verb (one with an object) has a passive. Intransitive verbs such as sleep, go, come, die and arrive cannot be put into the passive. A verb with two objects can make either object the subject.',
      example: 'He gave me a book. → I was given a book by him. / A book was given to me by him.',
    },
  ],
  comparisons: [
    {
      title: 'Active vs passive, tense by tense',
      items: ['Active', 'Passive'],
      rows: [
        { aspect: 'Simple present', values: ['She **writes** a letter.', 'A letter **is written** by her.'] },
        { aspect: 'Present continuous', values: ['She **is writing** a letter.', 'A letter **is being written** by her.'], key: true },
        { aspect: 'Present perfect', values: ['She **has written** a letter.', 'A letter **has been written** by her.'], key: true },
        { aspect: 'Present perfect continuous', values: ['She **has been writing** a letter.', 'Not used in the passive'] },
        { aspect: 'Simple past', values: ['She **wrote** a letter.', 'A letter **was written** by her.'] },
        { aspect: 'Past continuous', values: ['She **was writing** a letter.', 'A letter **was being written** by her.'] },
        { aspect: 'Past perfect', values: ['She **had written** a letter.', 'A letter **had been written** by her.'] },
        { aspect: 'Past perfect continuous', values: ['She **had been writing** a letter.', 'Not used in the passive'] },
        { aspect: 'Simple future', values: ['She **will write** a letter.', 'A letter **will be written** by her.'] },
        { aspect: 'Future continuous', values: ['She **will be writing** a letter.', 'Not used in the passive'] },
        { aspect: 'Future perfect', values: ['She **will have written** a letter.', 'A letter **will have been written** by her.'] },
        { aspect: 'Future perfect continuous', values: ['She **will have been writing** a letter.', 'Not used in the passive'] },
        { aspect: 'Modal', values: ['She **can write** a letter.', 'A letter **can be written** by her.'] },
      ],
      reveal: 'The helping verb keeps the tense. Continuous adds "being", perfect adds "been", and the main verb is always V3.',
      whenToUse: ['The doer is important and should come first.', 'The action or the receiver matters more, or the doer is unknown.'],
    },
    {
      title: 'Imperative sentences in the passive',
      items: ['Command', 'Request', 'Negative command'],
      rows: [
        { aspect: 'Active', values: ['Shut the door.', 'Please lend me your pen.', 'Do not touch the wire.'] },
        {
          aspect: 'Passive',
          values: ['Let the door be shut.', 'You are requested to lend me your pen.', 'Let the wire not be touched.'],
          key: true,
        },
        { aspect: 'Pattern', values: ['Let + object + be + V3', 'You are requested to + V1', 'Let + object + not be + V3'] },
      ],
      reveal: 'A command uses "Let ... be + V3". A polite request uses "You are requested to". A negative command can also be written "You are forbidden to touch the wire."',
      whenToUse: [
        'A plain order with an object.',
        'The sentence starts with please or kindly.',
        'The sentence starts with "Do not" or "Don\'t".',
      ],
    },
  ],
  qa: [
    {
      q: 'Passive of "They are building a house."?',
      a: ['A house is being built by them.', 'Present continuous: is / are + being + V3.'],
      tag: 'Asked often',
    },
    {
      q: 'Which word marks a continuous tense in the passive, and which marks a perfect tense?',
      a: ['Continuous: **being** (is being done).', 'Perfect: **been** (has been done).'],
      tag: 'Trap',
    },
    {
      q: 'Passive of "Open the window."?',
      a: ['Let the window be opened.', 'Command: Let + object + be + V3.'],
      tag: 'Asked often',
    },
    {
      q: 'Passive of "Please help me."?',
      a: ['You are requested to help me.', 'Requests with please or kindly use "You are requested to".'],
    },
    {
      q: 'Passive of "Who wrote this book?"?',
      a: ['By whom was this book written?', '"Who" becomes "By whom", and the question form stays.'],
      tag: 'Asked often',
    },
    {
      q: 'Passive of "You should respect your elders."?',
      a: ['Your elders should be respected by you.', 'Modal + be + V3.'],
    },
    {
      q: 'When do you drop the "by" phrase?',
      a: ['When the doer is vague or obvious: people, someone, they.', 'Someone has stolen my bag. → My bag has been stolen.'],
    },
    {
      q: 'Can "The baby is sleeping" be put into the passive?',
      a: ['No. "Sleep" is intransitive: it has no object.', 'Only transitive verbs have a passive.'],
      tag: 'Trap',
    },
    {
      q: 'Passive of "People say that he is honest."?',
      a: ['It is said that he is honest.', 'Or: He is said to be honest.'],
    },
    {
      q: 'What happens to pronouns when you change the voice?',
      a: ['The object pronoun becomes a subject pronoun: me → I, him → he.', 'The subject goes after "by" in object form: I → me, they → them.'],
    },
    {
      q: 'Passive of "He gave me a book."?',
      a: ['I was given a book by him.', 'Or: A book was given to me by him.', 'Either object can become the subject.'],
    },
  ],
  quiz: [
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'Select the option that expresses the given sentence in passive voice.\nThe boy kicked the ball.',
      options: ['The ball is kicked by the boy.', 'The ball was kicked by the boy.', 'The ball was being kicked by the boy.', 'The ball had been kicked by the boy.'],
      answer: 1,
      explain: 'Simple past: was / were + V3.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'Select the option that expresses the given sentence in passive voice.\nThey are building a house.',
      options: ['A house is built by them.', 'A house is being built by them.', 'A house was being built by them.', 'A house has been built by them.'],
      answer: 1,
      explain: 'Present continuous: is / are + being + V3.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'Select the option that expresses the given sentence in passive voice.\nShe has finished the work.',
      options: ['The work was finished by her.', 'The work has been finished by her.', 'The work had been finished by her.', 'The work has finished by her.'],
      answer: 1,
      explain: 'Present perfect: has / have + been + V3.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'Select the option that expresses the given sentence in passive voice.\nShut the door.',
      options: ['Let the door is shut.', 'Let the door be shut.', 'The door be shut.', 'Let the door being shut.'],
      answer: 1,
      explain: 'A command becomes Let + object + be + V3.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'Select the option that expresses the given sentence in passive voice.\nYou must obey the rules.',
      options: [
        'The rules must obeyed by you.',
        'The rules must be obeyed by you.',
        'The rules must have been obeyed by you.',
        'The rules must being obeyed by you.',
      ],
      answer: 1,
      explain: 'Modal + be + V3: must be obeyed.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'Select the option that expresses the given sentence in passive voice.\nDid he write this letter?',
      options: ['Was this letter written by him?', 'Is this letter written by him?', 'Was this letter wrote by him?', 'Had this letter been written by him?'],
      answer: 0,
      explain: 'Simple past question: Was / Were + object + V3 + by + agent?',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'Select the option that expresses the given sentence in passive voice.\nWho broke the window?',
      options: ['By whom the window was broken?', 'By whom was the window broken?', 'Who was the window broken by him?', 'By whom has the window been broken?'],
      answer: 1,
      explain: '"Who" becomes "By whom", and the question keeps the helping verb before the subject.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'Select the option that expresses the given sentence in passive voice.\nSomeone has stolen my purse.',
      options: ['My purse was stolen by someone.', 'My purse has been stolen.', 'My purse had been stolen.', 'My purse is stolen by someone.'],
      answer: 1,
      explain: 'Present perfect: has been + V3. The vague agent "someone" is dropped.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'Select the option that expresses the given sentence in passive voice.\nThe committee will announce the results tomorrow.',
      options: [
        'The results will announce tomorrow by the committee.',
        'The results will be announced by the committee tomorrow.',
        'The results would be announced by the committee tomorrow.',
        'The results will have been announced by the committee tomorrow.',
      ],
      answer: 1,
      explain: 'Simple future: will be + V3.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'Select the option that expresses the given sentence in passive voice.\nPlease help me.',
      options: ['You are requested to help me.', 'I am requested to be helped.', 'Let me be helping.', 'You were requested to help me.'],
      answer: 0,
      explain: 'A request with "please" becomes "You are requested to + V1".',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'Select the option that expresses the given sentence in active voice.\nThe song was sung by Meera.',
      options: ['Meera sings the song.', 'Meera sang the song.', 'Meera has sung the song.', 'Meera had sung the song.'],
      answer: 1,
      explain: '"Was sung" is simple past passive, so the active is simple past: sang.',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: 'Select the option that expresses the given sentence in passive voice.\nHe gave me a book.',
      options: ['I was given a book by him.', 'I am given a book by him.', 'A book is given to me by him.', 'A book had been given to me by him.'],
      answer: 0,
      explain: 'Simple past with two objects: either object can be the subject, but the tense must stay past: was given.',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: 'Select the option that expresses the given sentence in passive voice.\nDo not touch the wire.',
      options: ['Let the wire be not touch.', 'Let the wire not be touched.', 'The wire is not touched.', 'Let not the wire touched.'],
      answer: 1,
      explain: 'A negative command becomes Let + object + not be + V3.',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: 'Select the option that expresses the given sentence in passive voice.\nPeople say that he is honest.',
      options: ['He is said to be honest.', 'He was said to be honest.', 'He is said being honest.', 'He is being said to be honest.'],
      answer: 0,
      explain: '"People say that..." becomes "It is said that..." or "He is said to be...". The tense stays present.',
    },
    {
      type: 'truefalse',
      difficulty: 'easy',
      statement: 'An intransitive verb such as "sleep" cannot be put into the passive voice.',
      answer: true,
      explain: 'The passive needs an object to become the new subject. Intransitive verbs have none.',
    },
    {
      type: 'truefalse',
      difficulty: 'medium',
      statement: 'The passive of a continuous tense uses "been" before the past participle.',
      answer: false,
      explain: 'Continuous tenses use "being" (is being done). Perfect tenses use "been".',
    },
  ],
};

export default topic;
