import type { Topic } from '@/content/types';

const topic: Topic = {
  id: 'modern-history',
  title: 'Modern India and the freedom struggle',
  level: 'intermediate',
  masteryMinutes: 200,
  reviseMinutes: 70,
  priority: 'high',
  weightage: { tier1: 1.5, tier2: 1.5 },
  tags: ['Plassey', 'Buxar', 'Governor-General', 'Viceroy', 'social reform', 'INC', 'moderates', 'extremists', 'Gandhi', 'Quit India', 'Government of India Act'],
  summary:
    'From Plassey (1757) to independence (1947). Learn it as four timelines: battles, Governors-General with their events, reform movements with founders, and the national movement with its sessions and campaigns.',
  keyPoints: [
    {
      title: 'Battles of British expansion',
      text: '**Plassey 1757**: Robert Clive defeats Siraj-ud-Daulah of Bengal. **Wandiwash 1760**: the English defeat the French. **Panipat III 1761**: Ahmad Shah Abdali defeats the Marathas. **Buxar 1764**: Hector Munro defeats Mir Qasim, Shuja-ud-Daula of Awadh and Mughal emperor Shah Alam II; the **Treaty of Allahabad (1765)** gives the Company the Diwani of Bengal, Bihar and Odisha.',
      example: 'Four Anglo-Mysore wars end in **1799** with Tipu Sultan killed at Seringapatam. The third Anglo-Maratha war ends Maratha power in 1818. Punjab is annexed in **1849** after the second Anglo-Sikh war.',
    },
    {
      title: 'Governors-General and their events (Company rule)',
      text: '**Warren Hastings**: first Governor-General of Bengal (Regulating Act 1773). **Cornwallis**: Permanent Settlement **1793**. **Wellesley**: Subsidiary Alliance. **William Bentinck**: abolished sati **1829**; first Governor-General of India (Charter Act 1833); English Education Act 1835. **Dalhousie**: Doctrine of Lapse, first railway Bombay to Thane **1853**, Wood\'s Despatch 1854, annexation of Awadh 1856.',
      example: 'Doctrine of Lapse annexed Satara, Jhansi and Nagpur, among others.',
    },
    {
      title: 'Viceroys and their events (Crown rule)',
      text: '**Canning**: revolt of 1857; last Governor-General and first Viceroy (1858). **Lytton**: Vernacular Press Act 1878, Delhi Durbar 1877. **Ripon**: repealed the Vernacular Press Act, local self-government resolution 1882, Ilbert Bill 1883. **Dufferin**: INC founded 1885. **Curzon**: partition of Bengal **1905**. **Minto II**: Morley-Minto Reforms 1909. **Hardinge II**: partition annulled and capital moved to Delhi announced, 1911. **Chelmsford**: Rowlatt Act and Jallianwala Bagh, 1919. **Reading**: Chauri Chaura 1922. **Irwin**: Dandi March 1930. **Willingdon**: Poona Pact 1932. **Linlithgow**: Quit India 1942. **Wavell**: Shimla Conference 1945. **Mountbatten**: partition plan of 3 June 1947.',
      example: 'Ripon is called the father of local self-government in India. C. Rajagopalachari was the only Indian Governor-General.',
    },
    {
      title: 'Social and religious reform movements',
      text: '**Brahmo Samaj** (1828): Raja Ram Mohan Roy. **Prarthana Samaj** (1867): Atmaram Pandurang. **Satyashodhak Samaj** (1873): Jyotiba Phule. **Arya Samaj** (1875, Bombay): Swami Dayanand Saraswati, "Go back to the Vedas". **Theosophical Society** (1875, New York): Madame Blavatsky and Colonel Olcott. **Ramakrishna Mission** (1897): Swami Vivekananda. **Aligarh Movement**: Sir Syed Ahmad Khan. **Young Bengal**: Henry Vivian Derozio.',
      example: 'Ishwar Chandra Vidyasagar campaigned for the **Hindu Widows\' Remarriage Act, 1856**. Dayanand wrote **Satyarth Prakash**; Phule wrote **Gulamgiri**.',
    },
    {
      title: 'Indian National Congress: sessions to remember',
      text: 'Founded **28 December 1885** in Bombay by **A.O. Hume**; first president **W.C. Bonnerjee**, 72 delegates. **1886 Calcutta**: Dadabhai Naoroji. **1887 Madras**: Badruddin Tyabji, first Muslim president. **1906 Calcutta**: Naoroji, swaraj as the goal. **1907 Surat**: split into moderates and extremists. **1916 Lucknow**: reunion and the Congress-League pact. **1917 Calcutta**: Annie Besant, first woman president. **1924 Belgaum**: only session Gandhi presided. **1925 Kanpur**: Sarojini Naidu, first Indian woman president. **1929 Lahore**: Jawaharlal Nehru, Purna Swaraj. **1931 Karachi**: Vallabhbhai Patel, resolution on Fundamental Rights.',
      example: '26 January 1930 was celebrated as Independence Day after the Lahore session; that is why the Constitution came into force on 26 January.',
    },
    {
      title: 'Gandhian movements with years',
      text: 'Returned from South Africa in **1915**. **Champaran 1917** (indigo farmers, Bihar): first satyagraha in India. **Ahmedabad mill strike 1918**: first hunger strike. **Kheda 1918**: revenue remission. **Non-Cooperation 1920 to 1922**: withdrawn after **Chauri Chaura** (February 1922). **Civil Disobedience 1930**: Dandi March from Sabarmati, 12 March to 6 April 1930, to break the salt law. **Gandhi-Irwin Pact 1931**. **Individual Satyagraha 1940**: Vinoba Bhave first. **Quit India, 8 August 1942**: "Do or Die".',
      example: 'Gandhi attended only the **Second** Round Table Conference (1931).',
    },
    {
      title: 'Key acts of British rule',
      text: '**Regulating Act 1773**: Governor-General of Bengal, Supreme Court at Calcutta. **Pitt\'s India Act 1784**: Board of Control. **Charter Act 1813**: ended the Company\'s trade monopoly except tea and trade with China; ₹1 lakh a year for education. **Charter Act 1833**: Governor-General of India. **Charter Act 1853**: open competition for civil services. **Government of India Act 1858**: Crown rule, Secretary of State for India. **Indian Councils Act 1909** (Morley-Minto): separate electorates for Muslims. **GoI Act 1919** (Montagu-Chelmsford): dyarchy in provinces. **GoI Act 1935**: provincial autonomy, federal court. **Indian Independence Act 1947**.',
    },
    {
      title: 'Other milestones',
      text: 'Revolt of 1857 began at **Meerut on 10 May 1857**. **Muslim League** founded in Dhaka, **1906**. **Home Rule Leagues 1916**: Tilak and Annie Besant. **Jallianwala Bagh, 13 April 1919**, Amritsar (General Dyer). **Simon Commission** (appointed 1927) boycotted because it had no Indian member. **Poona Pact 1932**: Gandhi and B.R. Ambedkar. **Cripps Mission 1942**, **Cabinet Mission 1946**.',
      example: 'Rabindranath Tagore gave up his knighthood in protest against Jallianwala Bagh.',
    },
  ],
  comparisons: [
    {
      title: 'Moderates vs extremists',
      items: ['Moderates', 'Extremists'],
      rows: [
        { aspect: 'Dominant phase', values: ['1885 to 1905', '1905 to about 1920'] },
        { aspect: 'Leaders', values: ['Dadabhai Naoroji, G.K. Gokhale, Pherozeshah Mehta, Surendranath Banerjea', 'Bal Gangadhar Tilak, Lala Lajpat Rai, Bipin Chandra Pal (Lal-Bal-Pal), Aurobindo Ghosh'] },
        { aspect: 'Goal', values: ['Reforms and more Indian share in government within British rule', '**Swaraj**'], key: true },
        { aspect: 'Methods', values: ['Petitions, prayers and protests through constitutional means', 'Swadeshi, boycott, national education, mass agitation'], key: true },
        { aspect: 'View of British rule', values: ['Faith in British sense of justice', 'No faith; saw rule as exploitative'] },
        { aspect: 'Support base', values: ['Educated urban middle class', 'Wider masses, including the lower middle class'] },
        { aspect: 'Signature idea', values: ['Drain of wealth theory (Naoroji)', '"Swaraj is my birthright" (Tilak)'] },
      ],
      reveal: 'Both wanted Indians to gain power. The split was over method and pace: constitutional appeals against mass agitation. They split at Surat (1907) and reunited at Lucknow (1916).',
      whenToUse: ['Questions on the early Congress, petitions or the drain theory.', 'Questions on the Swadeshi Movement, boycott, Lal-Bal-Pal or the Surat split.'],
    },
    {
      title: 'Three mass movements led by Gandhi',
      items: ['Non-Cooperation', 'Civil Disobedience', 'Quit India'],
      rows: [
        { aspect: 'Year', values: ['1920 to 1922', '1930 to 1934', '1942'] },
        { aspect: 'Trigger', values: ['Rowlatt Act, Jallianwala Bagh, Khilafat issue', 'Purna Swaraj resolution (Lahore 1929); salt law', 'Failure of the Cripps Mission'] },
        { aspect: 'Signature act', values: ['Boycott of schools, courts, councils and foreign cloth', 'Dandi March to make salt', '"Do or Die"; leaders arrested at once'], key: true },
        { aspect: 'Viceroy', values: ['Chelmsford, then Reading', 'Irwin, then Willingdon', 'Linlithgow'], key: true },
        { aspect: 'How it ended', values: ['Withdrawn after Chauri Chaura (1922)', 'Paused by the Gandhi-Irwin Pact (1931), finally withdrawn in 1934', 'Crushed by force; leaders released later'] },
      ],
      reveal: 'Non-cooperation meant refusing to cooperate with the government. Civil disobedience went further: deliberately breaking laws. Quit India demanded that the British leave at once.',
      whenToUse: ['Questions on Chauri Chaura, Khilafat or boycott of councils.', 'Questions on Dandi, salt or the Gandhi-Irwin Pact.', 'Questions on 1942, "Do or Die" or August Kranti.'],
    },
  ],
  qa: [
    {
      q: 'Who fought the Battle of Plassey (1757)?',
      a: ['Robert Clive of the East India Company.', 'Against Siraj-ud-Daulah, Nawab of Bengal; Mir Jafar betrayed the Nawab.'],
      tag: 'Asked often',
    },
    {
      q: 'Who fought on the losing side at Buxar (1764)?',
      a: ['Mir Qasim of Bengal, Shuja-ud-Daula of Awadh and Mughal emperor Shah Alam II.', 'Hector Munro led the Company army.'],
      tag: 'Asked often',
    },
    {
      q: 'Who was the first Governor-General of Bengal, and who was the first Governor-General of India?',
      a: ['Bengal: Warren Hastings (Regulating Act 1773).', 'India: William Bentinck (Charter Act 1833).'],
      tag: 'Trap',
    },
    {
      q: 'Who was the last Governor-General and first Viceroy?',
      a: ['Lord Canning, from 1858 under the Government of India Act.'],
    },
    {
      q: 'Who introduced the Permanent Settlement and the Subsidiary Alliance?',
      a: ['Permanent Settlement: Cornwallis, 1793.', 'Subsidiary Alliance: Wellesley.'],
    },
    {
      q: 'Who founded the INC, and who was its first president?',
      a: ['Founded by A.O. Hume in Bombay, 28 December 1885.', 'First president: W.C. Bonnerjee.'],
      tag: 'Asked often',
    },
    {
      q: 'First Muslim, first woman and first Indian woman presidents of the INC?',
      a: ['First Muslim: Badruddin Tyabji (1887).', 'First woman: Annie Besant (1917).', 'First Indian woman: Sarojini Naidu (1925).'],
      tag: 'Trap',
    },
    {
      q: 'Where was the Purna Swaraj resolution passed?',
      a: ['Lahore session, 1929, presided by Jawaharlal Nehru.', '26 January 1930 was celebrated as Independence Day.'],
      tag: 'Asked often',
    },
    {
      q: 'Why was the Non-Cooperation Movement withdrawn?',
      a: ['Violence at Chauri Chaura (Gorakhpur district) in February 1922.', 'A crowd set fire to a police station.'],
    },
    {
      q: 'Which was Gandhi\'s first satyagraha in India?',
      a: ['Champaran, Bihar, 1917, for indigo farmers.', 'Ahmedabad (1918) was his first hunger strike.'],
    },
    {
      q: 'Which act brought separate electorates for Muslims?',
      a: ['Indian Councils Act 1909 (Morley-Minto Reforms).'],
      tag: 'Asked often',
    },
    {
      q: 'Match the founders: Arya Samaj, Brahmo Samaj, Satyashodhak Samaj, Ramakrishna Mission.',
      a: ['Arya Samaj: Dayanand Saraswati.', 'Brahmo Samaj: Raja Ram Mohan Roy.', 'Satyashodhak Samaj: Jyotiba Phule. Ramakrishna Mission: Vivekananda.'],
    },
  ],
  quiz: [
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'The Battle of Plassey was fought in:',
      options: ['1757', '1761', '1764', '1857'],
      answer: 0,
      explain: 'Plassey was fought in 1757. Buxar was 1764 and the third battle of Panipat 1761.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'Who was the first president of the Indian National Congress?',
      options: ['A.O. Hume', 'Dadabhai Naoroji', 'W.C. Bonnerjee', 'Surendranath Banerjea'],
      answer: 2,
      explain: 'W.C. Bonnerjee presided over the first session in Bombay, 1885. Hume founded the INC.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'Who founded the Arya Samaj?',
      options: ['Raja Ram Mohan Roy', 'Swami Vivekananda', 'Swami Dayanand Saraswati', 'Jyotiba Phule'],
      answer: 2,
      explain: 'Dayanand Saraswati founded it in Bombay in 1875.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'The Quit India Movement was launched in:',
      options: ['1930', '1940', '1942', '1946'],
      answer: 2,
      explain: 'Launched on 8 August 1942 at the Bombay session with the call "Do or Die".',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'The Permanent Settlement of Bengal was introduced by:',
      options: ['Warren Hastings', 'Lord Cornwallis', 'Lord Wellesley', 'Lord Dalhousie'],
      answer: 1,
      explain: 'Cornwallis introduced it in 1793, fixing land revenue with zamindars permanently.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'The Doctrine of Lapse is associated with:',
      options: ['Lord Wellesley', 'Lord Dalhousie', 'Lord Canning', 'Lord Curzon'],
      answer: 1,
      explain: 'Dalhousie used it to annex states like Satara, Jhansi and Nagpur.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'Sati was abolished in 1829 during the tenure of:',
      options: ['Lord Cornwallis', 'Lord William Bentinck', 'Lord Dalhousie', 'Lord Ripon'],
      answer: 1,
      explain: 'Bentinck abolished sati in 1829, with support from Raja Ram Mohan Roy.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'Bengal was partitioned in 1905 when the Viceroy was:',
      options: ['Lord Minto', 'Lord Curzon', 'Lord Hardinge', 'Lord Lytton'],
      answer: 1,
      explain: 'Curzon partitioned Bengal in 1905. It was annulled in 1911 under Hardinge II.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'The Congress split into moderates and extremists at which session?',
      options: ['Calcutta 1906', 'Surat 1907', 'Lucknow 1916', 'Lahore 1929'],
      answer: 1,
      explain: 'The split came at Surat in 1907. The two sides reunited at Lucknow in 1916.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'The resolution for Purna Swaraj was passed at the Congress session held at:',
      options: ['Karachi', 'Lahore', 'Haripura', 'Nagpur'],
      answer: 1,
      explain: 'Lahore, December 1929, under Jawaharlal Nehru.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'Gandhi\'s first satyagraha in India was at:',
      options: ['Kheda', 'Ahmedabad', 'Champaran', 'Bardoli'],
      answer: 2,
      explain: 'Champaran, Bihar, 1917, for indigo farmers. Ahmedabad and Kheda followed in 1918.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'Separate electorates for Muslims were first introduced by the:',
      options: ['Indian Councils Act 1892', 'Indian Councils Act 1909', 'Government of India Act 1919', 'Government of India Act 1935'],
      answer: 1,
      explain: 'The Morley-Minto Reforms (Indian Councils Act 1909) brought separate electorates for Muslims.',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: 'Which of these was NOT on the losing side at the Battle of Buxar?',
      options: ['Mir Qasim', 'Shuja-ud-Daula', 'Shah Alam II', 'Siraj-ud-Daulah'],
      answer: 3,
      explain: 'Siraj-ud-Daulah lost at Plassey (1757) and was dead by 1764.',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: 'Who was the first Indian woman to be president of the Indian National Congress?',
      options: ['Annie Besant', 'Sarojini Naidu', 'Nellie Sengupta', 'Vijaya Lakshmi Pandit'],
      answer: 1,
      explain: 'Sarojini Naidu, Kanpur 1925. Annie Besant (1917) was the first woman president but not Indian-born.',
    },
    {
      type: 'truefalse',
      difficulty: 'easy',
      statement: 'The Non-Cooperation Movement was withdrawn after the Chauri Chaura incident.',
      answer: true,
      explain: 'Gandhi called it off in February 1922 after violence at Chauri Chaura.',
    },
    {
      type: 'truefalse',
      difficulty: 'medium',
      statement: 'Warren Hastings was the first Governor-General of India.',
      answer: false,
      explain: 'He was the first Governor-General of Bengal. William Bentinck was the first Governor-General of India (1833).',
    },
    {
      type: 'truefalse',
      difficulty: 'medium',
      statement: 'The Vernacular Press Act passed under Lord Lytton was repealed by Lord Ripon.',
      answer: true,
      explain: 'Lytton passed it in 1878; Ripon repealed it in 1882.',
    },
    {
      type: 'truefalse',
      difficulty: 'hard',
      statement: 'Gandhi attended all three Round Table Conferences in London.',
      answer: false,
      explain: 'He attended only the Second Round Table Conference (1931), after the Gandhi-Irwin Pact.',
    },
  ],
};

export default topic;
