import type { Topic } from '@/content/types';

const topic: Topic = {
  id: 'parliament',
  title: 'Union executive and Parliament',
  level: 'intermediate',
  masteryMinutes: 120,
  reviseMinutes: 40,
  priority: 'high',
  weightage: { tier1: 1, tier2: 1 },
  tags: ['President', 'Vice-President', 'Prime Minister', 'Lok Sabha', 'Rajya Sabha', 'money bill', 'joint sitting', 'ordinance', 'Article 110', 'Article 123'],
  summary:
    'The President, Vice-President and council of ministers (Arts 52 to 78) and Parliament (Arts 79 to 122). Questions test article numbers, minimum ages, who presides, and what the Rajya Sabha can and cannot do.',
  keyPoints: [
    {
      title: 'President: key articles',
      text: '**Art 52** there shall be a President; 53 executive power vests in the President; 54 election; 56 term of 5 years; 58 qualifications (minimum age **35**); **61 impeachment** for "violation of the Constitution"; **72 pardoning power**; **123 ordinances** when Parliament is not in session.',
      example: 'Oath is given by the **Chief Justice of India** (Art 60). The President resigns by writing to the **Vice-President**.',
    },
    {
      title: 'How the President is elected',
      text: 'Elected indirectly by an **electoral college** of the **elected** members of both Houses of Parliament and the **elected** members of state Legislative Assemblies, including Delhi and Puducherry. Voting is by proportional representation with the single transferable vote, by secret ballot.',
      example: 'Nominated MPs and members of state Legislative Councils do **not** vote. Disputes go to the **Supreme Court** (Art 71).',
    },
    {
      title: 'Vice-President',
      text: '**Art 63** there shall be a Vice-President; **Art 64** he is ex officio **Chairman of the Rajya Sabha**. Elected by **all** members of both Houses of Parliament (elected and nominated); state legislators do not vote. Minimum age 35, term 5 years. Removed by a Rajya Sabha resolution agreed to by the Lok Sabha.',
    },
    {
      title: 'PM and council of ministers',
      text: '**Art 74**: a council of ministers headed by the PM aids and advises the President. **Art 75**: the President appoints the PM; the council is **collectively responsible to the Lok Sabha**. The **91st Amendment (2003)** caps the council at **15%** of the Lok Sabha strength. Three ranks: Cabinet ministers, Ministers of State, Deputy Ministers.',
      example: '**Art 76** Attorney General, the highest law officer of the Union, appointed by the President.',
    },
    {
      title: 'Lok Sabha and Rajya Sabha basics',
      text: '**Art 79**: Parliament = President + Rajya Sabha + Lok Sabha. **Art 80** Rajya Sabha: maximum **250** (238 from states and UTs + **12 nominated** for literature, science, art and social service). **Art 81** Lok Sabha: maximum **550 elected** members. Rajya Sabha is a **permanent House**: members serve 6 years and one-third retire every second year. Lok Sabha lasts 5 years unless dissolved.',
      example: 'Minimum age: Lok Sabha **25**, Rajya Sabha **30**, President and Vice-President **35**.',
    },
    {
      title: 'Presiding officers, sessions, quorum',
      text: '**Art 93** Speaker and Deputy Speaker of the Lok Sabha; **Art 89** Chairman and Deputy Chairman of the Rajya Sabha. **Art 85**: the gap between two sessions cannot exceed **6 months**; by convention there are three sessions (Budget, Monsoon, Winter). **Art 100**: quorum is **one-tenth** of the total members of the House.',
      example: 'Question Hour is the first hour of a sitting. Zero Hour is an Indian practice not mentioned in the rules.',
    },
    {
      title: 'Bills and the joint sitting',
      text: '**Art 110** defines a money bill; the **Speaker** certifies it. It is introduced only in the Lok Sabha with the President\'s recommendation. The Rajya Sabha can only make recommendations within **14 days** (Art 109). **Art 108**: a joint sitting, called by the President and presided over by the **Speaker**, settles a deadlock on an ordinary bill. No joint sitting for a money bill or a constitutional amendment (Art 368).',
      example: 'Joint sittings so far: **Dowry Prohibition Bill (1961)**, Banking Service Commission (Repeal) Bill (1978), **Prevention of Terrorism Bill (2002)**.',
    },
    {
      title: 'Other articles often asked',
      text: '**Art 112** annual financial statement (the Budget); **Art 117** financial bills; **Art 111** President\'s assent; **Art 249** Rajya Sabha can let Parliament make laws on a State List subject in the national interest; **Art 312** Rajya Sabha can create new all-India services. Emergencies: **352** national, **356** President\'s rule in a state, **360** financial.',
      example: 'The word "Budget" is not used in the Constitution; Article 112 calls it the annual financial statement.',
    },
  ],
  comparisons: [
    {
      title: 'Lok Sabha vs Rajya Sabha',
      items: ['Lok Sabha', 'Rajya Sabha'],
      rows: [
        { aspect: 'Article', values: ['Art 81', 'Art 80'] },
        { aspect: 'Maximum strength', values: ['550 elected', '250 (238 elected + 12 nominated)'] },
        { aspect: 'How members are chosen', values: ['Directly by voters', 'Indirectly by elected MLAs (single transferable vote); 12 nominated by the President'] },
        { aspect: 'Term', values: ['5 years; can be dissolved', 'Permanent; members serve 6 years, one-third retire every 2 years'], key: true },
        { aspect: 'Minimum age', values: ['25', '30'] },
        { aspect: 'Presiding officer', values: ['Speaker, elected from its members', 'Chairman, the Vice-President (ex officio)'] },
        { aspect: 'Money bills', values: ['Introduced only here; has the final say', 'Only recommends, within 14 days'], key: true },
        { aspect: 'No-confidence motion', values: ['Only here; the council of ministers is responsible to it', 'Cannot remove the government'], key: true },
        { aspect: 'Special powers', values: ['Speaker certifies money bills and presides over joint sittings', 'Art 249 (State List laws) and Art 312 (new all-India services)'] },
      ],
      reveal: 'The Lok Sabha controls money and the government. The Rajya Sabha is permanent and holds two special powers that protect the federal balance.',
      whenToUse: ['Questions on money bills, no-confidence, the Speaker or dissolution.', 'Questions on permanence, nominated members, the Vice-President, Art 249 or Art 312.'],
    },
    {
      title: 'Money bill vs financial bill vs ordinary bill',
      items: ['Money bill', 'Financial bill (Art 117(1))', 'Ordinary bill'],
      rows: [
        { aspect: 'Article', values: ['Art 110', 'Art 117(1)', 'Art 107'] },
        { aspect: 'Where introduced', values: ['Lok Sabha only', 'Lok Sabha only', 'Either House'] },
        { aspect: 'President\'s recommendation to introduce', values: ['Needed', 'Needed', 'Not needed'] },
        { aspect: 'Rajya Sabha can amend or reject?', values: ['No; only recommends within 14 days', 'Yes', 'Yes'], key: true },
        { aspect: 'Joint sitting possible?', values: ['No', 'Yes', 'Yes'], key: true },
        { aspect: 'Who decides its status', values: ['Speaker certifies; the decision is final', 'Not certified by the Speaker', 'Not certified by the Speaker'] },
        { aspect: 'President can return it?', values: ['No; assents or withholds', 'Yes, once', 'Yes, once'] },
      ],
      reveal: 'A money bill deals only with the matters in Art 110 (taxes, borrowing, the Consolidated Fund). A financial bill touches those matters but also others, so after introduction it follows the ordinary procedure.',
      whenToUse: [
        'The bill deals only with taxation, borrowing or spending from the Consolidated Fund.',
        'The bill includes some money matters along with other provisions.',
        'Any other bill.',
      ],
    },
  ],
  qa: [
    {
      q: 'Who elects the President?',
      a: ['Elected members of both Houses of Parliament.', 'Elected members of state Legislative Assemblies, including Delhi and Puducherry.', 'Nominated members do not vote.'],
      tag: 'Asked often',
    },
    {
      q: 'Who elects the Vice-President?',
      a: ['All members of both Houses of Parliament, elected and nominated.', 'State legislators do not take part.'],
      tag: 'Trap',
    },
    {
      q: 'Who administers the oath to the President, and to whom does the President resign?',
      a: ['Oath: Chief Justice of India.', 'Resignation: addressed to the Vice-President.'],
    },
    {
      q: 'Which article gives the President the power to pardon? And the power to issue ordinances?',
      a: ['Pardon: Article 72 (Governor: Article 161).', 'Ordinance: Article 123 (Governor: Article 213).'],
      tag: 'Asked often',
    },
    {
      q: 'Who decides whether a bill is a money bill?',
      a: ['The Speaker of the Lok Sabha.', 'The decision is final (Article 110(3)).'],
      tag: 'Asked often',
    },
    {
      q: 'How long can the Rajya Sabha hold a money bill?',
      a: ['14 days.', 'After that it is deemed passed by both Houses in the form the Lok Sabha passed it.'],
    },
    {
      q: 'Who presides over a joint sitting of Parliament?',
      a: ['The Speaker of the Lok Sabha (Article 118(4)).', 'In the Speaker\'s absence, the Deputy Speaker.'],
      tag: 'Trap',
    },
    {
      q: 'Which bills can never go to a joint sitting?',
      a: ['Money bills.', 'Constitutional amendment bills (Article 368).'],
    },
    {
      q: 'What is the maximum gap allowed between two sessions of Parliament?',
      a: ['Six months (Article 85).', 'So Parliament must meet at least twice a year.'],
    },
    {
      q: 'Which amendment limits the size of the council of ministers?',
      a: ['91st Amendment (2003).', 'Total ministers, including the PM, cannot exceed 15% of the Lok Sabha strength.'],
    },
    {
      q: 'What is the quorum of either House?',
      a: ['One-tenth of the total number of members (Article 100).'],
    },
    {
      q: 'Name the two special powers of the Rajya Sabha.',
      a: ['Article 249: allow Parliament to legislate on a State List subject in the national interest.', 'Article 312: create new all-India services.', 'Both need a two-thirds majority of members present and voting.'],
      tag: 'Asked often',
    },
  ],
  quiz: [
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'What is the minimum age to become a member of the Rajya Sabha?',
      options: ['21 years', '25 years', '30 years', '35 years'],
      answer: 2,
      explain: 'Rajya Sabha 30, Lok Sabha 25, President and Vice-President 35.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'Who is the ex officio Chairman of the Rajya Sabha?',
      options: ['The President', 'The Vice-President', 'The Speaker', 'The Prime Minister'],
      answer: 1,
      explain: 'Article 64 makes the Vice-President ex officio Chairman of the Council of States.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'How many members can the President nominate to the Rajya Sabha?',
      options: ['2', '10', '12', '14'],
      answer: 2,
      explain: 'Article 80: 12 members with knowledge of literature, science, art or social service.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'Who presides over a joint sitting of the two Houses of Parliament?',
      options: ['The President', 'The Vice-President', 'The Speaker of the Lok Sabha', 'The Chief Justice of India'],
      answer: 2,
      explain: 'Article 118(4): the Speaker presides; in the Speaker\'s absence, the Deputy Speaker.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'The President can issue ordinances under which article?',
      options: ['Article 72', 'Article 110', 'Article 123', 'Article 356'],
      answer: 2,
      explain: 'Article 123. Article 72 is pardoning power; Article 356 is President\'s rule.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'Which article deals with the impeachment of the President?',
      options: ['Article 56', 'Article 61', 'Article 67', 'Article 74'],
      answer: 1,
      explain: 'Article 61: the only ground is "violation of the Constitution".',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'Who certifies a bill as a money bill?',
      options: ['The President', 'The Finance Minister', 'The Speaker of the Lok Sabha', 'The Chairman of the Rajya Sabha'],
      answer: 2,
      explain: 'Article 110(3): the Speaker decides, and the decision is final.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'Within how many days must the Rajya Sabha return a money bill to the Lok Sabha?',
      options: ['7 days', '14 days', '30 days', '6 months'],
      answer: 1,
      explain: 'Article 109: 14 days, with or without recommendations the Lok Sabha may ignore.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'Which of these does NOT take part in the election of the President?',
      options: ['Elected members of the Lok Sabha', 'Elected members of the Rajya Sabha', 'Elected members of the Delhi Legislative Assembly', 'Nominated members of the Rajya Sabha'],
      answer: 3,
      explain: 'Only elected members vote. Nominated members of either House are left out.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'The council of ministers is collectively responsible to:',
      options: ['The President', 'The Rajya Sabha', 'The Lok Sabha', 'Parliament as a whole'],
      answer: 2,
      explain: 'Article 75(3). That is why a no-confidence motion can be moved only in the Lok Sabha.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'The maximum gap between two sessions of Parliament is:',
      options: ['3 months', '4 months', '6 months', '1 year'],
      answer: 2,
      explain: 'Article 85 says six months must not pass between the last sitting of one session and the first of the next.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'Which amendment capped the size of the council of ministers at 15% of the Lok Sabha strength?',
      options: ['42nd', '61st', '91st', '101st'],
      answer: 2,
      explain: 'The 91st Amendment (2003). The 61st lowered the voting age; the 101st brought GST.',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: 'The first joint sitting of the Indian Parliament was held on which bill?',
      options: ['Prevention of Terrorism Bill', 'Dowry Prohibition Bill', 'Banking Service Commission (Repeal) Bill', 'Hindu Code Bill'],
      answer: 1,
      explain: 'Dowry Prohibition Bill, 1961. The other two joint sittings were in 1978 and 2002.',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: 'Under which article can the Rajya Sabha authorise Parliament to make a law on a subject in the State List?',
      options: ['Article 249', 'Article 250', 'Article 312', 'Article 368'],
      answer: 0,
      explain: 'Article 249, by a resolution of two-thirds of members present and voting. Article 312 is about all-India services.',
    },
    {
      type: 'truefalse',
      difficulty: 'easy',
      statement: 'The Rajya Sabha is a permanent House and cannot be dissolved.',
      answer: true,
      explain: 'One-third of its members retire every second year; the House itself never dissolves.',
    },
    {
      type: 'truefalse',
      difficulty: 'medium',
      statement: 'Nominated members of Parliament vote in the election of the Vice-President.',
      answer: true,
      explain: 'The Vice-President is elected by all members of both Houses, elected and nominated.',
    },
    {
      type: 'truefalse',
      difficulty: 'medium',
      statement: 'A joint sitting can be called to resolve a deadlock over a constitutional amendment bill.',
      answer: false,
      explain: 'Article 368 needs each House to pass the bill separately. Joint sittings are only for ordinary and financial bills.',
    },
    {
      type: 'truefalse',
      difficulty: 'hard',
      statement: 'A financial bill under Article 117(1) can be amended or rejected by the Rajya Sabha.',
      answer: true,
      explain: 'Only a money bill limits the Rajya Sabha. A financial bill follows the ordinary procedure after introduction.',
    },
  ],
};

export default topic;
