import type { Topic } from '@/content/types';

const topic: Topic = {
  id: 'analogy',
  title: 'Analogy',
  level: 'beginner',
  masteryMinutes: 45,
  reviseMinutes: 15,
  priority: 'high',
  weightage: { tier1: 2, tier2: 2 },
  tags: ['word analogy', 'number analogy', 'letter analogy', 'bridge sentence', 'squares', 'cubes', 'letter positions'],
  summary:
    'A : B :: C : ?. Find the one rule that turns A into B, check it fits exactly, then apply the same rule to C. Words need a bridge sentence; numbers and letters need a small table of squares, cubes and positions.',
  keyPoints: [
    {
      title: 'Make a bridge sentence for word pairs',
      text: 'Link the first pair with a short, exact sentence. Then put the second pair into the same sentence. If two options fit, make the sentence tighter.',
      example: '"A doctor works in a hospital" → "A teacher works in a **school**."',
    },
    {
      title: 'Relations that come again and again',
      text: 'Worker : workplace, tool : its use, instrument : what it measures, animal : its young, animal : its home, part : whole, maker : product, word : synonym or antonym.',
      example: 'Barometer : pressure (instrument : measures). Cow : calf (animal : young). Bee : hive (animal : home).',
    },
    {
      title: 'Keep the order of the pair',
      text: 'A : B is not the same as B : A. If the first pair goes worker → place, the answer must go the same way, not place → worker.',
      example: 'Author : Book matches Composer : Music, not Music : Composer.',
    },
    {
      title: 'Number pairs: test squares and cubes first',
      text: 'Most number analogies are n², n³, n² ± 1, n³ ± 1 or n(n + 1). Know squares up to 30 and cubes up to 15 so you spot them at sight.',
      formula: 'n → n² ± 1,  n → n³ ± 1,  n → n(n + 1)',
      example: '6 : 35 is 6² − 1, so 11 : **120** (11² − 1).',
    },
    {
      title: 'Letter pairs: convert to positions',
      text: 'Write each letter as its position (A = 1 … Z = 26) and look at the gap between matching letters. Use EJOTY (E 5, J 10, O 15, T 20, Y 25) to find positions fast.',
      formula: 'EJOTY: E = 5, J = 10, O = 15, T = 20, Y = 25',
      example: 'ACE : BDF is +1 on each letter, so GIK : **HJL**.',
    },
    {
      title: 'Opposite letters add to 27',
      text: 'A pair like AZ, BY, CX uses opposite letters. A letter at position n pairs with the letter at 27 − n.',
      formula: 'opposite of n = 27 − n',
      example: 'D is 4, so its opposite is 23 = W. AZ : BY :: CX : **DW**.',
    },
    {
      title: 'Check the rule on the whole pair',
      text: 'A rule must turn A into B exactly. If two rules both work for the first pair, apply both to C and see which result is among the options.',
      example: '12 : 20 fits 3×4 : 4×5. With 30 = 5×6, the answer is 6×7 = **42**.',
    },
  ],
  comparisons: [
    {
      title: 'Word vs number vs letter analogy',
      items: ['Word analogy', 'Number analogy', 'Letter analogy'],
      rows: [
        { aspect: 'What links the pair', values: ['A meaning relation', 'An arithmetic rule', 'A shift in letter positions'] },
        {
          aspect: 'First thing to try',
          values: ['A bridge sentence', 'Squares, cubes, ±1', 'Write positions, find each gap'],
          key: true,
        },
        { aspect: 'Typical rule', values: ['Worker : place, tool : use', 'n → n² − 1', 'Each letter +1, or opposite letter'] },
        { aspect: 'Common trap', values: ['Reversed order in the options', 'Rule fits A but not B', 'Counting the gap off by one'] },
      ],
      reveal: 'All three are the same job: name the rule from the first pair, then apply it once more. Only the tool for spotting the rule changes.',
      whenToUse: [
        'The terms are words: say the link out loud as a sentence.',
        'The terms are numbers: compare each with nearby squares and cubes.',
        'The terms are letters: convert to positions before you guess.',
      ],
    },
  ],
  shortcuts: [
    {
      pattern: 'Number analogy near a square',
      example: '8 : 63 :: 12 : ?',
      options: ['143', '144', '145', '132'],
      answer: '143',
      ladder: [
        {
          name: 'Standard',
          steps: ['Try 8 × 8 = 64, 8 × 7 = 56, 8³ = 512.', '63 is one less than 64, so the rule is n² − 1.', '12² − 1 = 144 − 1 = 143.'],
          seconds: 30,
        },
        { name: 'Shortcut', steps: ['63 sits next to the square 64, so read it as 8² − 1.', '12² − 1 = 143.'], seconds: 10 },
        {
          name: 'Option elimination',
          steps: ['144 is 12² and 145 is 12² + 1: both break the "− 1".', '132 is 11 × 12, which does not match 8 : 63.', 'Only 143 is left.'],
          seconds: 8,
        },
      ],
    },
    {
      pattern: 'Letter pair analogy',
      example: 'BD : GI :: KM : ?',
      options: ['PR', 'OQ', 'PQ', 'QR'],
      answer: 'PR',
      ladder: [
        {
          name: 'Standard',
          steps: ['Write the alphabet and count on from B to G: 5 steps.', 'Count D to I: 5 steps.', 'Count 5 on from K and M: P and R.'],
          seconds: 40,
        },
        { name: 'Positions', steps: ['B 2 → G 7 and D 4 → I 9: both +5.', 'K 11 + 5 = 16 = P, M 13 + 5 = 18 = R.'], seconds: 15 },
        {
          name: 'Option elimination',
          steps: ['In BD and GI the two letters are 2 apart, so the answer must be too.', 'PQ and QR are 1 apart; OQ starts at O, only +4 from K.', 'Only PR is left.'],
          seconds: 10,
        },
      ],
    },
    {
      pattern: 'Word analogy with close options',
      example: 'Author : Book :: Composer : ?',
      options: ['Music', 'Piano', 'Orchestra', 'Singer'],
      answer: 'Music',
      ladder: [
        { name: 'Standard', steps: ['Read each option against "composer" and pick the one that feels closest.'], seconds: 25 },
        { name: 'Bridge sentence', steps: ['"An author creates a book."', '"A composer creates music."'], seconds: 10 },
        {
          name: 'Option elimination',
          steps: ['Piano is a tool, not a product.', 'Orchestra and singer perform the work; they are not what a composer creates.', 'Music is left.'],
          seconds: 8,
        },
      ],
    },
  ],
  qa: [
    {
      q: 'What is a bridge sentence?',
      a: ['A short sentence that links the first pair exactly.', 'Put the second pair into it: the right option fits without changing a word.'],
      tag: 'Shortcut',
    },
    {
      q: 'Two options fit your bridge sentence. What now?',
      a: ['Make the sentence more exact.', '"A bee lives in a hive" beats "a bee is found near a hive".'],
    },
    {
      q: 'Why does the order of a pair matter?',
      a: ['A : B means the same direction for C : D.', 'Worker : Place never matches Place : Worker.'],
      tag: 'Trap',
    },
    {
      q: 'Which number rules should you test first?',
      a: ['n², n³ and each of them ± 1.', 'Then n(n + 1), then × or ÷ by a fixed number.'],
      tag: 'Asked often',
    },
    {
      q: 'What is EJOTY?',
      a: ['A memory aid for letter positions: E 5, J 10, O 15, T 20, Y 25.', 'Count one or two steps from the nearest anchor.'],
      tag: 'Shortcut',
    },
    {
      q: 'How do you find the opposite letter of any letter?',
      a: ['Opposite of position n is 27 − n.', 'H is 8, so its opposite is 19 = S.'],
      tag: 'Shortcut',
    },
    {
      q: 'Instrument analogies you should know?',
      a: ['Thermometer : temperature, barometer : atmospheric pressure.', 'Hygrometer : humidity, anemometer : wind speed, seismograph : earthquakes.'],
      tag: 'Asked often',
    },
    {
      q: 'Animal and young pairs that come up?',
      a: ['Cow : calf, dog : puppy, cat : kitten, horse : foal.', 'Sheep : lamb, lion : cub, frog : tadpole.'],
    },
    {
      q: 'A rule fits 3 : 28. How do you pick between 3³ + 1 and 9 × 3 + 1?',
      a: ['Apply both to the next term.', 'Keep the rule whose result is in the options; squares and cubes win most often.'],
      tag: 'Trap',
    },
  ],
  quiz: [
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'Doctor : Hospital :: Teacher : ?',
      options: ['Book', 'School', 'Student', 'Chalk'],
      answer: 1,
      explain: 'Worker : place of work. A doctor works in a hospital; a teacher works in a school.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'Bird : Nest :: Bee : ?',
      options: ['Den', 'Burrow', 'Hive', 'Stable'],
      answer: 2,
      explain: 'Animal : its home. A bee lives in a hive. Den (lion), burrow (rabbit) and stable (horse) belong to other animals.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: '4 : 16 :: 7 : ?',
      options: ['42', '49', '56', '343'],
      answer: 1,
      explain: 'Number : its square. 4² = 16, so 7² = 49.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'Pen : Write :: Knife : ?',
      options: ['Sharp', 'Kitchen', 'Cut', 'Steel'],
      answer: 2,
      explain: 'Tool : its use. A pen is used to write; a knife is used to cut.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: '5 : 125 :: 8 : ?',
      options: ['64', '256', '512', '520'],
      answer: 2,
      explain: 'Number : its cube. 5³ = 125, so 8³ = 512.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: '6 : 35 :: 11 : ?',
      options: ['120', '121', '122', '132'],
      answer: 0,
      explain: '35 = 6² − 1, so the answer is 11² − 1 = 120.',
      shortcut: '35 is one less than the square 36. Look for 11² − 1 among the options.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'ACE : BDF :: GIK : ?',
      options: ['HIJ', 'HJL', 'GHI', 'IKM'],
      answer: 1,
      explain: 'Each letter moves +1: A→B, C→D, E→F. So G→H, I→J, K→L gives HJL.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'AZ : BY :: CX : ?',
      options: ['DV', 'DW', 'EW', 'DX'],
      answer: 1,
      explain: 'Each pair is a letter and its opposite (positions add to 27). The first letters go A, B, C, D, and the opposite of D (4) is W (23).',
      shortcut: 'Opposite of n = 27 − n.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'MOTHER : NPUIFS :: FATHER : ?',
      options: ['GBUHFS', 'GBUIFS', 'HBUIFS', 'GBVIFS'],
      answer: 1,
      explain: 'Each letter moves one step forward: M→N, O→P, T→U, H→I, E→F, R→S. FATHER becomes GBUIFS.',
      shortcut: 'THER is common to both words, so the code must end in UIFS. Only F→G and A→B are new.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'Thermometer : Temperature :: Barometer : ?',
      options: ['Humidity', 'Wind speed', 'Pressure', 'Rainfall'],
      answer: 2,
      explain: 'Instrument : what it measures. A barometer measures atmospheric pressure. Humidity uses a hygrometer and wind speed an anemometer.',
    },
    {
      type: 'truefalse',
      difficulty: 'easy',
      statement: 'Lion : Den and Horse : Stable show the same relation.',
      answer: true,
      explain: 'Both pairs are animal : its home. A lion lives in a den; a horse is kept in a stable.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'Select the pair that has the same relation as Cow : Calf.',
      options: ['Hen : Egg', 'Dog : Puppy', 'Lion : Den', 'Horse : Stable'],
      answer: 1,
      explain: 'Animal : its young. A puppy is a young dog. An egg is not a young hen, and den and stable are homes.',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: '12 : 20 :: 30 : ?',
      options: ['36', '40', '42', '48'],
      answer: 2,
      explain: '12 = 3 × 4 and 20 = 4 × 5: n(n + 1) goes to (n + 1)(n + 2). 30 = 5 × 6, so the answer is 6 × 7 = 42.',
      shortcut: 'Split each number into two consecutive factors, then move both factors up by one.',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: 'CAT : DDY :: DOG : ?',
      options: ['EQL', 'ERK', 'ERL', 'FRL'],
      answer: 2,
      explain: 'The letters move +1, +3, +5: C→D, A→D, T→Y. So D+1 = E, O+3 = R, G+5 = L gives ERL.',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: 'Select the number pair that follows the same rule as 3 : 28.',
      options: ['4 : 65', '5 : 124', '6 : 215', '2 : 7'],
      answer: 0,
      explain: '28 = 3³ + 1. Only 4 : 65 fits n³ + 1 (4³ + 1 = 65). The other three are n³ − 1.',
      shortcut: 'Three options share one rule (n³ − 1); the odd rule out is the answer.',
    },
  ],
};

export default topic;
