import type { Topic } from '@/content/types';

const topic: Topic = {
  id: 'series',
  title: 'Series',
  level: 'intermediate',
  masteryMinutes: 90,
  reviseMinutes: 30,
  priority: 'high',
  weightage: { tier1: 2, tier2: 2 },
  tags: ['number series', 'letter series', 'alphanumeric', 'difference table', 'squares', 'cubes', 'alternating', 'EJOTY', 'wrong term'],
  summary:
    'Find the rule, check it on every term, then extend it once. Start with differences; if they grow fast, try multiplication; if a term sits next to a square or cube, try n² ± k or n³ ± k; if nothing fits, split the series into two.',
  keyPoints: [
    {
      title: 'Start with the difference table',
      text: 'Subtract each term from the next. If the differences are not constant, take differences of the differences. Stop when a clear pattern appears, then build back up.',
      example: '6, 11, 21, 36, 56: differences 5, 10, 15, 20, so next is +25 = **81**.',
    },
    {
      title: 'Fast growth means multiplication',
      text: 'When terms roughly double or triple, test ×k ± c. Divide each term by the one before to see the multiplier.',
      formula: 'next = previous × k ± c',
      example: '3, 7, 15, 31, 63: each is ×2 + 1, so next is **127**.',
    },
    {
      title: 'Terms next to squares or cubes',
      text: 'If the terms sit one or two away from 1, 4, 9, 16… or 1, 8, 27, 64…, the rule is n² ± k or n³ ± k. n(n + 1) = 2, 6, 12, 20, 30 is the other common one.',
      formula: 'n² ± k,  n³ ± k,  n(n + 1)',
      example: '0, 7, 26, 63, 124 = n³ − 1, so next is 6³ − 1 = **215**.',
    },
    {
      title: 'Alternating series',
      text: 'If the terms go up and down, or two rules take turns, split the series into odd places and even places. Each half is a simple series.',
      example: '5, 10, 8, 16, 14, 28: ×2 and −2 take turns, so next is 28 − 2 = **26**.',
    },
    {
      title: 'Letter positions and EJOTY',
      text: 'Turn letters into numbers: A = 1 … Z = 26. EJOTY marks 5, 10, 15, 20, 25. Reverse position is 27 − n (A = 26, Z = 1).',
      formula: 'reverse position = 27 − n',
      example: 'Z, X, U, Q = 26, 24, 21, 17 (gaps −2, −3, −4), so next is 17 − 5 = 12 = **L**.',
    },
    {
      title: 'Alphanumeric: solve each part alone',
      text: 'In terms like B2, D8, F18 the letters follow one rule and the numbers another. Solve the letters, solve the numbers, then join them.',
      example: 'B, D, F, H → J. 2, 8, 18, 32 = 2n² → 50. Answer **J50**.',
    },
    {
      title: 'Find the wrong term',
      text: 'Guess the rule from most of the terms. The one term that breaks it is wrong. Changing that single term should make the whole series fit.',
      example: '3, 8, 15, 24, **34**, 48 is n² − 1 with 35 replaced by 34.',
    },
  ],
  comparisons: [
    {
      title: 'Which kind of series is it?',
      items: ['Difference', 'Multiplication', 'Square / cube', 'Alternating'],
      rows: [
        {
          aspect: 'What you see',
          values: ['Steady, slow growth', 'Terms roughly double or triple', 'Terms next to 4, 9, 16 or 8, 27, 64', 'Up and down, or two speeds'],
          key: true,
        },
        { aspect: 'Test', values: ['1st and 2nd differences', 'Ratio of neighbours', 'Compare with n² and n³', 'Split odd and even places'] },
        { aspect: 'Example', values: ['6, 11, 21, 36, 56', '3, 7, 15, 31, 63', '0, 7, 26, 63, 124', '5, 10, 8, 16, 14, 28'] },
        { aspect: 'Next term', values: ['81 (+25)', '127 (×2 + 1)', '215 (6³ − 1)', '26 (−2 after ×2)'] },
      ],
      reveal: 'The shape of the growth tells you which test to run first. Slow growth: differences. Fast growth: ratios. Near a square or cube: n² or n³. Zig-zag: split it.',
      whenToUse: [
        'Terms grow by small, changing steps.',
        'The last term is about two or three times the one before.',
        'Most terms are one or two away from a perfect square or cube.',
        'The series rises and falls, or has more than about 7 terms.',
      ],
    },
  ],
  shortcuts: [
    {
      pattern: 'Differences that grow in a pattern',
      example: '6, 11, 21, 36, 56, ?',
      options: ['76', '81', '86', '91'],
      answer: '81',
      ladder: [
        {
          name: 'Standard',
          steps: ['1st differences: 5, 10, 15, 20.', '2nd differences: 5, 5, 5.', 'Next 1st difference = 25, so 56 + 25 = 81.'],
          seconds: 35,
        },
        { name: 'Shortcut', steps: ['Differences are 5 × 1, 5 × 2, 5 × 3, 5 × 4.', 'Next is 5 × 5 = 25, so 81.'], seconds: 15 },
        {
          name: 'Option elimination',
          steps: ['The gaps rise by 5 each time, so the next gap is 25.', '76, 86 and 91 need gaps of 20, 30 and 35.', 'Only 81 (gap 25) fits.'],
          seconds: 10,
        },
      ],
    },
    {
      pattern: 'Terms one away from cubes',
      example: '0, 7, 26, 63, 124, ?',
      options: ['215', '216', '217', '225'],
      answer: '215',
      ladder: [
        {
          name: 'Standard',
          steps: ['1st differences: 7, 19, 37, 61.', '2nd differences: 12, 18, 24; 3rd: 6, 6.', 'Build back: 30 → 91 → 124 + 91 = 215.'],
          seconds: 60,
        },
        { name: 'Shortcut', steps: ['7, 26, 63, 124 are one less than 8, 27, 64, 125.', 'Rule n³ − 1, so 6³ − 1 = 215.'], seconds: 12 },
        {
          name: 'Option elimination',
          steps: ['216 is a cube itself and 217 is cube + 1: both break "one less".', '225 is 15², not near a cube.', '215 is left.'],
          seconds: 8,
        },
      ],
    },
    {
      pattern: 'Two rules taking turns',
      example: '5, 10, 8, 16, 14, 28, ?',
      options: ['24', '26', '30', '56'],
      answer: '26',
      ladder: [
        {
          name: 'Standard',
          steps: ['Differences: +5, −2, +8, −2, +14. No single pattern.', 'Try ratios on the rises: 10/5 = 2, 16/8 = 2, 28/14 = 2.', 'So ×2 and −2 alternate; next is 28 − 2 = 26.'],
          seconds: 45,
        },
        { name: 'Shortcut', steps: ['Every fall is −2, so the next step (a fall) is 28 − 2 = 26.'], seconds: 10 },
        {
          name: 'Option elimination',
          steps: ['The series just rose (14 → 28), so the next term must fall below 28.', '30 and 56 are out; the falls are always −2, so 26.'],
          seconds: 6,
        },
      ],
    },
  ],
  qa: [
    {
      q: 'What is the first thing to try on any number series?',
      a: ['The difference table.', 'If differences are steady or follow a pattern, you are done in one or two rows.'],
      tag: 'Asked often',
    },
    {
      q: 'When do you switch from differences to ratios?',
      a: ['When terms roughly double or triple.', 'Then test ×k ± c, for example ×2 + 1.'],
    },
    {
      q: 'List the squares and cubes worth knowing by heart.',
      a: ['Squares up to 30² = 900.', 'Cubes up to 15³ = 3375.', 'Then n² ± 1 and n³ ± 1 jump out at sight.'],
      tag: 'Shortcut',
    },
    {
      q: 'What does n(n + 1) look like?',
      a: ['2, 6, 12, 20, 30, 42, 56.', 'Its differences are 4, 6, 8, 10, 12: even numbers in a row.'],
    },
    {
      q: 'A series has 8 or more terms and zig-zags. What do you do?',
      a: ['Split it into odd places and even places.', 'Each half is usually a simple series.'],
      tag: 'Asked often',
    },
    {
      q: 'What is EJOTY?',
      a: ['E 5, J 10, O 15, T 20, Y 25.', 'Use it to turn any letter into its position in a second.'],
      tag: 'Shortcut',
    },
    {
      q: 'What is the reverse position of a letter?',
      a: ['27 − its position, so A = 26 and Z = 1.', 'Letters with the same sum of positions (27) are opposites: A-Z, B-Y, M-N.'],
    },
    {
      q: 'How do you solve an alphanumeric series like A1, C3, E5?',
      a: ['Solve the letters and the numbers as two separate series.', 'Then join the two answers.'],
    },
    {
      q: 'In a wrong-term question, how do you know you found the right term?',
      a: ['Changing that one term makes every other term fit the rule.', 'If you need to change two terms, your rule is wrong.'],
      tag: 'Trap',
    },
    {
      q: 'The letter gap goes past Z. What then?',
      a: ['Wrap round: subtract 26.', 'X (24) + 5 = 29 → 29 − 26 = 3 = C.'],
      tag: 'Trap',
    },
  ],
  quiz: [
    {
      type: 'mcq',
      difficulty: 'easy',
      question: '2, 6, 12, 20, 30, ?',
      options: ['40', '42', '44', '36'],
      answer: 1,
      explain: 'Each term is n(n + 1): 1×2, 2×3, 3×4, 4×5, 5×6. Next is 6 × 7 = 42.',
      shortcut: 'Differences are 4, 6, 8, 10, so the next difference is 12: 30 + 12 = 42.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: '3, 7, 15, 31, 63, ?',
      options: ['125', '126', '127', '131'],
      answer: 2,
      explain: 'Each term is the previous × 2 + 1. 63 × 2 + 1 = 127.',
      shortcut: 'The terms are 2ⁿ − 1 from n = 2: 4−1, 8−1, 16−1… Next is 128 − 1.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'B, E, H, K, ?',
      options: ['L', 'M', 'N', 'O'],
      answer: 2,
      explain: 'Positions 2, 5, 8, 11 rise by 3. Next is 14 = N.',
      shortcut: 'O is 15 (EJOTY), so 14 is the letter before it: N.',
    },
    {
      type: 'truefalse',
      difficulty: 'easy',
      statement: 'In the series 2, 3, 5, 9, 17, 33 each term is twice the previous term minus 1.',
      answer: true,
      explain: '2×2−1 = 3, 3×2−1 = 5, 5×2−1 = 9, 9×2−1 = 17, 17×2−1 = 33. The rule fits every term.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: '2, 5, 10, 17, 26, ?',
      options: ['35', '36', '37', '38'],
      answer: 2,
      explain: 'Each term is n² + 1: 1+1, 4+1, 9+1, 16+1, 25+1. Next is 36 + 1 = 37.',
      shortcut: 'Differences are the odd numbers 3, 5, 7, 9, so add 11.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: '0, 7, 26, 63, 124, ?',
      options: ['215', '216', '217', '225'],
      answer: 0,
      explain: 'Each term is n³ − 1: 1−1, 8−1, 27−1, 64−1, 125−1. Next is 216 − 1 = 215.',
      shortcut: 'Spot 63 and 124 as one less than the cubes 64 and 125.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: '5, 10, 8, 16, 14, 28, ?',
      options: ['24', '26', '30', '56'],
      answer: 1,
      explain: 'Two steps take turns: ×2, then −2. After 14 × 2 = 28 comes 28 − 2 = 26.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'Z, X, U, Q, ?',
      options: ['M', 'L', 'K', 'N'],
      answer: 1,
      explain: 'Positions 26, 24, 21, 17 fall by 2, 3, 4. Next fall is 5: 17 − 5 = 12 = L.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'AZ, BY, CX, DW, ?',
      options: ['EU', 'FV', 'EV', 'EW'],
      answer: 2,
      explain: 'First letters go A, B, C, D, E. Second letters go Z, Y, X, W, V (each is the opposite of the first). Next is EV.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: '7, 11, 13, 17, 19, ?',
      options: ['21', '22', '23', '25'],
      answer: 2,
      explain: 'These are prime numbers in order. The next prime after 19 is 23.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: '6, 11, 21, 36, 56, ?',
      options: ['76', '81', '86', '91'],
      answer: 1,
      explain: 'Differences are 5, 10, 15, 20. Next difference is 25, so 56 + 25 = 81.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'Find the wrong number in the series: 3, 8, 15, 24, 34, 48',
      options: ['8', '15', '24', '34'],
      answer: 3,
      explain: 'The rule is n² − 1: 3, 8, 15, 24, 35, 48. The fifth term should be 35, not 34.',
      shortcut: 'Differences 5, 7, 9, 10, 14 should be 5, 7, 9, 11, 13. The break is at 34.',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: '3, 4, 8, 17, 33, ?',
      options: ['54', '56', '58', '60'],
      answer: 2,
      explain: 'Differences are 1, 4, 9, 16: the squares. Next difference is 25, so 33 + 25 = 58.',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: 'B2, D8, F18, H32, ?',
      options: ['J48', 'J50', 'I50', 'K50'],
      answer: 1,
      explain: 'Letters skip one: B, D, F, H, J. Numbers are 2n²: 2, 8, 18, 32, 50. Answer J50.',
      shortcut: 'Each number is the letter position × n: B(2)×1, D(4)×2, F(6)×3, H(8)×4, J(10)×5 = 50.',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: '1, 2, 6, 24, 120, ?',
      options: ['240', '600', '720', '840'],
      answer: 2,
      explain: 'Multiply by 2, 3, 4, 5, then 6: 120 × 6 = 720. These are factorials: 1!, 2!, 3!, 4!, 5!, 6!.',
    },
  ],
};

export default topic;
