import type { Topic } from '@/content/types';

const topic: Topic = {
  id: 'algebra-identities',
  title: 'Identities and x + 1/x',
  level: 'intermediate',
  masteryMinutes: 150,
  reviseMinutes: 50,
  priority: 'high',
  weightage: { tier1: 2, tier2: 3 },
  tags: ['algebraic identities', 'x + 1/x', 'x − 1/x', 'a³ + b³ + c³ − 3abc', 'a + b + c = 0', 'put values', 'squares', 'cubes'],
  summary:
    'A dozen identities and the x + 1/x ladder answer most algebra questions. When the options are expressions, put simple numbers in and see which option matches.',
  patterns: [
    { name: 'x + 1/x = a, find x² + 1/x² or x³ + 1/x³', frequency: 'most', example: 'x + 1/x = 3. Find x³ + 1/x³.' },
    { name: 'a + b + c = 0 or a³ + b³ + c³ − 3abc', frequency: 'most', example: 'a + b + c = 0. Find (a³ + b³ + c³)/abc.' },
    { name: 'a + b and ab given, find a² + b² or a³ + b³', frequency: 'often', example: 'a + b = 7, ab = 12. Find a² + b².' },
    { name: 'Simplify using an identity', frequency: 'often', example: '(a² − b²)/(a − b) with a = 7, b = 3.' },
    { name: 'x − 1/x family', frequency: 'often', example: 'x − 1/x = 4. Find x² + 1/x².' },
    { name: 'Put values to eliminate options', frequency: 'rare', example: 'If a = b = c, which expression is 3?' },
  ],
  keyPoints: [
    {
      title: 'Square identities',
      text: '(a + b)² = a² + 2ab + b², (a − b)² = a² − 2ab + b², a² − b² = (a + b)(a − b). Also (a + b)² − (a − b)² = 4ab and (a + b)² + (a − b)² = 2(a² + b²).',
      formula: 'a² + b² = (a + b)² − 2ab',
      example: 'a + b = 10, ab = 21: a² + b² = 100 − 42 = **58**.',
    },
    {
      title: 'Cube identities',
      text: '(a + b)³ = a³ + b³ + 3ab(a + b) and (a − b)³ = a³ − b³ − 3ab(a − b). Sum and difference of cubes: a³ + b³ = (a + b)(a² − ab + b²), a³ − b³ = (a − b)(a² + ab + b²).',
      formula: 'a³ + b³ = (a + b)³ − 3ab(a + b)',
      example: '(0.73³ + 0.27³) ÷ (0.73² − 0.73 × 0.27 + 0.27²) = 0.73 + 0.27 = **1**.',
    },
    {
      title: 'Three variables',
      text: '(a + b + c)² = a² + b² + c² + 2(ab + bc + ca). Use it to get any one of the three pieces from the other two.',
      formula: '(a + b + c)² = a² + b² + c² + 2(ab + bc + ca)',
      example: 'a + b + c = 6, a² + b² + c² = 14: ab + bc + ca = (36 − 14)/2 = **11**.',
    },
    {
      title: 'a³ + b³ + c³ − 3abc',
      text: 'It factors as (a + b + c)(a² + b² + c² − ab − bc − ca). The second bracket also equals ½[(a − b)² + (b − c)² + (c − a)²].',
      formula: 'a³ + b³ + c³ − 3abc = (a + b + c)(a² + b² + c² − ab − bc − ca)',
      example: 'a, b, c = 2019, 2020, 2021: second bracket = ½(1 + 1 + 4) = 3, so the value = 6,060 × 3 = **18,180**.',
    },
    {
      title: 'The a + b + c = 0 case',
      text: 'If a + b + c = 0, then a³ + b³ + c³ = 3abc. Watch for hidden zero sums like (a − b) + (b − c) + (c − a).',
      formula: 'a + b + c = 0 ⇒ a³ + b³ + c³ = 3abc',
      example: '[(a − b)³ + (b − c)³ + (c − a)³] ÷ [(a − b)(b − c)(c − a)] = **3**.',
    },
    {
      title: 'The x + 1/x ladder',
      text: 'If x + 1/x = a, square to climb: x² + 1/x² = a² − 2, then x⁴ + 1/x⁴ = (a² − 2)² − 2. Cube for the odd step: x³ + 1/x³ = a³ − 3a.',
      formula: 'x² + 1/x² = a² − 2; x³ + 1/x³ = a³ − 3a',
      example: 'x + 1/x = 3: x² + 1/x² = **7**, x³ + 1/x³ = 27 − 9 = **18**, x⁴ + 1/x⁴ = 49 − 2 = **47**.',
    },
    {
      title: 'The x − 1/x family',
      text: 'If x − 1/x = b, then x² + 1/x² = b² + 2 and x³ − 1/x³ = b³ + 3b. The two families are linked by (x + 1/x)² − (x − 1/x)² = 4.',
      formula: 'x² + 1/x² = b² + 2; x³ − 1/x³ = b³ + 3b',
      example: 'x − 1/x = 4: x² + 1/x² = **18**. x − 1/x = 3: x³ − 1/x³ = 27 + 9 = **36**.',
    },
    {
      title: 'Put values to kill options',
      text: 'When the options are expressions, choose small numbers that fit the condition (avoid 0 and values that make two options equal), work out the question, and keep the option that matches. Special case: x + 1/x = 2 means x = 1 (for real x).',
      example: 'x + 1/x = 2 ⇒ x = 1, so x¹⁰⁰ + 1/x¹⁰⁰ = **2**.',
    },
  ],
  comparisons: [
    {
      title: 'x + 1/x family vs x − 1/x family',
      items: ['x + 1/x = a', 'x − 1/x = b'],
      rows: [
        { aspect: 'x² + 1/x²', values: ['**a² − 2**', '**b² + 2**'], key: true },
        { aspect: 'Odd cube', values: ['x³ + 1/x³ = a³ − 3a', 'x³ − 1/x³ = b³ + 3b'] },
        { aspect: 'Example: a = 3 or b = 3', values: ['x² + 1/x² = 7, x³ + 1/x³ = 18', 'x² + 1/x² = 11, x³ − 1/x³ = 36'] },
        { aspect: 'Get the other one', values: ['(x − 1/x)² = a² − 4', '(x + 1/x)² = b² + 4'] },
        { aspect: 'Smallest value (x > 0)', values: ['a ≥ 2, equal to 2 only at x = 1', 'Any real value'] },
      ],
      reveal: 'The sign flips because squaring x − 1/x gives −2, not +2. So the minus family adds back what the plus family takes away.',
      whenToUse: [
        'The question gives x + 1/x, or a quadratic like x² − 4x + 1 = 0 (divide by x).',
        'The question gives x − 1/x, or a quadratic like x² − 3x − 1 = 0.',
      ],
    },
  ],
  shortcuts: [
    {
      pattern: 'x + 1/x given, cube wanted',
      example: 'If x + 1/x = 3, find the value of x³ + 1/x³.',
      options: ['18', '27', '24', '36'],
      answer: '18',
      ladder: [
        {
          name: 'Standard',
          steps: ['Cube both sides: x³ + 1/x³ + 3(x + 1/x) = 27.', 'x³ + 1/x³ = 27 − 3 × 3 = 18.'],
          seconds: 30,
        },
        { name: 'Shortcut', steps: ['a³ − 3a = 27 − 9 = 18.'], seconds: 5 },
        {
          name: 'Factor route',
          steps: ['x³ + 1/x³ = (x + 1/x)(x² + 1/x² − 1).', 'x² + 1/x² = 7, so the value = 3 × 6 = 18.'],
          seconds: 15,
        },
      ],
    },
    {
      pattern: 'Hidden a + b + c = 0',
      example: 'Find the value of [(a − b)³ + (b − c)³ + (c − a)³] ÷ [(a − b)(b − c)(c − a)].',
      options: ['3', '0', '1', 'abc'],
      answer: '3',
      ladder: [
        {
          name: 'Standard',
          steps: ['Expand all three cubes and the product.', 'Collect terms: long and easy to slip.'],
          seconds: 120,
        },
        {
          name: 'Shortcut',
          steps: ['(a − b) + (b − c) + (c − a) = 0.', 'So the sum of cubes = 3 × product, and the ratio is 3.'],
          seconds: 10,
        },
        {
          name: 'Put values',
          steps: ['a = 1, b = 2, c = 3: top = (−1)³ + (−1)³ + 2³ = 6.', 'Bottom = (−1)(−1)(2) = 2. Ratio = 3.'],
          seconds: 20,
        },
      ],
    },
    {
      pattern: 'Expression options: put values',
      example: 'If x = a(b − c), y = b(c − a) and z = c(a − b), then (x/a)³ + (y/b)³ + (z/c)³ equals:',
      options: ['(xyz)/(abc)', '3(xyz)/(abc)', 'xyz', '3abc'],
      answer: '3(xyz)/(abc)',
      ladder: [
        {
          name: 'Standard',
          steps: ['x/a = b − c, y/b = c − a, z/c = a − b.', 'Expand (b − c)³ + (c − a)³ + (a − b)³ and match it to each option.'],
          seconds: 90,
        },
        {
          name: 'Shortcut',
          steps: ['x/a + y/b + z/c = 0, so the sum of cubes = 3 × (x/a)(y/b)(z/c).', '= 3(xyz)/(abc).'],
          seconds: 15,
        },
        {
          name: 'Put values',
          steps: [
            'a = 1, b = 2, c = 3: x = −1, y = 4, z = −3.',
            'Question: (−1)³ + 2³ + (−1)³ = 6.',
            'Options: (xyz)/(abc) = 2, 3(xyz)/(abc) = 6, xyz = 12, 3abc = 18. Only 3(xyz)/(abc) fits.',
          ],
          seconds: 30,
        },
      ],
    },
  ],
  qa: [
    {
      q: 'If x + 1/x = a, what are x² + 1/x² and x³ + 1/x³?',
      a: ['x² + 1/x² = a² − 2.', 'x³ + 1/x³ = a³ − 3a.'],
      tag: 'Asked often',
    },
    {
      q: 'If x − 1/x = b, what is x² + 1/x²?',
      a: ['b² + 2, not b² − 2.', 'Squaring x − 1/x gives x² − 2 + 1/x².'],
      tag: 'Trap',
    },
    {
      q: 'If a + b + c = 0, what is a³ + b³ + c³?',
      a: ['3abc.', 'So (a³ + b³ + c³)/abc = 3.'],
      tag: 'Asked often',
    },
    {
      q: 'How do you factor a³ + b³ + c³ − 3abc?',
      a: ['(a + b + c)(a² + b² + c² − ab − bc − ca).', 'The second bracket = ½[(a − b)² + (b − c)² + (c − a)²].'],
      tag: 'Shortcut',
    },
    {
      q: 'How do you turn x² − 4x + 1 = 0 into the x + 1/x form?',
      a: ['Divide by x: x − 4 + 1/x = 0.', 'So x + 1/x = 4, then x³ + 1/x³ = 64 − 12 = 52.'],
      tag: 'Shortcut',
    },
    {
      q: 'x + 1/x = 2. What is x¹⁰⁰ + 1/x¹⁰⁰?',
      a: ['x + 1/x = 2 only when x = 1 (for real x).', 'So any power gives 1 + 1 = 2.'],
      tag: 'Trap',
    },
    {
      q: 'How do you go from x⁴ + 1/x⁴ back down the ladder?',
      a: ['Add 2 and take the root: x² + 1/x² = √(x⁴ + 1/x⁴ + 2).', '119 → √121 = 11. Then x − 1/x = √(11 − 2) = 3 for x > 1.'],
    },
    {
      q: 'What are (a + b)² − (a − b)² and (a + b)² + (a − b)²?',
      a: ['(a + b)² − (a − b)² = 4ab.', '(a + b)² + (a − b)² = 2(a² + b²).'],
    },
    {
      q: 'When should you put values instead of solving?',
      a: ['When the options are expressions, not numbers.', 'Pick small numbers that fit the condition; avoid 0 and values that make two options equal.'],
      tag: 'Shortcut',
    },
    {
      q: 'Simplify (a³ + b³)/(a² − ab + b²).',
      a: ['a³ + b³ = (a + b)(a² − ab + b²).', 'So the answer is a + b.'],
    },
  ],
  quiz: [
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'If x + 1/x = 3, what is the value of x² + 1/x²?',
      options: ['9', '11', '7', '5'],
      answer: 2,
      explain: 'Square both sides: x² + 2 + 1/x² = 9, so x² + 1/x² = 7.',
      shortcut: 'a² − 2 = 9 − 2 = 7.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'If x + 1/x = 3, what is the value of x³ + 1/x³?',
      options: ['18', '27', '24', '36'],
      answer: 0,
      explain: 'Cube: x³ + 1/x³ + 3(x + 1/x) = 27, so x³ + 1/x³ = 27 − 9 = 18.',
      shortcut: 'a³ − 3a = 27 − 9 = 18.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'If a + b = 10 and ab = 21, what is a² + b²?',
      options: ['79', '58', '100', '42'],
      answer: 1,
      explain: 'a² + b² = (a + b)² − 2ab = 100 − 42 = 58.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'If a + b = 7 and ab = 12, what is a³ + b³?',
      options: ['175', '91', '343', '127'],
      answer: 1,
      explain: 'Use a³ + b³ = (a + b)³ − 3ab(a + b). So a³ + b³ = 7³ − 3 × 12 × 7 = 343 − 252 = 91.',
      shortcut: 'The numbers are 3 and 4 (sum 7, product 12): 27 + 64 = 91.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'If x − 1/x = 4, what is the value of x² + 1/x²?',
      options: ['14', '16', '20', '18'],
      answer: 3,
      explain: 'Square: x² − 2 + 1/x² = 16, so x² + 1/x² = 18.',
      shortcut: 'b² + 2 = 18.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'If x + 1/x = 3, what is the value of x⁴ + 1/x⁴?',
      options: ['49', '47', '51', '79'],
      answer: 1,
      explain: 'x² + 1/x² = 9 − 2 = 7. Square again: x⁴ + 1/x⁴ = 49 − 2 = 47.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'If a + b + c = 0, what is the value of (a³ + b³ + c³)/abc?',
      options: ['0', '1', '3', '−3'],
      answer: 2,
      explain: 'When a + b + c = 0, a³ + b³ + c³ = 3abc, so the ratio is 3.',
      shortcut: 'Put a = 1, b = 1, c = −2: (1 + 1 − 8)/(−2) = 3.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'If a + b + c = 9, ab + bc + ca = 26 and abc = 24, what is a³ + b³ + c³?',
      options: ['99', '91', '117', '81'],
      answer: 0,
      explain: 'a² + b² + c² = 81 − 52 = 29. a³ + b³ + c³ = 3abc + (a + b + c)(29 − 26) = 72 + 27 = 99.',
      shortcut: 'The numbers are 2, 3, 4 (sum 9, product 24): 8 + 27 + 64 = 99.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'If x = √3 + √2, what is the value of x² + 1/x²?',
      options: ['12', '8', '10', '2√6'],
      answer: 2,
      explain: '1/x = √3 − √2, so x + 1/x = 2√3. Then x² + 1/x² = 12 − 2 = 10.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'If x + 1/x = 2, what is the value of x¹⁰⁰ + 1/x¹⁰⁰?',
      options: ['2¹⁰⁰', '0', '100', '2'],
      answer: 3,
      explain: 'x + 1/x = 2 gives (x − 1)² = 0, so x = 1. Then 1 + 1 = 2.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'If x² − 4x + 1 = 0, what is the value of x³ + 1/x³?',
      options: ['64', '52', '76', '48'],
      answer: 1,
      explain: 'Divide by x: x + 1/x = 4. Then x³ + 1/x³ = 64 − 12 = 52.',
      shortcut: 'a³ − 3a with a = 4.',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: 'If x⁴ + 1/x⁴ = 119 and x > 1, what is the value of x³ − 1/x³?',
      options: ['30', '27', '36', '33'],
      answer: 2,
      explain: 'x² + 1/x² = √(119 + 2) = 11. (x − 1/x)² = 11 − 2 = 9, so x − 1/x = 3 (x > 1). x³ − 1/x³ = 27 + 3 × 3 = 36.',
      shortcut: 'b³ + 3b with b = 3.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'What is the value of (0.73 × 0.73 × 0.73 + 0.27 × 0.27 × 0.27) ÷ (0.73 × 0.73 − 0.73 × 0.27 + 0.27 × 0.27)?',
      options: ['0.46', '1', '0.73', '2'],
      answer: 1,
      explain: '(a³ + b³)/(a² − ab + b²) = a + b = 0.73 + 0.27 = 1.',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: 'If a = 2019, b = 2020 and c = 2021, what is the value of a³ + b³ + c³ − 3abc?',
      options: ['6,060', '18,000', '12,120', '18,180'],
      answer: 3,
      explain: 'a + b + c = 6,060. a² + b² + c² − ab − bc − ca = ½[(1)² + (1)² + (2)²] = 3. Value = 6,060 × 3 = 18,180.',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: 'If a/b + b/a = 1 (a, b ≠ 0), what is the value of a³ + b³?',
      options: ['0', '1', 'ab', 'a + b'],
      answer: 0,
      explain: 'a/b + b/a = 1 gives a² + b² = ab, so a² − ab + b² = 0. Then a³ + b³ = (a + b)(a² − ab + b²) = 0. (No real a, b satisfy the condition, but the identity still gives 0.)',
    },
    {
      type: 'truefalse',
      difficulty: 'easy',
      statement: '(a + b)³ = a³ + b³ + 3ab(a + b).',
      answer: true,
      explain: '(a + b)³ = a³ + 3a²b + 3ab² + b³, and 3a²b + 3ab² = 3ab(a + b).',
    },
    {
      type: 'truefalse',
      difficulty: 'medium',
      statement: 'If x − 1/x = 3, then x² + 1/x² = 7.',
      answer: false,
      explain: 'Squaring x − 1/x gives x² − 2 + 1/x² = 9, so x² + 1/x² = 11. The value 7 is for x + 1/x = 3.',
    },
  ],
};

export default topic;
