import type { Topic } from '@/content/types';

const topic: Topic = {
  id: 'average',
  title: 'Average',
  level: 'beginner',
  masteryMinutes: 60,
  reviseMinutes: 20,
  priority: 'high',
  weightage: { tier1: 1, tier2: 1 },
  tags: ['average', 'mean', 'replacement', 'new member', 'cricket average', 'consecutive numbers', 'weighted average'],
  summary:
    'Average = total ÷ count, so almost every question is about the total. When a member joins, leaves or is replaced, the change in the average times the count tells you how the total moved.',
  patterns: [
    { name: 'One member replaced', frequency: 'most', example: 'Average of 8 men rises 2.5 kg when a 65 kg man is replaced. New man?' },
    { name: 'New member joins or one leaves', frequency: 'most', example: 'Average age of 30 students is 15; with the teacher it is 16. Teacher?' },
    { name: 'Cricket average after an innings', frequency: 'often', example: 'Scoring 87 in the 17th innings raises the average by 3. New average?' },
    { name: 'Overlapping groups (find the middle value)', frequency: 'often', example: 'Average of 11 results is 50; first six 49, last six 52. Sixth result?' },
    { name: 'Consecutive numbers', frequency: 'often', example: 'Average of 5 consecutive odd numbers is 27. Largest?' },
    { name: 'Combined (weighted) average of groups', frequency: 'often', example: '30 students average 40, 20 students average 50. Overall?' },
    { name: 'Wrong entry corrected', frequency: 'rare', example: 'A 64 was read as 46 among 40 numbers. Correct average?' },
  ],
  keyPoints: [
    {
      title: 'Average and total',
      text: 'Average is the total shared equally. Turn every average into a total first; totals can be added and subtracted, averages cannot.',
      formula: 'Average = (Sum of observations)/(Number of observations)',
      example: 'Average of 7 numbers is 24: total = 168. Multiply each by 3: average becomes 72.',
    },
    {
      title: 'One member replaced',
      text: 'The count stays n. If the average rises by d, the newcomer is n × d heavier than the person who left; if it falls, lighter.',
      formula: 'new member = old member + n × (change in average)',
      example: '8 men, average up 2.5 kg, 65 kg man replaced: 65 + 8 × 2.5 = **85 kg**.',
    },
    {
      title: 'New member joins',
      text: 'n members, average rises by d when one joins. The newcomer brings the new average for himself plus d for each of the n old members.',
      formula: 'newcomer = new average + n × rise',
      example: '30 students average 15; with the teacher it is 16: 16 + 30 × 1 = **46 years**.',
    },
    {
      title: 'One member leaves',
      text: 'n members with average A. One leaves and the average falls by d. The leaver took A for himself plus d for each of the n − 1 who stayed.',
      formula: 'leaver = old average + (n − 1) × fall',
      example: '25 members average 40; one leaves and it becomes 39: 40 + 24 × 1 = **64**.',
    },
    {
      title: 'Cricket average',
      text: 'A batsman scores R in his nth innings and his average rises by d. The runs above the new average paid for the rise in all n − 1 earlier innings.',
      formula: 'new average = R − (n − 1) × rise',
      example: '87 in the 17th innings, rise of 3: 87 − 16 × 3 = **39**.',
    },
    {
      title: 'Consecutive numbers and series',
      text: 'For numbers in equal steps (consecutive, consecutive odd or even), the average is the middle term, or the mean of the first and last.',
      formula: 'Average = (first + last)/2; first n natural numbers: (n + 1)/2',
      example: '5 consecutive odd numbers with average 27: 23, 25, 27, 29, 31. Largest **31**. First n odd numbers average n; first n even numbers average n + 1.',
    },
    {
      title: 'Combined and weighted average',
      text: 'When groups of different sizes merge, weight each average by its size. The result lies between the two and nearer the bigger group.',
      formula: 'Average = (n₁a₁ + n₂a₂)/(n₁ + n₂)',
      example: '30 students at 40 and 20 at 50: (1200 + 1000)/50 = **44**.',
    },
    {
      title: 'Overlapping groups and wrong entries',
      text: 'Middle value = sum of the first part + sum of the last part − whole total. A wrong entry shifts the average by the error spread over the count.',
      formula: 'correct average = wrong average + (correct − wrong)/n',
      example: '11 results average 50, first six 49, last six 52: 294 + 312 − 550 = **56**.',
    },
  ],
  comparisons: [
    {
      title: 'Joins vs leaves vs replaced',
      items: ['Member joins', 'Member leaves', 'Member replaced'],
      rows: [
        { aspect: 'Count', values: ['n → n + 1', 'n → n − 1', 'Stays n'] },
        { aspect: 'Formula', values: ['new average + n × rise', 'old average + (n − 1) × fall', 'old member + n × rise'], key: true },
        { aspect: 'Example', values: ['30 at 15 → 16: 46', '25 at 40 → 39: 64', '8 men, +2.5, 65 out: 85'] },
      ],
      reveal: 'Each formula is the same idea: the person carries one average for himself and the change for every other member who is counted.',
      whenToUse: [
        'Someone is added: teacher included, new player joins.',
        'Someone drops out and the count falls.',
        'One person swaps for another and the count is unchanged.',
      ],
    },
    {
      title: 'Simple vs weighted average',
      items: ['Simple average', 'Weighted average'],
      rows: [
        { aspect: 'Use when', values: ['Each value counts once', 'Groups of different sizes are combined'] },
        { aspect: 'Class A 30 at 40, class B 20 at 50', values: ['(40 + 50)/2 = 45 (wrong here)', '(1200 + 1000)/50 = **44**'], key: true },
        { aspect: 'Equal group sizes', values: ['Same answer', 'Same answer'] },
      ],
      reveal: 'Averaging two averages is right only when the groups are the same size.',
      whenToUse: ['Plain list of values.', 'Two or more classes, sections or batches with their own averages.'],
    },
  ],
  shortcuts: [
    {
      pattern: 'Replacement changes the average',
      example: 'The average weight of 8 men rises by 2.5 kg when a man weighing 65 kg is replaced by a new man. What is the weight of the new man?',
      options: ['80 kg', '85 kg', '82.5 kg', '75 kg'],
      answer: '85 kg',
      ladder: [
        { name: 'Standard', steps: ['Let the old average be x: total 8x.', 'New total 8x − 65 + w = 8(x + 2.5).', 'w = 65 + 20 = 85 kg.'], seconds: 40 },
        { name: 'Shortcut', steps: ['Total rises by 8 × 2.5 = 20.', 'New man = 65 + 20 = 85 kg.'], seconds: 10 },
      ],
    },
    {
      pattern: 'Cricket average after one innings',
      example: 'A batsman scores 87 runs in his 17th innings and raises his average by 3. What is his average after the 17th innings?',
      options: ['36', '39', '40', '42'],
      answer: '39',
      ladder: [
        { name: 'Standard', steps: ['Old average x: 16x + 87 = 17(x + 3).', 'x = 87 − 51 = 36.', 'New average = 39.'], seconds: 40 },
        { name: 'Shortcut', steps: ['New average = 87 − 16 × 3 = 39.'], seconds: 8 },
        { name: 'Put values', steps: ['Try 39: old average 36. 16 × 36 + 87 = 663 = 17 × 39. Match.'], seconds: 20 },
      ],
    },
    {
      pattern: 'Overlapping groups',
      example: 'The average of 11 results is 50. The average of the first six is 49 and of the last six is 52. Find the sixth result.',
      options: ['54', '56', '58', '60'],
      answer: '56',
      ladder: [
        { name: 'Standard', steps: ['First six: 294. Last six: 312. All eleven: 550.', 'The sixth is counted twice: 294 + 312 − 550 = 56.'], seconds: 30 },
        {
          name: 'Shortcut',
          steps: ['Work in deviations from 50.', 'First six: 6 × (−1) = −6. Last six: 6 × (+2) = +12.', 'Sixth = 50 − 6 + 12 = 56.'],
          seconds: 12,
        },
      ],
    },
  ],
  qa: [
    {
      q: 'A member is replaced and the average rises by d. How heavy is the newcomer?',
      a: ['Old member + n × d, with n the group size.', 'The count does not change.'],
      tag: 'Asked often',
    },
    {
      q: 'Teacher joins n students and the average rises by d. Teacher’s age?',
      a: ['New average + n × d.', 'Or old average + (n + 1) × d. Both give the same.'],
      tag: 'Asked often',
    },
    {
      q: 'Cricket: R runs in the nth innings raise the average by d. New average?',
      a: ['R − (n − 1) × d.', '98 in the 19th innings, up by 4: 98 − 72 = 26.'],
      tag: 'Shortcut',
    },
    {
      q: 'Average of 5 consecutive numbers?',
      a: ['The middle (3rd) number.', 'For an even count, the mean of the two middle numbers.'],
      tag: 'Shortcut',
    },
    {
      q: 'Average of the first n natural numbers?',
      a: ['(n + 1)/2.', 'First 50: 25.5.'],
    },
    {
      q: 'Can you average two class averages directly?',
      a: ['Only if the classes are the same size.', 'Otherwise weight by the number of students.'],
      tag: 'Trap',
    },
    {
      q: 'Every value rises by 5. What happens to the average?',
      a: ['It rises by 5, not by 5 × count.', 'Multiply every value by 3 and the average is multiplied by 3.'],
      tag: 'Trap',
    },
    {
      q: 'How do you correct an average after a misread entry?',
      a: ['Add (correct − wrong) ÷ n to the old average.', '64 read as 46 among 40 values: +18/40 = +0.45.'],
    },
    {
      q: 'What is the deviation method?',
      a: ['Pick a working average, add up how far each value is above or below it.', 'Average = working average + (total deviation)/n.'],
      tag: 'Shortcut',
    },
    {
      q: 'Husband and wife averaged 23 at marriage. Five years later, with a child, the family averages 20. Child’s age?',
      a: ['Couple now: 46 + 10 = 56.', 'Family: 3 × 20 = 60. Child = 4 years.'],
    },
  ],
  quiz: [
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'What is the average of the first 50 natural numbers?',
      options: ['25', '25.5', '26', '50.5'],
      answer: 1,
      explain: '(n + 1)/2 = 51/2 = 25.5.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'The average of 5 consecutive odd numbers is 27. What is the largest of them?',
      options: ['29', '33', '31', '35'],
      answer: 2,
      explain: 'The middle number is 27, so the numbers are 23, 25, 27, 29, 31. Largest 31.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'Class A has 30 students with an average of 40 marks and class B has 20 students with an average of 50. What is the average of both classes together?',
      options: ['45', '44', '46', '42'],
      answer: 1,
      explain: '(30 × 40 + 20 × 50)/50 = 2200/50 = 44.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'The average of 7 numbers is 24. If each number is multiplied by 3, what is the new average?',
      options: ['27', '72', '504', '24'],
      answer: 1,
      explain: 'Multiplying every value by 3 multiplies the average by 3: 72.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'The average weight of 10 students increases by 1.5 kg when one student weighing 48 kg is replaced by a new student. What is the weight of the new student?',
      options: ['58 kg', '63 kg', '61.5 kg', '49.5 kg'],
      answer: 1,
      explain: 'Total rises by 10 × 1.5 = 15 kg. New student = 48 + 15 = 63 kg.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'The average age of 30 students is 15 years. When the teacher’s age is included, the average becomes 16 years. What is the teacher’s age?',
      options: ['31 years', '45 years', '46 years', '47 years'],
      answer: 2,
      explain: '31 × 16 − 30 × 15 = 496 − 450 = 46.',
      shortcut: 'New average + n × rise = 16 + 30 × 1 = 46.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'A batsman scores 98 runs in his 19th innings, which raises his average by 4. What is his average after the 19th innings?',
      options: ['22', '24', '30', '26'],
      answer: 3,
      explain: '18x + 98 = 19(x + 4) gives x = 22. New average 26.',
      shortcut: '98 − 18 × 4 = 26.',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: 'The average of 13 results is 60. The average of the first 7 is 57 and the average of the last 7 is 64. What is the 7th result?',
      options: ['67', '64', '60', '71'],
      answer: 0,
      explain: '7 × 57 + 7 × 64 − 13 × 60 = 399 + 448 − 780 = 67.',
      shortcut: 'Deviations from 60: 7 × (−3) + 7 × (+4) = +7. Seventh = 60 + 7 = 67.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'The average of 40 numbers was found to be 36. Later it was found that 64 had been read as 46. What is the correct average?',
      options: ['36.45', '36.54', '35.55', '36.18'],
      answer: 0,
      explain: 'The total was 64 − 46 = 18 short. Correct average = 36 + 18/40 = 36.45.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'The average age of 25 members of a club is 40 years. One member leaves and the average becomes 39 years. What is the age of the member who left?',
      options: ['39 years', '64 years', '65 years', '49 years'],
      answer: 1,
      explain: '25 × 40 − 24 × 39 = 1000 − 936 = 64.',
      shortcut: 'Old average + (n − 1) × fall = 40 + 24 × 1 = 64.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'The average of 6 consecutive even numbers is 25. What is the smallest of them?',
      options: ['22', '18', '24', '20'],
      answer: 3,
      explain: 'The two middle numbers are 24 and 26. So the numbers are 20, 22, 24, 26, 28, 30. Smallest 20.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'The average of 10 innings of a batsman is 32. How many runs must he score in the next innings to raise his average by 4?',
      options: ['72', '76', '36', '80'],
      answer: 1,
      explain: 'New total = 11 × 36 = 396. Old total = 320. Needed: 76.',
      shortcut: 'New average + n × rise = 36 + 10 × 4 = 76.',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: 'The average of three numbers is 28. The first is twice the second and the second is twice the third. What is the largest number?',
      options: ['42', '56', '48', '36'],
      answer: 2,
      explain: 'Let the third be c: numbers 4c, 2c, c. 7c = 3 × 28 = 84, so c = 12 and the largest is 48.',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: 'At the time of their marriage, the average age of a husband and wife was 23 years. Five years later, with one child, the average age of the family is 20 years. How old is the child?',
      options: ['3 years', '5 years', '2 years', '4 years'],
      answer: 3,
      explain: 'Couple then: 46. Five years later: 56. Family total now: 3 × 20 = 60. Child = 4 years.',
    },
    {
      type: 'truefalse',
      difficulty: 'easy',
      statement: 'The average of 5 consecutive integers is equal to the middle integer.',
      answer: true,
      explain: 'The numbers are equally spaced around the middle one, so the gaps cancel.',
    },
    {
      type: 'truefalse',
      difficulty: 'medium',
      statement: 'If every number in a set of 10 numbers is increased by 5, the average increases by 50.',
      answer: false,
      explain: 'The total rises by 50, but the average rises by 50 ÷ 10 = 5.',
    },
  ],
};

export default topic;
