import type { Topic } from '@/content/types';

const topic: Topic = {
  id: 'circles',
  title: 'Circles',
  level: 'advanced',
  masteryMinutes: 150,
  reviseMinutes: 50,
  priority: 'high',
  weightage: { tier1: 1, tier2: 1.5 },
  tags: ['chord', 'tangent', 'secant', 'angle in a semicircle', 'cyclic quadrilateral', 'alternate segment', 'common tangents', 'intersecting chords'],
  summary:
    'Most circle questions hide a right triangle: radius, half-chord and distance, or radius, tangent and distance to the centre. Add the angle rules and the cyclic quadrilateral and you cover nearly all of it.',
  patterns: [
    { name: 'Chord length and distance from the centre', frequency: 'most', example: 'A chord of 16 cm lies in a circle of radius 10 cm. How far is it from the centre?' },
    { name: 'Tangent length and two tangents from a point', frequency: 'most', example: 'P is 13 cm from the centre of a circle of radius 5 cm. Length of the tangent?' },
    { name: 'Direct and transverse common tangents', frequency: 'often', example: 'Radii 8 and 3 cm, centres 13 cm apart. Length of the direct common tangent?' },
    { name: 'Angle at the centre, same segment, semicircle', frequency: 'often', example: '∠AOB = 110°. Find ∠ACB for C on the major arc.' },
    { name: 'Cyclic quadrilateral angles', frequency: 'often', example: 'ABCD is cyclic and ∠A = 75°. Find ∠C.' },
    { name: 'Intersecting chords and tangent-secant', frequency: 'often', example: 'PA = 4, AB = 5 on a secant, PT a tangent. Find PT.' },
    { name: 'Alternate segment theorem', frequency: 'rare', example: 'A chord makes 65° with the tangent at its end. Angle in the other segment?' },
  ],
  keyPoints: [
    {
      title: 'Chords',
      text: 'The perpendicular from the centre bisects a chord. So radius, half-chord and distance from the centre make a right triangle. Equal chords are equally far from the centre, and a longer chord is nearer the centre.',
      formula: 'chord = 2√(r² − d²)',
      example: 'r = 10, chord 16: half-chord 8, so d = √(100 − 64) = **6**.',
    },
    {
      title: 'Angles in a circle',
      text: 'The angle an arc makes at the centre is twice the angle it makes anywhere on the rest of the circle. Angles in the same segment are equal. The angle in a semicircle is 90°.',
      formula: '∠AOB = 2∠ACB',
      example: '∠AOB = 110°, so ∠ACB = **55°** for C on the major arc.',
    },
    {
      title: 'Cyclic quadrilateral',
      text: 'When all four corners lie on a circle, opposite angles add to 180°. An exterior angle equals the interior opposite angle.',
      formula: '∠A + ∠C = 180°, ∠B + ∠D = 180°',
      example: '∠A = 75° gives ∠C = **105°**.',
    },
    {
      title: 'Tangents from a point',
      text: 'A tangent is perpendicular to the radius at the point of contact. The two tangents from an outside point are equal. The angle between them and the angle at the centre add to 180°.',
      formula: 'tangent = √(d² − r²); ∠APB + ∠AOB = 180°',
      example: 'd = 13, r = 5: tangent = √(169 − 25) = **12**.',
    },
    {
      title: 'Alternate segment theorem',
      text: 'The angle between a tangent and a chord through the point of contact equals the angle the chord makes in the other segment.',
      example: 'Tangent-chord angle 65°, so the angle in the alternate segment is **65°**.',
    },
    {
      title: 'Intersecting chords and tangent-secant',
      text: 'Chords AB and CD meeting at P (inside or outside the circle): PA × PB = PC × PD. For a tangent PT and a secant PAB from the same outside point: PT² = PA × PB.',
      formula: 'PA × PB = PC × PD; PT² = PA × PB',
      example: 'PA = 4, AB = 5, so PB = 9 and PT = √36 = **6**.',
    },
    {
      title: 'Common tangents of two circles',
      text: 'A direct common tangent does not cross the line of centres; a transverse one does. With d the distance between the centres:',
      formula: 'direct = √(d² − (r₁ − r₂)²); transverse = √(d² − (r₁ + r₂)²)',
      example: 'r₁ = 8, r₂ = 3, d = 13: direct √(169 − 25) = **12**, transverse √(169 − 121) = **4√3**.',
    },
    {
      title: 'Quadrilateral around a circle',
      text: 'When a circle touches all four sides of a quadrilateral, the sums of opposite sides are equal, since the tangents from each corner are equal.',
      formula: 'AB + CD = AD + BC',
      example: 'AB = 6, BC = 7, CD = 4: AD = 6 + 4 − 7 = **3**.',
    },
  ],
  comparisons: [
    {
      title: 'Direct vs transverse common tangent',
      items: ['Direct common tangent', 'Transverse common tangent'],
      rows: [
        { aspect: 'Crosses the line of centres?', values: ['No', 'Yes, between the circles'] },
        { aspect: 'Length', values: ['√(d² − (r₁ − r₂)²)', '√(d² − (r₁ + r₂)²)'], key: true },
        { aspect: 'Exists when', values: ['Neither circle lies inside the other', 'The circles do not overlap (d ≥ r₁ + r₂)'] },
        { aspect: 'r = 8 and 3, d = 13', values: ['12', '4√3'] },
      ],
      reveal: 'The only change is the sign between the radii: minus for direct, plus for transverse. So the direct tangent is always the longer one.',
      whenToUse: ['"Direct", "external" or both circles on the same side of the tangent.', '"Transverse", "internal" or the tangent passes between the circles.'],
    },
    {
      title: 'Number of common tangents',
      items: ['Apart', 'Touch outside', 'Cross', 'Touch inside', 'One inside other'],
      rows: [
        { aspect: 'Distance d', values: ['d > r₁ + r₂', 'd = r₁ + r₂', 'r₁ − r₂ < d < r₁ + r₂', 'd = r₁ − r₂', 'd < r₁ − r₂'] },
        { aspect: 'Common tangents', values: ['4', '3', '2', '1', '0'], key: true },
      ],
      reveal: 'Each step closer loses one tangent: 4, 3, 2, 1, 0.',
      whenToUse: [
        'Compare d with the sum of the radii first.',
        'd equals the sum exactly.',
        'd is between the difference and the sum.',
        'd equals the difference exactly.',
        'd is smaller than the difference.',
      ],
    },
  ],
  shortcuts: [
    {
      pattern: 'Distance of a chord from the centre',
      example: 'A chord of length 16 cm is drawn in a circle of radius 10 cm. How far is it from the centre?',
      options: ['6 cm', '8 cm', '4 cm', '5 cm'],
      answer: '6 cm',
      ladder: [
        { name: 'Standard', steps: ['Drop the perpendicular: it bisects the chord, half-chord 8.', 'd² = 10² − 8² = 36.', 'd = 6 cm.'], seconds: 25 },
        { name: 'Shortcut', steps: ['Spot the triplet 6-8-10: d = 6 cm.'], seconds: 5 },
      ],
    },
    {
      pattern: 'Direct common tangent',
      example: 'Two circles of radii 8 cm and 3 cm have centres 13 cm apart. Find the length of the direct common tangent.',
      options: ['10 cm', '12 cm', '4√3 cm', '11 cm'],
      answer: '12 cm',
      ladder: [
        {
          name: 'Standard',
          steps: ['Draw the tangent and both radii to it.', 'Draw a line from the small centre parallel to the tangent.', 'Right triangle with hypotenuse 13 and one leg 8 − 3 = 5.', 'Tangent = √(169 − 25) = 12 cm.'],
          seconds: 60,
        },
        { name: 'Shortcut', steps: ['√(d² − (r₁ − r₂)²) = √(169 − 25) = 12 cm.'], seconds: 12 },
        { name: 'Option elimination', steps: ['5-12-13 triplet: legs 5 and 12.', '4√3 is the transverse tangent, a trap.'], seconds: 6 },
      ],
    },
    {
      pattern: 'Tangent length from an outside point',
      example: 'A point is 17 cm from the centre of a circle of radius 8 cm. Find the length of the tangent from it.',
      options: ['15 cm', '9 cm', '12 cm', '16 cm'],
      answer: '15 cm',
      ladder: [
        { name: 'Standard', steps: ['Tangent ⟂ radius, so a right triangle with hypotenuse 17.', 't² = 289 − 64 = 225.', 't = 15 cm.'], seconds: 25 },
        { name: 'Shortcut', steps: ['8-15-17 triplet: t = 15 cm.'], seconds: 5 },
      ],
    },
  ],
  qa: [
    {
      q: 'Length of a chord at distance d from the centre of a circle of radius r?',
      a: ['2√(r² − d²).', 'The perpendicular from the centre bisects the chord.'],
      tag: 'Asked often',
    },
    {
      q: 'Length of the tangent from a point at distance d from the centre?',
      a: ['√(d² − r²).', 'The tangent meets the radius at 90°.'],
      tag: 'Asked often',
    },
    {
      q: 'Two tangents PA and PB meet at P. How are ∠APB and ∠AOB related?',
      a: ['They add to 180°.', 'OAPB has two right angles at A and B.'],
      tag: 'Shortcut',
    },
    {
      q: 'Angle at the centre vs angle at the circumference on the same arc?',
      a: ['Centre angle = 2 × circumference angle.', 'In a semicircle the centre angle is 180°, so the angle is 90°.'],
    },
    {
      q: 'Are the opposite angles of a cyclic quadrilateral equal?',
      a: ['No, they add to 180°.', 'They are equal only when both are 90°.'],
      tag: 'Trap',
    },
    {
      q: 'Formulas for the direct and transverse common tangents?',
      a: ['Direct: √(d² − (r₁ − r₂)²).', 'Transverse: √(d² − (r₁ + r₂)²).', 'Direct uses minus, transverse uses plus.'],
      tag: 'Trap',
    },
    {
      q: 'How many common tangents do two circles touching externally have?',
      a: ['3: two direct and one at the point of contact.', 'Apart 4, crossing 2, touching inside 1, one inside the other 0.'],
      tag: 'Asked often',
    },
    {
      q: 'Tangent PT and secant PAB from the same point. Rule?',
      a: ['PT² = PA × PB.', 'PB is the whole secant, not AB.'],
      tag: 'Trap',
    },
    {
      q: 'State the alternate segment theorem.',
      a: ['Angle between a tangent and a chord = angle in the alternate segment.', 'The alternate segment is the one on the other side of the chord.'],
    },
    {
      q: 'A circle touches all four sides of ABCD. What is equal?',
      a: ['AB + CD = AD + BC.', 'A rhombus is the only parallelogram that works.'],
    },
  ],
  quiz: [
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'O is the centre of a circle and ∠AOB = 110°. C is a point on the major arc. What is ∠ACB?',
      options: ['110°', '55°', '125°', '70°'],
      answer: 1,
      explain: 'The angle at the circumference is half the angle at the centre: 110 ÷ 2 = 55°.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'AB is a diameter and C is a point on the circle. If ∠CAB = 35°, what is ∠CBA?',
      options: ['55°', '35°', '90°', '45°'],
      answer: 0,
      explain: '∠ACB = 90° (angle in a semicircle), so ∠CBA = 180 − 90 − 35 = 55°.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'A point is 13 cm from the centre of a circle of radius 5 cm. What is the length of the tangent from the point?',
      options: ['8 cm', '10 cm', '12 cm', '18 cm'],
      answer: 2,
      explain: '√(13² − 5²) = √144 = 12 cm.',
      shortcut: '5-12-13 triplet.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'ABCD is a cyclic quadrilateral with ∠A = 75°. What is ∠C?',
      options: ['75°', '105°', '115°', '95°'],
      answer: 1,
      explain: 'Opposite angles of a cyclic quadrilateral add to 180°: 180 − 75 = 105°.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'A chord of length 16 cm is drawn in a circle of radius 10 cm. What is its distance from the centre?',
      options: ['8 cm', '4 cm', '5 cm', '6 cm'],
      answer: 3,
      explain: 'Half-chord = 8. Distance = √(100 − 64) = 6 cm.',
      shortcut: '6-8-10 triplet.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'PA and PB are tangents from P to a circle with centre O. If ∠APB = 50°, what is ∠AOB?',
      options: ['50°', '100°', '130°', '65°'],
      answer: 2,
      explain: '∠OAP = ∠OBP = 90°, so ∠AOB = 360 − 90 − 90 − 50 = 130°.',
      shortcut: '∠APB + ∠AOB = 180°.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'Two circles of radii 8 cm and 3 cm have their centres 13 cm apart. What is the length of the direct common tangent?',
      options: ['10 cm', '4√3 cm', '11 cm', '12 cm'],
      answer: 3,
      explain: '√(13² − (8 − 3)²) = √(169 − 25) = 12 cm.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'Two circles of radii 6 cm and 3 cm have their centres 15 cm apart. What is the length of the transverse common tangent?',
      options: ['12 cm', '6√6 cm', '9 cm', '10 cm'],
      answer: 0,
      explain: '√(15² − (6 + 3)²) = √(225 − 81) = 12 cm.',
      shortcut: '9-12-15 is 3-4-5 × 3. (6√6 is the direct tangent, a trap.)',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'Chords AB and CD of a circle meet at P inside the circle. If AP = 4 cm, PB = 6 cm and CP = 3 cm, what is PD?',
      options: ['4.5 cm', '8 cm', '2 cm', '9 cm'],
      answer: 1,
      explain: 'AP × PB = CP × PD: 24 = 3 × PD, so PD = 8 cm.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'From an outside point P, a tangent PT and a secant PAB are drawn to a circle. If PA = 4 cm and AB = 5 cm, what is PT?',
      options: ['6 cm', '√20 cm', '3 cm', '4.5 cm'],
      answer: 0,
      explain: 'PB = 4 + 5 = 9. PT² = PA × PB = 36, so PT = 6 cm.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'The tangent at A makes an angle of 65° with the chord AB. C is a point on the circle in the alternate segment. What is ∠ACB?',
      options: ['25°', '115°', '65°', '130°'],
      answer: 2,
      explain: 'Alternate segment theorem: the angle in the alternate segment equals the tangent-chord angle, 65°.',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: 'ABCD is a cyclic quadrilateral in which AB is a diameter and ∠BCD = 120°. What is ∠ABD?',
      options: ['60°', '30°', '45°', '40°'],
      answer: 1,
      explain: '∠BAD = 180 − 120 = 60° (opposite angles). ∠ADB = 90° (semicircle). So ∠ABD = 180 − 90 − 60 = 30°.',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: 'Two circles of radii 5 cm and 3 cm have their centres 8 cm apart. How many common tangents do they have?',
      options: ['1', '2', '3', '4'],
      answer: 2,
      explain: 'd = 5 + 3, so the circles touch externally and have 3 common tangents.',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: 'A circle touches all four sides of quadrilateral ABCD. If AB = 6 cm, BC = 7 cm and CD = 4 cm, what is AD?',
      options: ['3 cm', '5 cm', '4 cm', '9 cm'],
      answer: 0,
      explain: 'AB + CD = AD + BC: 6 + 4 = AD + 7, so AD = 3 cm.',
    },
    {
      type: 'truefalse',
      difficulty: 'easy',
      statement: 'The opposite angles of a cyclic quadrilateral are equal.',
      answer: false,
      explain: 'They add to 180°. They are equal only when both are 90°.',
    },
    {
      type: 'truefalse',
      difficulty: 'medium',
      statement: 'Two circles that cross each other at two points have exactly two common tangents.',
      answer: true,
      explain: 'Crossing circles have only the two direct common tangents; no tangent can pass between them.',
    },
  ],
};

export default topic;
