import type { Topic } from '@/content/types';

const topic: Topic = {
  id: 'coordinate-geometry',
  title: 'Coordinate geometry',
  level: 'beginner',
  masteryMinutes: 45,
  reviseMinutes: 15,
  priority: 'low',
  tags: ['distance formula', 'section formula', 'midpoint', 'centroid', 'slope', 'intercepts', 'area of triangle', 'collinear'],
  summary:
    'Six formulas cover the whole chapter: distance, section, midpoint, centroid, slope and area. The line-with-axes triangle is the most asked question.',
  patterns: [
    { name: 'Area of the triangle a line makes with the axes', frequency: 'most', example: 'Find the area of the triangle formed by 4x + 3y = 24 and the axes.' },
    { name: 'Intercepts: where a line cuts the axes', frequency: 'often', example: 'At which point does 2x + 5y = 10 cut the y-axis?' },
    { name: 'Slope, parallel and perpendicular lines', frequency: 'often', example: '2x + ky = 5 is perpendicular to 3x − 6y = 7. Find k.' },
    { name: 'Distance between two points', frequency: 'often', example: 'Find the distance between (3, 4) and (−3, −4).' },
    { name: 'Section formula, midpoint and centroid', frequency: 'often', example: 'In what ratio does the y-axis divide the join of (−4, 5) and (6, −2)?' },
    { name: 'Area of a triangle from vertices and collinearity', frequency: 'rare', example: 'For what k are (2, 3), (4, k) and (6, −3) collinear?' },
  ],
  keyPoints: [
    {
      title: 'Distance formula',
      text: 'The distance between (x₁, y₁) and (x₂, y₂) is Pythagoras on the horizontal and vertical gaps. Distance from the origin to (x, y) is √(x² + y²). Use it to test the type of triangle.',
      formula: 'd = √((x₂ − x₁)² + (y₂ − y₁)²)',
      example: '(3, 4) to (−3, −4): √(36 + 64) = **10**.',
    },
    {
      title: 'Section formula and midpoint',
      text: 'The point dividing the join of A(x₁, y₁) and B(x₂, y₂) internally in the ratio m : n. Cross-multiply: m goes with the far point B. The midpoint is the case m = n.',
      formula: 'x = (mx₂ + nx₁)/(m + n),  y = (my₂ + ny₁)/(m + n)',
      example: '(2, 3) and (8, 9) in 1 : 2: x = (8 + 4)/3 = 4, y = (9 + 6)/3 = 5, so **(4, 5)**.',
    },
    {
      title: 'Ratio in which an axis divides a segment',
      text: 'The x-axis divides the join in the ratio of the sizes of the y-coordinates, |y₁| : |y₂|. The y-axis uses the x-coordinates, |x₁| : |x₂|. The points must lie on opposite sides of that axis.',
      formula: 'x-axis: |y₁| : |y₂|,  y-axis: |x₁| : |x₂|',
      example: 'Join of (2, −3) and (5, 6) meets the x-axis in the ratio 3 : 6 = **1 : 2**.',
    },
    {
      title: 'Centroid',
      text: 'The centroid is where the medians meet. It divides each median 2 : 1 from the vertex. Its coordinates are the averages of the three vertices.',
      formula: 'G = ((x₁ + x₂ + x₃)/3, (y₁ + y₂ + y₃)/3)',
      example: '(1, 2), (4, 6), (7, −2): G = (12/3, 6/3) = **(4, 2)**.',
    },
    {
      title: 'Area of a triangle from its vertices',
      text: 'Take the absolute value. If the area is zero the three points are collinear.',
      formula: 'Area = 1/2 × |x₁(y₂ − y₃) + x₂(y₃ − y₁) + x₃(y₁ − y₂)|',
      example: '(1, 1), (4, 5), (7, 2): 1/2 × |3 + 4 − 28| = **10.5**.',
    },
    {
      title: 'Slope of a line',
      text: 'Slope through two points is rise over run. For ax + by + c = 0 the slope is −a/b. Parallel lines have equal slopes; perpendicular lines have slopes whose product is −1.',
      formula: 'm = (y₂ − y₁)/(x₂ − x₁),  ax + by + c = 0 ⇒ m = −a/b',
      example: '3x − 4y + 7 = 0: m = −3/(−4) = **3/4**.',
    },
    {
      title: 'Intercepts and the triangle with the axes',
      text: 'The line ax + by = c cuts the x-axis at (c/a, 0) and the y-axis at (0, c/b). With the axes it makes a right triangle whose legs are those intercepts. Intercept form: x/p + y/q = 1.',
      formula: 'Area with axes = c²/(2|ab|)',
      example: '3x + 4y = 12: intercepts 4 and 3, area = 144/24 = **6**.',
    },
    {
      title: 'Quadrants and special lines',
      text: 'Signs of (x, y): I (+, +), II (−, +), III (−, −), IV (+, −). x = k is a vertical line, y = k is horizontal. y = x and y = −x are at 45° to the axes. A point on the x-axis has y = 0.',
      example: '(−3, 4) is in quadrant **II**. Lines y = x, y = −x and y = 6 make a triangle of area 36.',
    },
  ],
  comparisons: [
    {
      title: 'Parallel vs perpendicular lines',
      items: ['Parallel lines', 'Perpendicular lines'],
      rows: [
        { aspect: 'Slopes', values: ['m₁ = m₂', 'm₁ × m₂ = −1'], key: true },
        { aspect: 'Line through a point, like ax + by + c = 0', values: ['ax + by + k = 0', 'bx − ay + k = 0'] },
        { aspect: 'Example with 2x + 3y = 6', values: ['2x + 3y = k', '3x − 2y = k'] },
        { aspect: 'a₁/a₂ vs b₁/b₂', values: ['a₁/a₂ = b₁/b₂ (no solution if c differs)', 'a₁a₂ + b₁b₂ = 0'] },
      ],
      reveal: 'Parallel keeps the x and y coefficients; perpendicular swaps them and flips one sign.',
      whenToUse: [
        'The lines never meet, or the pair of equations has no solution.',
        'The lines meet at a right angle.',
      ],
    },
  ],
  shortcuts: [
    {
      pattern: 'Triangle made by a line with the axes',
      example: 'Find the area of the triangle formed by the line 3x + 4y = 12 and the coordinate axes.',
      options: ['6', '12', '7', '24'],
      answer: '6',
      ladder: [
        { name: 'Standard', steps: ['Put y = 0: x = 4. Put x = 0: y = 3.', 'Right triangle with legs 4 and 3.', 'Area = 1/2 × 4 × 3 = 6.'], seconds: 25 },
        { name: 'Shortcut', steps: ['c²/(2ab) = 144/(2 × 3 × 4) = 144/24 = 6.'], seconds: 8 },
        { name: 'Option elimination', steps: ['Legs are c/a and c/b, whole numbers here: 4 and 3.', 'Half their product must be 6.'], seconds: 8 },
      ],
    },
    {
      pattern: 'Ratio in which an axis cuts a segment',
      example: 'In what ratio does the x-axis divide the line segment joining (2, −3) and (5, 6)?',
      options: ['1 : 2', '2 : 1', '3 : 5', '2 : 3'],
      answer: '1 : 2',
      ladder: [
        { name: 'Standard', steps: ['Let the ratio be m : n. On the x-axis y = 0.', '(6m − 3n)/(m + n) = 0, so 6m = 3n.', 'm : n = 1 : 2.'], seconds: 30 },
        { name: 'Shortcut', steps: ['x-axis: ratio = |y₁| : |y₂| = 3 : 6 = 1 : 2.'], seconds: 5 },
      ],
    },
    {
      pattern: 'Missing coordinate from a distance',
      example: 'The distance between (k, 3) and (5, 7) is 5 units. Which of these is a value of k?',
      options: ['8', '6', '4', '9'],
      answer: '8',
      ladder: [
        { name: 'Standard', steps: ['(k − 5)² + (3 − 7)² = 25.', '(k − 5)² = 9, so k − 5 = ±3.', 'k = 8 or 2.'], seconds: 35 },
        { name: 'Triplet', steps: ['Vertical gap is 4 and distance is 5: the 3-4-5 triplet.', 'Horizontal gap must be 3, so k = 5 ± 3 = 8 or 2.'], seconds: 10 },
        { name: 'Put values', steps: ['k = 8: gaps 3 and 4 give 5. It fits.'], seconds: 10 },
      ],
    },
  ],
  qa: [
    {
      q: 'Where does the line ax + by = c cut the axes?',
      a: ['x-axis at (c/a, 0): put y = 0.', 'y-axis at (0, c/b): put x = 0.'],
      tag: 'Asked often',
    },
    {
      q: 'Quick formula for the area a line makes with the axes?',
      a: ['For ax + by = c: area = c²/(2|ab|).', '4x + 3y = 24: 576/24 = 24.'],
      tag: 'Shortcut',
    },
    {
      q: 'Slope of the line ax + by + c = 0?',
      a: ['−a/b.', 'Write it as y = −(a/b)x − c/b and read the x coefficient.'],
      tag: 'Asked often',
    },
    {
      q: 'In the section formula, which ratio part goes with which point?',
      a: ['Cross over: m multiplies the second point, n the first.', 'x = (mx₂ + nx₁)/(m + n).'],
      tag: 'Trap',
    },
    {
      q: 'How do you test if three points are collinear?',
      a: ['Area of the triangle they form is 0.', 'Or: slope AB = slope BC.'],
    },
    {
      q: 'Centroid of a triangle with given vertices?',
      a: ['Average the x values and the y values.', 'It divides each median 2 : 1 from the vertex.'],
    },
    {
      q: 'Condition for two lines to be perpendicular?',
      a: ['Product of slopes = −1.', 'For a₁x + b₁y + c₁ = 0 and a₂x + b₂y + c₂ = 0: a₁a₂ + b₁b₂ = 0.'],
      tag: 'Asked often',
    },
    {
      q: 'When do two linear equations have no solution?',
      a: ['When the lines are parallel and distinct.', 'a₁/a₂ = b₁/b₂ ≠ c₁/c₂.'],
      tag: 'Trap',
    },
    {
      q: 'Signs of coordinates in each quadrant?',
      a: ['I (+, +), II (−, +), III (−, −), IV (+, −).', 'Points on an axis lie in no quadrant.'],
    },
    {
      q: 'Distance of the point (x, y) from each axis?',
      a: ['From the x-axis: |y|. From the y-axis: |x|.', 'From the origin: √(x² + y²).'],
      tag: 'Trap',
    },
  ],
  quiz: [
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'What is the distance between the points (3, 4) and (−3, −4)?',
      options: ['10', '5', '14', '8'],
      answer: 0,
      explain: '√(6² + 8²) = √100 = 10.',
      shortcut: 'Each point is 5 from the origin and they are opposite, so 2 × 5 = 10.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'What is the midpoint of the segment joining (−2, 6) and (8, −4)?',
      options: ['(5, 1)', '(3, 1)', '(3, 5)', '(6, 2)'],
      answer: 1,
      explain: '((−2 + 8)/2, (6 − 4)/2) = (3, 1).',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'What is the slope of the line 3x − 4y + 7 = 0?',
      options: ['−3/4', '4/3', '3/4', '−4/3'],
      answer: 2,
      explain: 'Slope = −a/b = −3/(−4) = 3/4.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'At which point does the line 2x + 5y = 10 cut the y-axis?',
      options: ['(0, 5)', '(5, 0)', '(2, 0)', '(0, 2)'],
      answer: 3,
      explain: 'Put x = 0: 5y = 10, so y = 2. The point is (0, 2).',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'What is the area of the triangle formed by the line 4x + 3y = 24 and the coordinate axes?',
      options: ['48', '24', '12', '36'],
      answer: 1,
      explain: 'Intercepts are 6 (x-axis) and 8 (y-axis). Area = 1/2 × 6 × 8 = 24.',
      shortcut: 'c²/(2ab) = 576/24 = 24.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'Find the point that divides the segment joining (2, 3) and (8, 9) internally in the ratio 1 : 2.',
      options: ['(4, 5)', '(6, 7)', '(5, 6)', '(4, 6)'],
      answer: 0,
      explain: 'x = (1 × 8 + 2 × 2)/3 = 4, y = (1 × 9 + 2 × 3)/3 = 5.',
      shortcut: 'The point is 1/3 of the way from (2, 3): add 1/3 of (6, 6), giving (4, 5).',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'What is the centroid of the triangle with vertices (1, 2), (4, 6) and (7, −2)?',
      options: ['(4, 3)', '(4, 2)', '(3, 2)', '(6, 3)'],
      answer: 1,
      explain: '((1 + 4 + 7)/3, (2 + 6 − 2)/3) = (4, 2).',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'What is the area of the triangle with vertices (1, 1), (4, 5) and (7, 2)?',
      options: ['21', '9.5', '12', '10.5'],
      answer: 3,
      explain: '1/2 × |1(5 − 2) + 4(2 − 1) + 7(1 − 5)| = 1/2 × |3 + 4 − 28| = 21/2 = 10.5.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'For what value of k are the points (2, 3), (4, k) and (6, −3) collinear?',
      options: ['1', '−1', '0', '3'],
      answer: 2,
      explain: 'x = 4 is midway between 2 and 6, so (4, k) must be the midpoint: k = (3 − 3)/2 = 0.',
      shortcut: 'Equal x-steps mean equal y-steps on a straight line.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'In what ratio does the y-axis divide the segment joining (−4, 5) and (6, −2)?',
      options: ['3 : 2', '2 : 3', '4 : 5', '5 : 4'],
      answer: 1,
      explain: 'On the y-axis x = 0: (6m − 4n)/(m + n) = 0, so m : n = 4 : 6 = 2 : 3.',
      shortcut: 'y-axis ratio = |x₁| : |x₂| = 4 : 6 = 2 : 3.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'The lines 2x + ky = 5 and 3x − 6y = 7 are perpendicular. What is k?',
      options: ['4', '−1', '−4', '1'],
      answer: 3,
      explain: 'Slopes are −2/k and 3/6 = 1/2. Product = −1/k = −1, so k = 1.',
      shortcut: 'a₁a₂ + b₁b₂ = 0: 6 − 6k = 0, so k = 1.',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: 'A(−1, 3), B(1, −1) and C(5, 1) are the vertices of a triangle. What is the length of the median through A?',
      options: ['√26', '4', '5', '√29'],
      answer: 2,
      explain: 'Midpoint of BC = (3, 0). Distance from A = √(4² + 3²) = 5.',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: 'The points (1, 1), (−1, −1) and (−√3, √3) form which type of triangle?',
      options: ['Isosceles right-angled', 'Equilateral', 'Scalene', 'Right-angled scalene'],
      answer: 1,
      explain: 'Each side squared is 8: (2² + 2²), (1 + √3)² + (1 − √3)² = 8, and (√3 − 1)² + (√3 + 1)² = 8. All sides √8.',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: 'What is the area of the triangle formed by the lines y = x, y = −x and y = 6?',
      options: ['18', '72', '36', '24'],
      answer: 2,
      explain: 'Vertices (0, 0), (6, 6) and (−6, 6). Base 12 along y = 6, height 6. Area = 1/2 × 12 × 6 = 36.',
      shortcut: 'For y = x, y = −x and y = k the area is k².',
    },
    {
      type: 'truefalse',
      difficulty: 'easy',
      statement: 'The point (−3, 4) lies in the second quadrant.',
      answer: true,
      explain: 'x negative, y positive: quadrant II.',
    },
    {
      type: 'truefalse',
      difficulty: 'medium',
      statement: 'The lines 3x + 2y = 5 and 6x + 4y = 9 meet at exactly one point.',
      answer: false,
      explain: '3/6 = 2/4 but 5/9 is different, so the lines are parallel and never meet.',
    },
  ],
};

export default topic;
