import type { Topic } from '@/content/types';

const topic: Topic = {
  id: 'hcf-lcm',
  title: 'HCF and LCM',
  level: 'beginner',
  masteryMinutes: 60,
  reviseMinutes: 20,
  priority: 'medium',
  weightage: { tier1: 0.5, tier2: 1 },
  tags: ['HCF', 'LCM', 'prime factorisation', 'remainder', 'bells', 'tiles', 'fractions'],
  summary:
    'HCF is the biggest number that fits into all of them; LCM is the smallest number they all fit into. Read the question for "largest" or "smallest", then add the remainder twist.',
  patterns: [
    { name: 'Smallest number leaving a given remainder', frequency: 'most', example: 'Smallest number which divided by 12, 15 and 18 leaves 5 each time?' },
    { name: 'HCF × LCM = product of two numbers', frequency: 'most', example: 'HCF 12, LCM 360, one number 72. Find the other.' },
    { name: 'Largest number leaving given remainders', frequency: 'often', example: 'Largest number dividing 1657 and 2037 leaving 6 and 5.' },
    { name: 'Bells, lights and runners together again', frequency: 'often', example: 'Bells toll every 6, 8 and 12 minutes. When together again?' },
    { name: 'Numbers in a ratio with given HCF or LCM', frequency: 'often', example: 'Two numbers are 3 : 4 and their LCM is 180. Find the HCF.' },
    { name: 'HCF and LCM of fractions', frequency: 'rare', example: 'Find the HCF of 2/3, 4/9 and 8/15.' },
    { name: 'Tiles, rows and equal groups', frequency: 'rare', example: 'Fewest square tiles for a 6.24 m by 4.32 m floor?' },
  ],
  keyPoints: [
    {
      title: 'Prime factorisation method',
      text: 'Break each number into primes. HCF takes the **lowest** power of each **common** prime. LCM takes the **highest** power of **every** prime that appears.',
      formula: 'HCF = lowest common powers; LCM = highest powers',
      example: '72 = 2³ × 3², 120 = 2³ × 3 × 5. HCF = 2³ × 3 = **24**, LCM = 2³ × 3² × 5 = **360**.',
    },
    {
      title: 'Product rule (two numbers only)',
      text: 'For any two numbers, HCF × LCM equals their product. It does not hold for three or more numbers.',
      formula: 'HCF × LCM = a × b',
      example: 'HCF 12, LCM 360, one number 72: other = 12 × 360 ÷ 72 = **60**.',
    },
    {
      title: 'Numbers as H × co-primes',
      text: 'If the HCF is H, the numbers are Ha and Hb with a and b co-prime. Their LCM is Hab. Numbers in the ratio a : b with HCF H follow the same rule.',
      formula: 'a = Hx, b = Hy (x, y co-prime) → LCM = Hxy',
      example: 'Ratio 3 : 4, LCM 180: H × 12 = 180, so HCF = **15** and the numbers are 45 and 60.',
    },
    {
      title: 'Smallest number with a remainder',
      text: 'Same remainder r for every divisor: LCM + r (or any multiple of the LCM plus r). If each remainder is the same amount k short of its divisor, the number is LCM − k.',
      formula: 'N = LCM × m + r, or N = LCM × m − k',
      example: '÷ 12, 15, 18 leaves 5: 180 + 5 = **185**. ÷ 5, 6, 7 leaves 3, 4, 5 (each 2 short): 210 − 2 = **208**.',
    },
    {
      title: 'Largest number with a remainder',
      text: 'Given remainders: subtract each remainder from its number, then take the HCF. Same but unknown remainder: take the HCF of the differences between the numbers.',
      formula: 'HCF(a − r₁, b − r₂) or HCF(b − a, c − b)',
      example: '1657 and 2037 leaving 6 and 5: HCF(1651, 2032) = **127**. 91, 251, 311 with the same remainder: HCF(160, 60) = **20**.',
    },
    {
      title: 'HCF and LCM of fractions',
      text: 'Write the fractions in lowest terms first. Then HCF works on numerators and LCM on denominators, and the other way round.',
      formula: 'HCF = (HCF of numerators)/(LCM of denominators); LCM = (LCM of numerators)/(HCF of denominators)',
      example: '2/3, 4/9, 8/15: HCF = 2/45, LCM = 8/3.',
    },
    {
      title: 'Word problems: which one to use',
      text: 'Bells, lights, runners on a track and "together again" need the LCM. Largest tile, longest rod, biggest equal group need the HCF. The fewest square tiles for a floor = area ÷ (HCF side)².',
      example: 'Floor 624 cm × 432 cm: HCF = 48 cm, tiles = 13 × 9 = **117**.',
    },
  ],
  comparisons: [
    {
      title: 'HCF vs LCM',
      items: ['HCF', 'LCM'],
      rows: [
        { aspect: 'Meaning', values: ['Largest number that divides all', 'Smallest number all divide into'] },
        { aspect: 'From prime factors', values: ['Lowest power of common primes', 'Highest power of every prime'] },
        { aspect: 'Words in the question', values: ['largest, greatest, maximum, equal groups, biggest tile', 'smallest, least, together again, first time'], key: true },
        { aspect: 'Size', values: ['At most the smallest number', 'At least the largest number'] },
        { aspect: 'Fractions', values: ['(HCF of tops)/(LCM of bottoms)', '(LCM of tops)/(HCF of bottoms)'] },
      ],
      reveal: 'HCF always divides LCM. "Largest" points to HCF, "smallest" points to LCM, and the remainder is added or subtracted afterwards.',
      whenToUse: ['Cutting, filling or dividing into the biggest equal parts.', 'Events repeating on different cycles that must coincide.'],
    },
    {
      title: 'Remainder patterns',
      items: ['Same remainder r', 'Each remainder k short', 'Largest divisor, same unknown remainder'],
      rows: [
        { aspect: 'Answer', values: ['LCM × m + r', 'LCM × m − k', 'HCF of the differences'], key: true },
        { aspect: 'Example', values: ['÷ 12, 15, 18 leaves 5 → 185', '÷ 5, 6, 7 leaves 3, 4, 5 → 208', '91, 251, 311 → 20'] },
        { aspect: 'Uses', values: ['LCM', 'LCM', 'HCF'] },
      ],
      reveal: 'Smallest number questions use the LCM; largest divisor questions use the HCF.',
      whenToUse: [
        'All remainders are equal.',
        'Divisor − remainder is the same for every divisor.',
        'The question asks for the divisor, not the number.',
      ],
    },
  ],
  shortcuts: [
    {
      pattern: 'Smallest number leaving the same remainder',
      example: 'Find the smallest number which, when divided by 12, 15 and 18, leaves remainder 5 in each case.',
      options: ['180', '185', '175', '365'],
      answer: '185',
      ladder: [
        { name: 'Standard', steps: ['12 = 2² × 3, 15 = 3 × 5, 18 = 2 × 3².', 'LCM = 2² × 3² × 5 = 180.', 'Add the remainder: 185.'], seconds: 40 },
        { name: 'Shortcut', steps: ['LCM of 12 and 15 is 60; LCM of 60 and 18 is 180.', '180 + 5 = 185.'], seconds: 15 },
        {
          name: 'Option elimination',
          steps: ['Answer − 5 must be divisible by 12, 15 and 18.', '180 − 5 = 175 and 175 − 5 = 170 fail.', '185 − 5 = 180 and 365 − 5 = 360 pass. Smallest: 185.'],
          seconds: 15,
        },
      ],
    },
    {
      pattern: 'Other number from HCF and LCM',
      example: 'The HCF and LCM of two numbers are 12 and 360. One number is 72. Find the other.',
      options: ['48', '60', '72', '90'],
      answer: '60',
      ladder: [
        { name: 'Standard', steps: ['72 = 12 × 6. Other = 12 × b with b co-prime to 6.', 'LCM = 12 × 6 × b = 360, so b = 5.', 'Other = 60.'], seconds: 40 },
        { name: 'Shortcut', steps: ['Other = HCF × LCM ÷ given = 12 × 360 ÷ 72 = 60.'], seconds: 10 },
        {
          name: 'Option elimination',
          steps: ['It must be a multiple of 12 and a factor of 360.', '90 is not a multiple of 12; 48 does not divide 360.', '72 would make the LCM 72. Only 60 is left.'],
          seconds: 15,
        },
      ],
    },
    {
      pattern: 'Largest divisor leaving different remainders',
      example: 'Find the largest number that divides 1657 and 2037 leaving remainders 6 and 5.',
      options: ['123', '127', '235', '305'],
      answer: '127',
      ladder: [
        { name: 'Standard', steps: ['1657 − 6 = 1651, 2037 − 5 = 2032.', 'Euclid: 2032 − 1651 = 381; 1651 = 4 × 381 + 127; 381 = 3 × 127.', 'HCF = 127.'], seconds: 60 },
        { name: 'Shortcut', steps: ['The HCF divides 2032 − 1651 = 381 = 3 × 127.', '1651 ÷ 127 = 13 exactly, so HCF = 127.'], seconds: 25 },
        { name: 'Option elimination', steps: ['The answer must divide 381.', 'Only 127 does.'], seconds: 10 },
      ],
    },
  ],
  qa: [
    {
      q: 'Does HCF × LCM = product hold for three numbers?',
      a: ['No, only for two numbers.', '2, 4, 8: HCF 2 × LCM 8 = 16, but the product is 64.'],
      tag: 'Trap',
    },
    {
      q: 'Smallest number that leaves remainder r with each of several divisors?',
      a: ['LCM of the divisors + r.', 'The next ones are 2 × LCM + r, 3 × LCM + r, and so on.'],
      tag: 'Asked often',
    },
    {
      q: 'Divisors 5, 6, 7 leave remainders 3, 4, 5. What is the trick?',
      a: ['Each remainder is 2 short of its divisor.', 'Number = LCM − 2 = 210 − 2 = 208.'],
      tag: 'Shortcut',
    },
    {
      q: 'Largest number that leaves the same remainder when dividing 91, 251 and 311?',
      a: ['HCF of the differences: 160 and 60.', 'HCF = 20. Each leaves remainder 11.'],
      tag: 'Asked often',
    },
    {
      q: 'HCF of fractions?',
      a: ['HCF of numerators over LCM of denominators.', 'Reduce each fraction to lowest terms first.'],
    },
    {
      q: 'LCM of fractions?',
      a: ['LCM of numerators over HCF of denominators.', '3/4, 5/6, 7/8: 105/2.'],
    },
    {
      q: 'Two numbers are in the ratio a : b and their HCF is H. What is their LCM?',
      a: ['H × a × b, when a and b are co-prime.', 'Ratio 3 : 4, HCF 5: LCM = 60.'],
      tag: 'Shortcut',
    },
    {
      q: 'What is the HCF of two co-prime numbers? Their LCM?',
      a: ['HCF = 1.', 'LCM = their product.'],
    },
    {
      q: 'Bells toll every 6, 8 and 12 minutes from 9:00 am. When do they next toll together?',
      a: ['LCM(6, 8, 12) = 24 minutes.', 'At 9:24 am.'],
      tag: 'Asked often',
    },
    {
      q: 'Can the HCF of two numbers be 12 and their LCM be 250?',
      a: ['No. The HCF always divides the LCM.', '250 ÷ 12 is not a whole number.'],
      tag: 'Trap',
    },
  ],
  quiz: [
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'What is the HCF of 72 and 120?',
      options: ['12', '24', '36', '8'],
      answer: 1,
      explain: '72 = 2³ × 3², 120 = 2³ × 3 × 5. Common lowest powers: 2³ × 3 = 24.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'The HCF and LCM of two numbers are 12 and 360. If one number is 72, what is the other?',
      options: ['48', '90', '72', '60'],
      answer: 3,
      explain: 'Other = 12 × 360 ÷ 72 = 60.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'Three bells toll at intervals of 6, 8 and 12 minutes. They toll together at 9:00 am. When will they next toll together?',
      options: ['9:24 am', '9:48 am', '9:12 am', '9:36 am'],
      answer: 0,
      explain: 'LCM(6, 8, 12) = 24 minutes, so at 9:24 am.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'Two numbers are in the ratio 3 : 4 and their LCM is 180. What is their HCF?',
      options: ['12', '20', '15', '60'],
      answer: 2,
      explain: 'Numbers 3H and 4H, LCM = 12H = 180, so H = 15. The numbers are 45 and 60.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'What is the smallest number which, when divided by 12, 15 and 18, leaves remainder 5 in each case?',
      options: ['175', '185', '365', '180'],
      answer: 1,
      explain: 'LCM(12, 15, 18) = 180. Add the remainder: 185.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'What is the largest number that divides 1657 and 2037 leaving remainders 6 and 5 respectively?',
      options: ['123', '235', '127', '305'],
      answer: 2,
      explain: 'HCF(1657 − 6, 2037 − 5) = HCF(1651, 2032) = 127.',
      shortcut: 'The answer divides 2032 − 1651 = 381 = 3 × 127. Only 127 among the options divides it.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'What is the HCF of 2/3, 4/9 and 8/15?',
      options: ['8/3', '2/45', '2/15', '1/45'],
      answer: 1,
      explain: 'HCF of numerators (2, 4, 8) = 2. LCM of denominators (3, 9, 15) = 45. HCF = 2/45.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'What is the LCM of 3/4, 5/6 and 7/8?',
      options: ['105/2', '105/24', '1/24', '35/2'],
      answer: 0,
      explain: 'LCM of numerators (3, 5, 7) = 105. HCF of denominators (4, 6, 8) = 2. LCM = 105/2.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'Find the smallest number which, when divided by 5, 6 and 7, leaves remainders 3, 4 and 5 respectively.',
      options: ['203', '213', '198', '208'],
      answer: 3,
      explain: 'Each remainder is 2 less than its divisor. LCM(5, 6, 7) = 210, so the number is 210 − 2 = 208.',
      shortcut: 'Check: 208 ÷ 5 leaves 3, ÷ 6 leaves 4, ÷ 7 leaves 5.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'What is the largest number that divides 91, 251 and 311 leaving the same remainder in each case?',
      options: ['10', '20', '30', '40'],
      answer: 1,
      explain: 'Differences: 251 − 91 = 160, 311 − 251 = 60. HCF(160, 60) = 20. Each leaves 11.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'A room is 6 m 24 cm long and 4 m 32 cm wide. What is the least number of equal square tiles that will cover the floor exactly?',
      options: ['117', '96', '124', '108'],
      answer: 0,
      explain: 'HCF(624, 432) = 48 cm is the largest tile side. Tiles = (624 ÷ 48) × (432 ÷ 48) = 13 × 9 = 117.',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: 'The sum of two numbers is 96 and their HCF is 12. How many such pairs of numbers are there?',
      options: ['1', '3', '4', '2'],
      answer: 3,
      explain: 'Numbers 12a and 12b with a + b = 8 and a, b co-prime: (1, 7) and (3, 5). So 2 pairs: (12, 84) and (36, 60).',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: 'What is the greatest 4-digit number that is exactly divisible by 12, 15, 18 and 27?',
      options: ['9720', '9900', '9180', '9990'],
      answer: 0,
      explain: 'LCM(12, 15, 18, 27) = 540. 9999 ÷ 540 = 18 remainder 279, so the number is 540 × 18 = 9720.',
      shortcut: 'Greatest n-digit multiple = largest n-digit number minus the remainder: 9999 − 279 = 9720.',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: 'What is the smallest 5-digit number which, when divided by 12, 15 and 18, leaves remainder 5 in each case?',
      options: ['10,005', '10,080', '10,085', '10,185'],
      answer: 2,
      explain: 'Numbers are 180k + 5. The first one at or above 10,000 is 180 × 56 + 5 = 10,085.',
    },
    {
      type: 'truefalse',
      difficulty: 'easy',
      statement: 'For any three numbers, HCF × LCM equals the product of the numbers.',
      answer: false,
      explain: 'The rule is for two numbers only. For 2, 4, 8: 2 × 8 = 16, but the product is 64.',
    },
    {
      type: 'truefalse',
      difficulty: 'medium',
      statement: 'The HCF of two numbers always divides their LCM.',
      answer: true,
      explain: 'The HCF divides each number, and each number divides the LCM.',
    },
  ],
};

export default topic;
