import type { Topic } from '@/content/types';

const topic: Topic = {
  id: 'heights-distances',
  title: 'Heights and distances',
  level: 'beginner',
  masteryMinutes: 60,
  reviseMinutes: 20,
  priority: 'medium',
  tags: ['angle of elevation', 'angle of depression', 'tower', 'shadow', '30-60-90', '45-45-90', 'two observers'],
  summary:
    'Almost every question uses 30°, 45° or 60°, so it is a right-triangle ratio problem. Learn the side ratios 1 : √3 : 2 and 1 : 1 : √2 and a few ready formulas.',
  patterns: [
    { name: 'Observer walks toward the tower (two angles, same side)', frequency: 'most', example: 'Angle changes from 30° to 60° after walking 40 m toward a tower. Height?' },
    { name: 'Single angle: find height or distance', frequency: 'most', example: 'The top of a tower 50√3 m high is seen at 60°. How far away is the observer?' },
    { name: 'Angle of depression from a cliff, building or plane', frequency: 'often', example: 'From a 75 m cliff a boat is seen at a depression of 30°. Distance of the boat?' },
    { name: 'Two buildings: elevation and depression from one top', frequency: 'often', example: 'From a 60 m building the top and foot of a tower are at depressions 30° and 60°. Tower height?' },
    { name: 'Shadow length and the sun\'s altitude', frequency: 'often', example: 'A shadow is 60 m longer at 30° than at 60°. Height of the tower?' },
    { name: 'Observers on opposite sides of a tower', frequency: 'often', example: 'A 100 m tower is seen at 30° and 45° from two sides. Distance between observers?' },
    { name: 'Complementary angles; flagstaff on a building; ladders', frequency: 'rare', example: 'Angles from 9 m and 16 m are complementary. Height of the tower?' },
  ],
  keyPoints: [
    {
      title: 'Elevation and depression',
      text: 'Elevation is measured up from the horizontal, depression down from the horizontal. The angle of depression from A to B equals the angle of elevation from B to A (alternate angles). Put the depression angle at the bottom of your figure.',
      example: 'Depression 30° from a cliff top to a boat = elevation 30° from the boat to the cliff top.',
    },
    {
      title: 'Values you use every time',
      text: 'tan 30° = 1/√3, tan 45° = 1, tan 60° = √3. sin 30° = cos 60° = 1/2, sin 60° = cos 30° = √3/2. Use √3 ≈ 1.732 when options are decimals.',
      formula: 'tan θ = height/(horizontal distance)',
      example: 'Tower 50√3 at 60°: distance = 50√3/√3 = **50 m**.',
    },
    {
      title: '30-60-90 and 45-45-90 triangles',
      text: 'Sides opposite 30°, 60°, 90° are in the ratio 1 : √3 : 2. In a 45-45-90 triangle the legs are equal and the hypotenuse is leg × √2. No trig needed once you know these.',
      formula: '1 : √3 : 2  and  1 : 1 : √2',
      example: 'Kite string 100 m at 30°: height = half the string = **50 m**.',
    },
    {
      title: 'Same side: observer moves distance d toward the tower',
      text: 'Angles α (near, larger) and β (far, smaller). The distance walked is the difference of the two ground distances.',
      formula: 'h = d/(cot β − cot α)',
      example: '30° → 60°, d = 40: h = 40/(√3 − 1/√3) = 40 × √3/2 = **20√3 m**.',
    },
    {
      title: '30° and 60° shortcut',
      text: 'For 30° then 60°: h = √3/2 × d, and the near point is d/2 from the foot. The far distance is 3 times the near one. For 30° then 45°: h = d/(√3 − 1) = d(√3 + 1)/2.',
      formula: '30° and 60°: h = √3/2 × d;  30° and 45°: h = (√3 + 1)/2 × d',
      example: '30° → 45° after 100 m: h = 50(√3 + 1) ≈ **136.6 m**.',
    },
    {
      title: 'Opposite sides of the tower',
      text: 'Two observers on either side see the top at α and β. The distance between them is the sum of the two ground distances.',
      formula: 'd = h(cot α + cot β),  h = d/(cot α + cot β)',
      example: 'h = 100, angles 30° and 45°: d = 100(√3 + 1) ≈ **273.2 m**.',
    },
    {
      title: 'From the top of a building',
      text: 'Observer at height H. The depression to the foot of a tower gives the gap x = H cot(depression). Then use that x for the second angle: tower height = H ± x tan(second angle).',
      example: '60 m building, depressions 30° (top) and 60° (foot): x = 20√3, drop = 20√3 × 1/√3 = 20, tower = **40 m**.',
    },
    {
      title: 'Complementary angles and shadows',
      text: 'If the elevations from distances a and b (same line, same side) add to 90°, then h = √(ab). The shadow of a height h at sun altitude θ is h cot θ; lower sun means a longer shadow.',
      formula: 'h = √(ab)',
      example: 'From 4 m and 9 m: h = √36 = **6 m**.',
    },
  ],
  comparisons: [
    {
      title: '30-60-90 vs 45-45-90 triangle',
      items: ['30-60-90 triangle', '45-45-90 triangle'],
      rows: [
        { aspect: 'Side ratio', values: ['1 : √3 : 2 (opposite 30°, 60°, 90°)', '1 : 1 : √2'], key: true },
        { aspect: 'tan values', values: ['tan 30° = 1/√3, tan 60° = √3', 'tan 45° = 1'] },
        { aspect: 'Height h, ground distance', values: ['h√3 at 30°, h/√3 at 60°', 'Equal to h'] },
        { aspect: 'Hypotenuse (string, ladder)', values: ['2h at 30°, 2h/√3 at 60°', 'h√2'] },
      ],
      reveal: 'At 45° height equals distance. At 30° the distance is √3 times the height; at 60° the height is √3 times the distance.',
      whenToUse: ['Angles 30° or 60°: answers usually carry √3.', 'Angle 45°: height and distance are equal; answers carry √2 only with a hypotenuse.'],
    },
    {
      title: 'Same side vs opposite sides',
      items: ['Same side (observer walks closer)', 'Opposite sides of the tower'],
      rows: [
        { aspect: 'Given distance d is', values: ['Difference of ground distances', 'Sum of ground distances'], key: true },
        { aspect: 'Formula', values: ['h = d/(cot β − cot α)', 'h = d/(cot α + cot β)'] },
        { aspect: '30° and 60°, d = 100 m', values: ['h = 50√3 ≈ 86.6 m', 'h = 25√3 ≈ 43.3 m'] },
      ],
      reveal: 'Draw the figure: if both points are on one side, subtract; if the tower is between them, add.',
      whenToUse: ['"Walks towards", "moves closer", "shadow becomes longer by".', '"On either side", "on opposite sides", "two ships on both sides of a lighthouse".'],
    },
  ],
  shortcuts: [
    {
      pattern: 'Angle changes from 30° to 60° as you walk closer',
      example: 'The angle of elevation of the top of a tower changes from 30° to 60° as a man walks 60 m toward it. What is the height of the tower?',
      options: ['30√3 m', '60√3 m', '20√3 m', '30 m'],
      answer: '30√3 m',
      ladder: [
        {
          name: 'Standard',
          steps: ['Let height h, near distance x.', 'tan 60° = h/x, so x = h/√3.', 'tan 30° = h/(x + 60), so x + 60 = h√3.', 'h√3 − h/√3 = 60, so 2h/√3 = 60 and h = 30√3.'],
          seconds: 60,
        },
        { name: 'Shortcut', steps: ['For 30° and 60°: h = √3/2 × d = √3/2 × 60 = 30√3.'], seconds: 8 },
        { name: 'Ratio', steps: ['Far distance is 3 times the near one, so 60 m is 2 parts: near = 30 m.', 'h = 30 × tan 60° = 30√3.'], seconds: 15 },
      ],
    },
    {
      pattern: 'Complementary angles of elevation',
      example: 'The angles of elevation of the top of a tower from two points 4 m and 9 m from its base, on the same line, are complementary. Find the height.',
      options: ['6 m', '6.5 m', '5 m', '13 m'],
      answer: '6 m',
      ladder: [
        { name: 'Standard', steps: ['tan θ = h/4 and tan(90° − θ) = cot θ = h/9.', 'tan θ × cot θ = 1, so h²/36 = 1.', 'h = 6 m.'], seconds: 40 },
        { name: 'Shortcut', steps: ['h = √(ab) = √(4 × 9) = 6 m.'], seconds: 5 },
        { name: 'Option elimination', steps: ['The height is the geometric mean, so it lies between 4 and 9 but below their average 6.5.', 'Only 6 m fits.'], seconds: 8 },
      ],
    },
    {
      pattern: 'Top of a building: elevation to one top, depression to its foot',
      example: 'From the top of a 20 m building, the angle of elevation of the top of a tower is 60° and the angle of depression of its foot is 45°. What is the height of the tower?',
      options: ['20(1 + √3) m', '20√3 m', '40 m', '20(√3 − 1) m'],
      answer: '20(1 + √3) m',
      ladder: [
        { name: 'Standard', steps: ['Depression 45° to the foot: gap x = 20 × cot 45° = 20.', 'Rise above the building: 20 × tan 60° = 20√3.', 'Tower = 20 + 20√3 = 20(1 + √3).'], seconds: 40 },
        { name: 'Shortcut', steps: ['Tower = H(1 + tan α ÷ tan β) = 20(1 + √3/1).'], seconds: 12 },
        { name: 'Option elimination', steps: ['The tower is taller than the building (elevation seen) and more than 20 + 20 = 40.', 'Only 20(1 + √3) ≈ 54.6 m is above 40.'], seconds: 8 },
      ],
    },
  ],
  qa: [
    {
      q: 'Is the angle of depression measured from the vertical?',
      a: ['No, from the horizontal line at the observer\'s eye.', 'It equals the angle of elevation from the other point.'],
      tag: 'Trap',
    },
    {
      q: 'Side ratio of a 30-60-90 triangle?',
      a: ['1 : √3 : 2, opposite 30°, 60° and 90°.', 'The side opposite 30° is half the hypotenuse.'],
      tag: 'Asked often',
    },
    {
      q: 'Angle changes 30° → 60° after walking d. Height?',
      a: ['h = √3/2 × d.', 'The near point is d/2 from the foot.'],
      tag: 'Shortcut',
    },
    {
      q: 'Angle changes 30° → 45° after walking d. Height?',
      a: ['h = d/(√3 − 1) = d(√3 + 1)/2.', 'd = 100 gives about 136.6 m.'],
      tag: 'Shortcut',
    },
    {
      q: 'Angles from distances a and b are complementary. Height?',
      a: ['h = √(ab).', 'From 9 m and 16 m: h = 12 m.'],
      tag: 'Asked often',
    },
    {
      q: 'Sun\'s altitude falls. What happens to a shadow?',
      a: ['It gets longer: shadow = h cot θ.', 'At 45° the shadow equals the height.'],
      tag: 'Trap',
    },
    {
      q: 'Shadow at altitude 30° vs 60°: how much longer?',
      a: ['h√3 − h/√3 = 2h/√3.', 'So h = √3/2 × (difference).'],
    },
    {
      q: 'Observers on opposite sides: add or subtract distances?',
      a: ['Add: d = h(cot α + cot β).', 'Same side: subtract.'],
      tag: 'Trap',
    },
    {
      q: 'Car approaching a tower: depression 30° → 60° in t minutes. Time left to reach the foot?',
      a: ['Far distance is 3 times the near one, so 2 parts take t minutes.', 'The last 1 part takes t/2 minutes.'],
      tag: 'Asked often',
    },
    {
      q: 'Ladder of length L makes angle θ with the ground. Height reached on the wall?',
      a: ['L sin θ. Foot is L cos θ from the wall.', 'At 60° the foot is L/2 from the wall.'],
    },
  ],
  quiz: [
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'A ladder makes an angle of 60° with the ground and its foot is 5 m from the wall. How long is the ladder?',
      options: ['10 m', '5√3 m', '5√2 m', '8 m'],
      answer: 0,
      explain: 'cos 60° = 5/L = 1/2, so L = 10 m.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'The angle of elevation of the top of a tower 50√3 m high is 60°. How far is the observer from the foot of the tower?',
      options: ['50√3 m', '150 m', '50 m', '100 m'],
      answer: 2,
      explain: 'tan 60° = 50√3/x = √3, so x = 50 m.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'A pole 12 m high casts a shadow 12√3 m long. What is the angle of elevation of the sun?',
      options: ['60°', '30°', '45°', '90°'],
      answer: 1,
      explain: 'tan θ = 12/(12√3) = 1/√3, so θ = 30°.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'A kite is flying on a string 100 m long that makes an angle of 30° with the ground. How high is the kite? (Assume the string is straight.)',
      options: ['25 m', '50√3 m', '100 m', '50 m'],
      answer: 3,
      explain: 'Height = 100 × sin 30° = 50 m.',
      shortcut: 'Opposite 30° is half the hypotenuse.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'The angle of elevation of the top of a tower changes from 30° to 60° as a man walks 40 m toward it. What is the height of the tower?',
      options: ['20√3 m', '40√3 m', '20 m', '40 m'],
      answer: 0,
      explain: 'h√3 − h/√3 = 40, so 2h/√3 = 40 and h = 20√3 m.',
      shortcut: 'h = √3/2 × 40 = 20√3.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'From the top of a cliff 75 m high, the angle of depression of a boat is 30°. How far is the boat from the foot of the cliff?',
      options: ['25√3 m', '75√3 m', '150 m', '75 m'],
      answer: 1,
      explain: 'tan 30° = 75/x, so x = 75√3 m.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'Two men on opposite sides of a tower 100 m high see its top at angles of elevation of 30° and 45°. How far apart are they?',
      options: ['100(√3 − 1) m', '100(√3 + 1) m', '200 m', '100√3 m'],
      answer: 1,
      explain: 'Distances are 100√3 and 100. Sum = 100(√3 + 1) ≈ 273.2 m.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'The shadow of a tower is 60 m longer when the sun\'s altitude is 30° than when it is 60°. What is the height of the tower?',
      options: ['60√3 m', '20√3 m', '30 m', '30√3 m'],
      answer: 3,
      explain: 'h√3 − h/√3 = 2h/√3 = 60, so h = 30√3 m.',
      shortcut: 'h = √3/2 × 60 = 30√3.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'The angles of elevation of the top of a tower from two points 9 m and 16 m from its base, on the same side and in line with it, are complementary. What is the height of the tower?',
      options: ['12 m', '12.5 m', '25 m', '7 m'],
      answer: 0,
      explain: 'tan θ = h/9 and cot θ = h/16. Multiply: h²/144 = 1, so h = 12 m.',
      shortcut: 'h = √(9 × 16) = 12.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'From the top of a building 60 m high, the angles of depression of the top and the bottom of a tower are 30° and 60°. What is the height of the tower?',
      options: ['20 m', '30 m', '40 m', '45 m'],
      answer: 2,
      explain: 'Gap = 60 cot 60° = 20√3. Drop to the tower top = 20√3 × tan 30° = 20. Tower = 60 − 20 = 40 m.',
      shortcut: 'For 30° and 60° the drop is 1/3 of the building, so the tower is 2/3 × 60 = 40.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'The angle of elevation of the top of a tower changes from 30° to 45° as an observer walks 100 m toward it. What is the height of the tower?',
      options: ['50(√3 − 1) m', '100√3 m', '100 m', '50(√3 + 1) m'],
      answer: 3,
      explain: 'h√3 − h = 100, so h = 100/(√3 − 1) = 50(√3 + 1) ≈ 136.6 m.',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: 'A man on top of a tower sees a car moving toward it at a steady speed. The angle of depression changes from 30° to 60° in 12 minutes. How much longer will the car take to reach the tower?',
      options: ['12 min', '8 min', '4 min', '6 min'],
      answer: 3,
      explain: 'Distances are h√3 and h/√3, a ratio of 3 : 1. So 2 parts take 12 min and the last part takes 6 min.',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: 'A 10 m flagstaff stands on a building. From a point on the ground, the angles of elevation of the top of the building and the top of the flagstaff are 30° and 45°. What is the height of the building?',
      options: ['5(√3 + 1) m', '5(√3 − 1) m', '10√3 m', '10(√3 + 1) m'],
      answer: 0,
      explain: 'Let the distance be x. Building = x/√3 and x = x/√3 + 10, so x = 10√3/(√3 − 1) = 5(3 + √3). Building = x/√3 = 5(√3 + 1) ≈ 13.66 m.',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: 'Two towers stand 60 m apart. From the foot of the shorter tower, the angle of elevation of the top of the taller one is 60°. From the foot of the taller tower, the angle of elevation of the top of the shorter one is 30°. What is the ratio of their heights (taller : shorter)?',
      options: ['√3 : 1', '2 : 1', '3 : 1', '9 : 1'],
      answer: 2,
      explain: 'Taller = 60 × tan 60° = 60√3. Shorter = 60 × tan 30° = 20√3. Ratio 3 : 1.',
      shortcut: 'tan 60° ÷ tan 30° = √3 × √3 = 3.',
    },
    {
      type: 'truefalse',
      difficulty: 'easy',
      statement: 'The angle of elevation of B from A equals the angle of depression of A from B.',
      answer: true,
      explain: 'They are alternate angles between two parallel horizontal lines.',
    },
    {
      type: 'truefalse',
      difficulty: 'medium',
      statement: 'As the sun\'s altitude increases, the shadow of a tower gets longer.',
      answer: false,
      explain: 'Shadow = h cot θ, and cot θ falls as θ rises, so the shadow gets shorter.',
    },
  ],
};

export default topic;
