import type { Topic } from '@/content/types';

const topic: Topic = {
  id: 'lines-angles',
  title: 'Lines and angles',
  level: 'beginner',
  masteryMinutes: 60,
  reviseMinutes: 20,
  priority: 'medium',
  tags: ['complementary', 'supplementary', 'linear pair', 'vertically opposite', 'transversal', 'alternate angles', 'co-interior', 'angle bisectors'],
  summary:
    'Straight line 180°, full turn 360°, and three rules for parallel lines. Almost every question is one equation in x built from these.',
  patterns: [
    { name: 'Parallel lines and a transversal: find x', frequency: 'most', example: 'Co-interior angles are (3x + 10)° and (2x + 20)°. Find x.' },
    { name: 'Complement and supplement word problems', frequency: 'most', example: 'An angle is 20° more than its complement. Find the angle.' },
    { name: 'Bent line between two parallel lines', frequency: 'often', example: 'AB ∥ CD, ∠BAE = 40°, ∠DCE = 55°. Find ∠AEC.' },
    { name: 'Vertically opposite angles and linear pairs', frequency: 'often', example: 'Vertically opposite angles are (5x − 12)° and (3x + 20)°. Find the angle.' },
    { name: 'Angle bisectors with parallel lines', frequency: 'rare', example: 'Bisectors of two co-interior angles meet at P. Find ∠P.' },
    { name: 'Angles around a point in a ratio', frequency: 'rare', example: 'Angles around a point are in the ratio 1 : 2 : 3 : 4. Largest?' },
  ],
  keyPoints: [
    {
      title: 'Complement and supplement',
      text: 'Two angles are complementary if they add to 90° and supplementary if they add to 180°. The supplement of any angle is always 90° more than its complement.',
      formula: 'complement = 90° − x; supplement = 180° − x',
      example: 'Complement of 38° is **52°**; supplement is **142°**; 142 − 52 = 90.',
    },
    {
      title: 'Straight line, point and crossing lines',
      text: 'Angles on a straight line (a linear pair) add to 180°. Angles around a point add to 360°. When two lines cross, vertically opposite angles are equal.',
      example: 'One angle at a crossing is 3 times its neighbour: x + 3x = 180, so the angles are 45° and **135°**.',
    },
    {
      title: 'Parallel lines cut by a transversal',
      text: 'Corresponding angles (F shape) are equal. Alternate interior angles (Z shape) are equal. Co-interior angles, on the same side between the lines (C shape), add to 180°. Each rule also works backwards to prove two lines parallel.',
      formula: 'corresponding = corresponding; alternate = alternate; co-interior sum = 180°',
      example: '(3x + 10) + (2x + 20) = 180 gives x = **30**.',
    },
    {
      title: 'A bent line between parallel lines',
      text: 'Draw a third line through the bend, parallel to both. If the bend points into the gap between the given angles (Z shapes), the bend angle is their sum. If the given angles are co-interior with the bend, all three add to 360°.',
      formula: '∠E = ∠a + ∠b, or ∠a + ∠b + ∠E = 360°',
      example: '∠BAE = 40°, ∠DCE = 55° on the Z side: ∠AEC = **95°**.',
    },
    {
      title: 'Angle as a multiple of its complement or supplement',
      text: 'If an angle is k times its supplement, split 180° in the ratio k : 1. If it is k times its complement, split 90° the same way.',
      formula: 'x = 180k/(k + 1) or x = 90k/(k + 1)',
      example: 'Angle = 4 × supplement: 180 × 4/5 = **144°**.',
    },
    {
      title: 'Sum and difference given',
      text: 'An angle that is d more than its complement is (90 + d)/2. An angle that is d more than its supplement is (180 + d)/2.',
      formula: 'larger = (sum + difference)/2',
      example: '20° more than its complement: (90 + 20)/2 = **55°**.',
    },
    {
      title: 'Angle bisectors',
      text: 'The bisectors of a linear pair are perpendicular. With parallel lines, the bisectors of two co-interior angles meet at 90°, and the bisectors of two alternate angles are parallel.',
      example: 'Co-interior angles 70° and 110°: halves 35° and 55° leave 180 − 35 − 55 = **90°**.',
    },
    {
      title: 'Counting lines and crossings',
      text: 'n points with no three in a line give n(n − 1)/2 lines. n lines with no two parallel and no three through one point cross at n(n − 1)/2 points.',
      formula: 'n(n − 1)/2',
      example: '8 such lines meet at 8 × 7/2 = **28** points.',
    },
  ],
  comparisons: [
    {
      title: 'Corresponding vs alternate vs co-interior angles',
      items: ['Corresponding', 'Alternate interior', 'Co-interior'],
      rows: [
        { aspect: 'Letter shape', values: ['F', 'Z', 'C or U'] },
        { aspect: 'Position', values: ['Same side of the transversal, same place at each line', 'Opposite sides of the transversal, between the lines', 'Same side of the transversal, between the lines'] },
        { aspect: 'Relation when lines are parallel', values: ['Equal', 'Equal', 'Add to 180°'], key: true },
        { aspect: 'Example with one angle 70°', values: ['70°', '70°', '110°'] },
      ],
      reveal: 'Only co-interior angles add up instead of being equal. Mix this up and you get 70° where the answer is 110°.',
      whenToUse: [
        'Both angles sit in the same corner at each line.',
        'The angles are on opposite sides, inside the parallel lines.',
        'The angles are on the same side, inside the parallel lines.',
      ],
    },
    {
      title: 'Complement vs supplement',
      items: ['Complement', 'Supplement'],
      rows: [
        { aspect: 'Pair adds to', values: ['90°', '180°'], key: true },
        { aspect: 'Of x', values: ['90° − x', '180° − x'] },
        { aspect: 'Exists for', values: ['Angles below 90° only', 'Angles below 180°'] },
        { aspect: 'Of 38°', values: ['52°', '142°'] },
      ],
      reveal: 'For the same angle the supplement is always exactly 90° bigger than the complement.',
      whenToUse: ['"Complementary", "complement", or parts of a right angle.', '"Supplementary", "linear pair", or parts of a straight line.'],
    },
  ],
  shortcuts: [
    {
      pattern: 'Angle is k times its supplement',
      example: 'An angle is 4 times its supplement. Find the angle.',
      options: ['36°', '144°', '135°', '120°'],
      answer: '144°',
      ladder: [
        { name: 'Standard', steps: ['x = 4(180 − x).', '5x = 720.', 'x = 144°.'], seconds: 25 },
        { name: 'Shortcut', steps: ['Split 180° in the ratio 4 : 1.', '180 × 4/5 = 144°.'], seconds: 8 },
        { name: 'Option elimination', steps: ['The angle must be 4 times what is left of 180.', '144 leaves 36, and 36 × 4 = 144.'], seconds: 6 },
      ],
    },
    {
      pattern: 'Bent line between parallel lines',
      example: 'AB ∥ CD. E lies between the lines, to the right of A and C. If ∠BAE = 40° and ∠DCE = 55°, find ∠AEC.',
      options: ['85°', '95°', '135°', '265°'],
      answer: '95°',
      ladder: [
        {
          name: 'Standard',
          steps: ['Draw EF through E parallel to AB.', '∠AEF = ∠BAE = 40° (alternate).', '∠FEC = ∠DCE = 55° (alternate).', '∠AEC = 40 + 55 = 95°.'],
          seconds: 40,
        },
        { name: 'Shortcut', steps: ['Z shape on both sides: the bend is the sum.', '40 + 55 = 95°.'], seconds: 6 },
      ],
    },
    {
      pattern: 'More than its complement by d',
      example: 'An angle is 20° more than its complement. Find the angle.',
      options: ['55°', '35°', '70°', '45°'],
      answer: '55°',
      ladder: [
        { name: 'Standard', steps: ['x = (90 − x) + 20.', '2x = 110.', 'x = 55°.'], seconds: 20 },
        { name: 'Shortcut', steps: ['(sum + difference)/2 = (90 + 20)/2 = 55°.'], seconds: 6 },
        { name: 'Option elimination', steps: ['The pair must add to 90 and differ by 20.', '55 and 35 do; the larger one is the angle.'], seconds: 5 },
      ],
    },
  ],
  qa: [
    {
      q: 'Which angle pairs are equal when a transversal cuts two parallel lines?',
      a: ['Corresponding angles (F).', 'Alternate interior and alternate exterior angles (Z).', 'Vertically opposite angles.'],
      tag: 'Asked often',
    },
    {
      q: 'Which pair adds to 180° instead of being equal?',
      a: ['Co-interior angles: same side of the transversal, between the lines.', 'Also any linear pair.'],
      tag: 'Trap',
    },
    {
      q: 'Difference between the supplement and the complement of an angle?',
      a: ['Always 90°.', '(180 − x) − (90 − x) = 90.'],
      tag: 'Shortcut',
    },
    {
      q: 'Angle at the bend of a zig-zag between parallel lines?',
      a: ['Draw a line through the bend parallel to both.', 'Z shapes: bend = sum of the two angles.', 'C shapes: the three angles add to 360°.'],
      tag: 'Asked often',
    },
    {
      q: 'The bisectors of two co-interior angles meet. At what angle?',
      a: ['90°.', 'The two halves add to 180/2 = 90, leaving 90° at the meeting point.'],
    },
    {
      q: 'The bisectors of a linear pair meet at what angle?',
      a: ['90°.', 'Half of 180° is 90°.'],
    },
    {
      q: 'Can an angle of 100° have a complement?',
      a: ['No. Only angles less than 90° have complements.', 'It does have a supplement: 80°.'],
      tag: 'Trap',
    },
    {
      q: 'Angle is k times its complement. Fast formula?',
      a: ['Split 90° in the ratio k : 1.', 'x = 90k/(k + 1). For k = 2: 60°.'],
      tag: 'Shortcut',
    },
    {
      q: 'How many angles are formed where a transversal cuts two lines?',
      a: ['8 angles: 4 at each crossing.', '4 are interior and 4 are exterior.'],
    },
    {
      q: 'Maximum crossing points of n lines?',
      a: ['n(n − 1)/2, with no two parallel and no three through one point.', '6 lines: 15 points.'],
    },
  ],
  quiz: [
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'What is the complement of 38°?',
      options: ['52°', '142°', '62°', '48°'],
      answer: 0,
      explain: '90 − 38 = 52°.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'Two parallel lines are cut by a transversal. Two co-interior angles are (3x + 10)° and (2x + 20)°. What is x?',
      options: ['26', '30', '34', '40'],
      answer: 1,
      explain: 'Co-interior angles add to 180: 5x + 30 = 180, so x = 30.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'Two vertically opposite angles are (5x − 12)° and (3x + 20)°. What is the size of each angle?',
      options: ['112°', '16°', '56°', '68°'],
      answer: 3,
      explain: '5x − 12 = 3x + 20 gives x = 16. Each angle is 5 × 16 − 12 = 68°.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'Two complementary angles are such that the larger is 6° less than twice the smaller. What is the larger angle?',
      options: ['32°', '58°', '64°', '52°'],
      answer: 1,
      explain: 's + (2s − 6) = 90 gives s = 32. Larger = 58°.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'An angle is 20° more than its complement. What is the angle?',
      options: ['35°', '55°', '65°', '70°'],
      answer: 1,
      explain: 'x = (90 − x) + 20, so 2x = 110 and x = 55°.',
      shortcut: '(90 + 20)/2 = 55°.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'An angle is 4 times its supplement. What is the angle?',
      options: ['36°', '120°', '144°', '150°'],
      answer: 2,
      explain: 'x = 4(180 − x), so 5x = 720 and x = 144°.',
      shortcut: 'Split 180 in the ratio 4 : 1: 180 × 4/5 = 144.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'The supplement of an angle is 4 times its complement. What is the angle?',
      options: ['60°', '45°', '30°', '75°'],
      answer: 0,
      explain: '180 − x = 4(90 − x) gives 3x = 180, so x = 60°.',
      shortcut: 'Supplement − complement = 90 = 3 × complement, so the complement is 30 and the angle 60.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'AB ∥ CD. Point E lies between the lines, to the right of A and C. If ∠BAE = 40° and ∠DCE = 55°, what is ∠AEC?',
      options: ['85°', '135°', '265°', '95°'],
      answer: 3,
      explain: 'Draw a line through E parallel to AB. By alternate angles ∠AEC = 40 + 55 = 95°.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'Two lines cross. One of the four angles formed is 3 times its adjacent angle. What is the largest angle?',
      options: ['120°', '135°', '45°', '150°'],
      answer: 1,
      explain: 'Adjacent angles form a linear pair: x + 3x = 180, so x = 45 and the larger is 135°.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'Four angles around a point are in the ratio 1 : 2 : 3 : 4. What is the largest angle?',
      options: ['108°', '120°', '160°', '144°'],
      answer: 3,
      explain: '10 parts = 360°, so one part = 36°. Largest = 4 × 36 = 144°.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'A transversal cuts two parallel lines. Two corresponding angles are (2x + 15)° and (3x − 20)°. What is x?',
      options: ['25', '40', '35', '45'],
      answer: 2,
      explain: 'Corresponding angles are equal: 2x + 15 = 3x − 20, so x = 35.',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: 'AB ∥ CD. Point E lies between the lines, to the left of A and C, with B and D to the right. If ∠BAE = 130° and ∠DCE = 125°, what is ∠AEC?',
      options: ['75°', '95°', '115°', '105°'],
      answer: 3,
      explain: 'The given angles are co-interior with the bend, so the three add to 360°. ∠AEC = 360 − 130 − 125 = 105°.',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: 'AB ∥ CD and a transversal meets them at G and H. The bisectors of ∠BGH and ∠DHG (on the same side) meet at P. If ∠BGH = 70°, what is ∠PHG?',
      options: ['35°', '70°', '55°', '45°'],
      answer: 2,
      explain: '∠BGH and ∠DHG are co-interior, so ∠DHG = 110°. Its half is ∠PHG = 55°.',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: 'The supplement of an angle is 30° less than 3 times its complement. What is the angle?',
      options: ['30°', '45°', '60°', '20°'],
      answer: 0,
      explain: '180 − x = 3(90 − x) − 30 = 240 − 3x, so 2x = 60 and x = 30°.',
    },
    {
      type: 'truefalse',
      difficulty: 'easy',
      statement: 'The bisectors of two co-interior angles formed by a transversal with two parallel lines meet at right angles.',
      answer: true,
      explain: 'The co-interior angles add to 180°, their halves add to 90°, so the angle between the bisectors is 90°.',
    },
    {
      type: 'truefalse',
      difficulty: 'medium',
      statement: 'Alternate interior angles formed by a transversal with two parallel lines are supplementary.',
      answer: false,
      explain: 'Alternate interior angles are equal. It is the co-interior angles that add to 180°.',
    },
  ],
};

export default topic;
