import type { Topic } from '@/content/types';

const topic: Topic = {
  id: 'linear-equations',
  title: 'Linear equations and polynomials',
  level: 'beginner',
  masteryMinutes: 60,
  reviseMinutes: 20,
  priority: 'medium',
  tags: ['linear equations', 'two variables', 'consistency', 'no solution', 'infinite solutions', 'remainder theorem', 'factor theorem', 'zeros of a polynomial'],
  summary:
    'Two equations in two unknowns: add or subtract them before you solve. For polynomials, the remainder on dividing by (x − a) is just p(a).',
  patterns: [
    { name: 'Solve a pair or find x + y, x − y', frequency: 'most', example: 'If 3x + 2y = 12 and 2x + 3y = 13, find x + y.' },
    { name: 'Unique, no or infinite solutions (find k)', frequency: 'most', example: 'For what k do 3x + ky = 8 and 9x + 12y = 15 have no solution?' },
    { name: 'Remainder theorem', frequency: 'often', example: 'Remainder when x³ − 2x² + 4x − 5 is divided by (x − 2)?' },
    { name: 'Factor theorem: find the missing coefficient', frequency: 'often', example: 'If (x + 2) is a factor of x³ + kx² − 4, find k.' },
    { name: 'Word problems: digits, ages, fractions', frequency: 'often', example: 'Digits add to 9; reversing adds 27. Find the number.' },
    { name: 'Sum and product of zeros', frequency: 'rare', example: 'If α, β are zeros of x² − 5x + 6, find α² + β².' },
  ],
  keyPoints: [
    {
      title: 'Elimination and the cross-multiplication rule',
      text: 'For a₁x + b₁y = c₁ and a₂x + b₂y = c₂, make one coefficient equal and subtract. Or use the cross-multiplication rule directly.',
      formula: 'x = (c₁b₂ − c₂b₁)/(a₁b₂ − a₂b₁), y = (a₁c₂ − a₂c₁)/(a₁b₂ − a₂b₁)',
      example: 'x + y = 7, x − y = 1: add to get 2x = 8, so x = **4**, y = **3**.',
    },
    {
      title: 'Swapped coefficients: add and subtract',
      text: 'When the pair looks like ax + by = p and bx + ay = q, adding gives x + y and subtracting gives x − y at once.',
      formula: 'x + y = (p + q)/(a + b), x − y = (p − q)/(a − b)',
      example: '3x + 2y = 12, 2x + 3y = 13: x + y = 25/5 = **5**, x − y = −1/1 = **−1**.',
    },
    {
      title: 'Consistency: how many solutions?',
      text: 'Compare the ratios of the coefficients. Unequal x and y ratios mean one solution. Equal x and y ratios but a different constant ratio mean none. All three equal means infinitely many.',
      formula: 'a₁/a₂ ≠ b₁/b₂ unique; a₁/a₂ = b₁/b₂ ≠ c₁/c₂ none; a₁/a₂ = b₁/b₂ = c₁/c₂ infinite',
      example: 'x + 2y = 4 and 2x + 4y = 12: 1/2 = 2/4 but 4/12 = 1/3, so **no solution**.',
    },
    {
      title: 'Equations with 1/x and 1/y',
      text: 'Put u = 1/x and v = 1/y. The pair becomes linear in u and v. Solve, then flip back.',
      example: '2/x + 3/y = 13, 5/x − 4/y = −2 give u = 2, v = 3, so x = **1/2**, y = **1/3**.',
    },
    {
      title: 'Remainder theorem',
      text: 'The remainder when p(x) is divided by (x − a) is p(a). For a divisor (ax − b), put x = b/a. No long division needed.',
      formula: 'p(x) ÷ (x − a) leaves p(a); p(x) ÷ (ax − b) leaves p(b/a)',
      example: 'x³ − 2x² + 4x − 5 ÷ (x − 2): 8 − 8 + 8 − 5 = **3**.',
    },
    {
      title: 'Factor theorem and quick factor checks',
      text: '(x − a) is a factor exactly when p(a) = 0. If the coefficients add to 0, (x − 1) is a factor. If the even-power coefficients add to the same as the odd-power ones, (x + 1) is a factor.',
      formula: '(x − a) is a factor ⇔ p(a) = 0',
      example: '(x + 2) a factor of x³ + kx² − 4: −8 + 4k − 4 = 0, so k = **3**.',
    },
    {
      title: 'Zeros and coefficients',
      text: 'For ax² + bx + c the zeros satisfy α + β = −b/a and αβ = c/a. For ax³ + bx² + cx + d: sum −b/a, sum of pairs c/a, product −d/a.',
      formula: 'α + β = −b/a, αβ = c/a',
      example: 'x² − 5x + 6: α + β = 5, αβ = 6, so α² + β² = 25 − 12 = **13**.',
    },
    {
      title: 'Setting up word problems',
      text: 'A two-digit number with digits x and y is 10x + y. Reversing it changes the number by 9(x − y). For ages, write every age at the same present time first.',
      formula: '(10x + y) − (10y + x) = 9(x − y)',
      example: 'Digits add to 9, reversal adds 27: y − x = 3, so the number is **36**.',
    },
  ],
  comparisons: [
    {
      title: 'Unique vs no vs infinite solutions',
      items: ['Unique solution', 'No solution', 'Infinitely many'],
      rows: [
        { aspect: 'Ratio test', values: ['a₁/a₂ ≠ b₁/b₂', 'a₁/a₂ = b₁/b₂ ≠ c₁/c₂', 'a₁/a₂ = b₁/b₂ = c₁/c₂'], key: true },
        { aspect: 'Graph', values: ['Lines cross at one point', 'Parallel lines', 'Same line twice'] },
        { aspect: 'Name', values: ['Consistent', 'Inconsistent', 'Consistent (dependent)'] },
        { aspect: 'Example', values: ['x + y = 5, x − y = 1', 'x + 2y = 4, 2x + 4y = 12', 'x + 2y = 4, 2x + 4y = 8'] },
      ],
      reveal: 'Only the x and y ratios decide whether the lines are parallel. The constant ratio then decides if the parallel lines are separate or the same.',
      whenToUse: [
        '"Unique solution": set a₁/a₂ ≠ b₁/b₂ and solve for k.',
        '"No solution" or "inconsistent": equate the x and y ratios, then check the constant ratio differs.',
        '"Infinitely many" or "coincident": set all three ratios equal.',
      ],
    },
    {
      title: 'Remainder theorem vs factor theorem',
      items: ['Remainder theorem', 'Factor theorem'],
      rows: [
        { aspect: 'Question asks', values: ['The remainder', 'Whether (x − a) divides exactly, or a missing coefficient'] },
        { aspect: 'What you compute', values: ['p(a)', 'p(a) and set it to 0'], key: true },
        { aspect: 'Divisor (2x − 1)', values: ['Remainder p(1/2)', 'Factor if p(1/2) = 0'] },
      ],
      reveal: 'Both put x = a into the polynomial. The factor theorem is the special case where the remainder is 0.',
      whenToUse: ['Any "find the remainder" question.', 'Any "is a factor" or "find k so that it divides" question.'],
    },
  ],
  shortcuts: [
    {
      pattern: 'Swapped coefficients',
      example: 'If 3x + 2y = 12 and 2x + 3y = 13, what is x + y?',
      options: ['4', '5', '6', '7'],
      answer: '5',
      ladder: [
        {
          name: 'Standard',
          steps: ['Multiply the first by 3 and the second by 2: 9x + 6y = 36, 4x + 6y = 26.', 'Subtract: 5x = 10, so x = 2.', 'Then y = 3, and x + y = 5.'],
          seconds: 45,
        },
        { name: 'Shortcut', steps: ['Add the two equations: 5x + 5y = 25.', 'x + y = 5.'], seconds: 8 },
      ],
    },
    {
      pattern: 'Find k for no solution',
      example: 'For what value of k do 3x + ky = 8 and 9x + 12y = 15 have no solution?',
      options: ['3', '4', '12', '−4'],
      answer: '4',
      ladder: [
        {
          name: 'Standard',
          steps: ['Solve the pair in terms of k.', 'The denominator 36 − 9k must be 0, so k = 4.', 'Check the numerator is not 0 at k = 4.'],
          seconds: 60,
        },
        { name: 'Shortcut', steps: ['3/9 = k/12, so k = 4.', 'Constant ratio 8/15 ≠ 1/3, so there is no solution.'], seconds: 15 },
        { name: 'Option elimination', steps: ['Parallel lines need 3 : 9 = k : 12.', 'Only k = 4 gives 1 : 3.'], seconds: 8 },
      ],
    },
    {
      pattern: 'Remainder without division',
      example: 'Find the remainder when x³ − 3x² + 4x − 7 is divided by (x − 2).',
      options: ['−3', '3', '1', '−1'],
      answer: '−3',
      ladder: [
        { name: 'Standard', steps: ['Long division by (x − 2).', 'Quotient x² − x + 2, remainder −3.'], seconds: 75 },
        { name: 'Shortcut', steps: ['Remainder theorem: p(2) = 8 − 12 + 8 − 7 = −3.'], seconds: 12 },
      ],
    },
  ],
  qa: [
    {
      q: 'What is the condition for a pair of linear equations to have no solution?',
      a: ['a₁/a₂ = b₁/b₂ ≠ c₁/c₂.', 'The lines are parallel and never meet.'],
      tag: 'Asked often',
    },
    {
      q: 'What is the condition for infinitely many solutions?',
      a: ['a₁/a₂ = b₁/b₂ = c₁/c₂.', 'Both equations describe the same line.'],
      tag: 'Asked often',
    },
    {
      q: 'The pair is ax + by = p and bx + ay = q. Fastest way to x + y?',
      a: ['Add them: (a + b)(x + y) = p + q.', 'Subtract them for x − y: (a − b)(x − y) = p − q.'],
      tag: 'Shortcut',
    },
    {
      q: 'What is the remainder when p(x) is divided by (x − a)?',
      a: ['p(a).', 'For (x + a), use p(−a). For (ax − b), use p(b/a).'],
      tag: 'Shortcut',
    },
    {
      q: 'For the divisor (x + 3), which value do you put in?',
      a: ['x = −3, not 3.', 'Set the divisor to 0 and solve for x.'],
      tag: 'Trap',
    },
    {
      q: 'How do you spot that (x − 1) is a factor without dividing?',
      a: ['The coefficients add up to 0.', 'x³ − 6x² + 11x − 6: 1 − 6 + 11 − 6 = 0, so (x − 1) is a factor.'],
    },
    {
      q: 'How do you spot that (x + 1) is a factor?',
      a: ['Sum of the even-power coefficients equals the sum of the odd-power ones.', 'That makes p(−1) = 0.'],
    },
    {
      q: 'Sum and product of the zeros of ax² + bx + c?',
      a: ['Sum = −b/a.', 'Product = c/a.', 'Watch the minus sign on the sum.'],
      tag: 'Trap',
    },
    {
      q: 'A two-digit number and its reverse differ by 36. What is the difference of the digits?',
      a: ['The gap is always 9 × (difference of digits).', '36 ÷ 9 = 4.'],
      tag: 'Shortcut',
    },
    {
      q: 'Is 2/x + 3/y = 13 a linear equation?',
      a: ['Not in x and y, but it is linear in u = 1/x and v = 1/y.', 'Substitute, solve for u and v, then flip back.'],
    },
  ],
  quiz: [
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'If 3x + 2y = 12 and 2x + 3y = 13, what is x − y?',
      options: ['1', '−1', '5', '−5'],
      answer: 1,
      explain: 'Subtract the second from the first: x − y = 12 − 13 = −1.',
      shortcut: 'Swapped coefficients: x − y = (p − q)/(a − b) = −1/1.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'What is the remainder when x³ − 2x² + 4x − 5 is divided by (x − 2)?',
      options: ['−3', '5', '11', '3'],
      answer: 3,
      explain: 'p(2) = 8 − 8 + 8 − 5 = 3.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'If (x + 2) is a factor of x³ + kx² − 4, what is k?',
      options: ['2', '3', '4', '−3'],
      answer: 1,
      explain: 'p(−2) = −8 + 4k − 4 = 0, so 4k = 12 and k = 3.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'For what value of k do the equations 3x + ky = 8 and 9x + 12y = 15 have no solution?',
      options: ['4', '3', '12', '−4'],
      answer: 0,
      explain: '3/9 = k/12 gives k = 4. The constant ratio 8/15 ≠ 1/3, so the lines are parallel.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'For which values of k do kx + 2y = 5 and 3x + y = 1 have a unique solution?',
      options: ['k = 6', 'k ≠ 6', 'k ≠ 3/2', 'k = 3/2'],
      answer: 1,
      explain: 'Unique solution needs k/3 ≠ 2/1, so k ≠ 6.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'What is the remainder when 2x³ − 3x² + x − 4 is divided by (2x − 1)?',
      options: ['4', '0', '−4', '−3'],
      answer: 2,
      explain: 'Put x = 1/2: 2/8 − 3/4 + 1/2 − 4 = 0.25 − 0.75 + 0.5 − 4 = −4.',
      shortcut: 'Divisor (ax − b): put x = b/a.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'The digits of a two-digit number add up to 9. When the digits are reversed, the number increases by 27. What is the number?',
      options: ['63', '36', '45', '27'],
      answer: 1,
      explain: '9(y − x) = 27 so y − x = 3, and x + y = 9. So x = 3, y = 6: the number is 36.',
      shortcut: 'Check the options: only 36 has digit sum 9 and 63 − 36 = 27.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: "Five years ago, A was three times as old as B. Ten years from now, A will be twice as old as B. What is A's present age?",
      options: ['40', '45', '50', '55'],
      answer: 2,
      explain: 'A − 5 = 3(B − 5) gives A = 3B − 10. A + 10 = 2(B + 10) gives A = 2B + 10. So B = 20, A = 50.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'If α and β are the zeros of x² − 5x + 6, what is α² + β²?',
      options: ['11', '13', '25', '19'],
      answer: 1,
      explain: 'α + β = 5, αβ = 6. α² + β² = (α + β)² − 2αβ = 25 − 12 = 13.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'If 2/x + 3/y = 13 and 5/x − 4/y = −2, what is x + y?',
      options: ['5/6', '5', '1/6', '6/5'],
      answer: 0,
      explain: 'Put u = 1/x, v = 1/y: 2u + 3v = 13, 5u − 4v = −2 give u = 2, v = 3. So x = 1/2, y = 1/3 and x + y = 5/6.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'If 1 is added to both the numerator and the denominator of a fraction, it becomes 4/5. If 5 is subtracted from both, it becomes 1/2. What is the fraction?',
      options: ['5/7', '3/4', '7/9', '9/11'],
      answer: 2,
      explain: '5(x + 1) = 4(y + 1) and 2(x − 5) = y − 5. So y = 2x − 5 and 5x − 4y = −1 give x = 7, y = 9.',
      shortcut: 'Test options: 7/9 → 8/10 = 4/5 and 2/4 = 1/2.',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: 'For what value of k do 2x + 3y = 7 and (k − 1)x + (k + 2)y = 3k have infinitely many solutions?',
      options: ['5', '4', '7', '8'],
      answer: 2,
      explain: '2/(k − 1) = 3/(k + 2) gives 2k + 4 = 3k − 3, so k = 7. Check: 7/21 = 1/3 = 3/9.',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: 'x³ + ax² + bx + 6 has (x − 2) as a factor and leaves remainder 3 when divided by (x − 3). What is a + b?',
      options: ['−3', '4', '−1', '−4'],
      answer: 3,
      explain: 'p(2) = 0 gives 2a + b = −7. p(3) = 3 gives 3a + b = −10. So a = −3, b = −1 and a + b = −4.',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: 'If α, β, γ are the zeros of 2x³ − 5x² − 14x + 8, what is 1/α + 1/β + 1/γ?',
      options: ['−7/4', '5/2', '7/4', '−7'],
      answer: 2,
      explain: 'Sum of pairs = c/a = −7, product = −d/a = −4. 1/α + 1/β + 1/γ = (αβ + βγ + γα)/αβγ = −7/(−4) = 7/4.',
      shortcut: 'The zeros are 4, 1/2 and −2: 1/4 + 2 − 1/2 = 7/4.',
    },
    {
      type: 'truefalse',
      difficulty: 'easy',
      statement: 'The pair x + 2y = 4 and 2x + 4y = 12 has no solution.',
      answer: true,
      explain: '1/2 = 2/4 but 4/12 = 1/3, so the lines are parallel and never meet.',
    },
    {
      type: 'truefalse',
      difficulty: 'medium',
      statement: 'If the coefficients of a polynomial add up to 0, then (x + 1) is a factor.',
      answer: false,
      explain: 'Coefficients adding to 0 means p(1) = 0, so (x − 1) is the factor, not (x + 1).',
    },
  ],
};

export default topic;
