import type { Topic } from '@/content/types';

const topic: Topic = {
  id: 'mensuration-3d',
  title: '3D solids: volume and surface area',
  level: 'intermediate',
  masteryMinutes: 120,
  reviseMinutes: 40,
  priority: 'high',
  weightage: { tier1: 1, tier2: 1.5 },
  tags: ['volume', 'surface area', 'cube', 'cuboid', 'cylinder', 'cone', 'sphere', 'hemisphere', 'frustum', 'prism', 'pyramid', 'melting and recasting'],
  summary:
    'Volume stays the same when a solid is melted and recast, and surface area and volume scale as k² and k³. With the cylinder, cone and sphere formulas, that covers most questions.',
  patterns: [
    { name: 'Melting and recasting', frequency: 'most', example: 'A sphere of radius 9 cm is melted into spheres of radius 3 cm. How many?' },
    { name: 'Cylinder, cone and sphere: direct volume or surface area', frequency: 'most', example: 'A cone has radius 6 cm and height 8 cm. Curved surface area?' },
    { name: 'Cube and cuboid: diagonal, surface area, small cubes', frequency: 'often', example: 'Longest rod that fits in a 12 m × 9 m × 8 m room?' },
    { name: 'Ratio of volumes or surface areas', frequency: 'often', example: 'Cylinder, cone and sphere of the same radius and height 2r. Ratio of volumes?' },
    { name: 'Percentage change in volume or surface area', frequency: 'often', example: 'Radius of a sphere rises 10%. Change in volume?' },
    { name: 'Hemisphere and combined solids; water level rise', frequency: 'often', example: 'A toy is a cone on a hemisphere of radius 7 cm. Total surface area?' },
    { name: 'Frustum, prism and pyramid', frequency: 'rare', example: 'Frustum with radii 10 cm and 4 cm, height 8 cm. Volume?' },
  ],
  keyPoints: [
    {
      title: 'Cuboid and cube',
      text: 'Cuboid: volume lbh, total surface 2(lb + bh + hl), lateral surface (four walls) 2h(l + b), diagonal √(l² + b² + h²). Cube of side a: volume a³, surface 6a², diagonal a√3.',
      formula: 'Cuboid diagonal = √(l² + b² + h²),  cube diagonal = a√3',
      example: 'Room 12 × 9 × 8: longest rod = √(144 + 81 + 64) = √289 = **17 m**.',
    },
    {
      title: 'Cylinder',
      text: 'Volume πr²h, curved surface 2πrh, total surface 2πr(r + h). Hollow pipe: π(R² − r²)h.',
      formula: 'V = πr²h,  CSA = 2πrh,  TSA = 2πr(r + h)',
      example: 'r = 7, h = 10: V = 22/7 × 49 × 10 = **1,540**.',
    },
    {
      title: 'Cone',
      text: 'Volume is one third of the cylinder with the same base and height. Slant height l from Pythagoras. When a sector is rolled into a cone, the arc becomes the base circumference and the sector radius becomes the slant height.',
      formula: 'V = 1/3 πr²h,  l = √(r² + h²),  CSA = πrl,  TSA = πr(l + r)',
      example: 'r = 6, h = 8: l = 10, CSA = **60π**.',
    },
    {
      title: 'Sphere and hemisphere',
      text: 'Sphere: volume 4/3 πr³, surface 4πr². Hemisphere: volume 2/3 πr³, curved surface 2πr², total surface 3πr² (the flat circle is added).',
      formula: 'Sphere V = 4/3 πr³,  SA = 4πr²;  hemisphere TSA = 3πr²',
      example: 'Hemisphere r = 7: TSA = 3 × 22/7 × 49 = **462**.',
    },
    {
      title: 'Frustum of a cone',
      text: 'A cone with its top cut off parallel to the base. R and r are the two radii, h the height.',
      formula: 'V = 1/3 πh(R² + r² + Rr),  CSA = π(R + r)l,  l = √(h² + (R − r)²)',
      example: 'R = 10, r = 4, h = 8: V = 1/3 π × 8 × 156 = **416π**.',
    },
    {
      title: 'Prism and pyramid',
      text: 'Prism: volume = base area × height, lateral surface = base perimeter × height. Pyramid: volume = 1/3 × base area × height, lateral surface = 1/2 × base perimeter × slant height.',
      formula: 'Pyramid V = 1/3 × base area × h',
      example: 'Square base 10, height 12: slant = 13, lateral = 1/2 × 40 × 13 = **260**.',
    },
    {
      title: 'Melting and recasting',
      text: 'The volume does not change. Number of small solids = big volume ÷ one small volume. For spheres into spheres this is (R/r)³. For a sphere drawn into a wire, the wire is a long cylinder.',
      formula: 'n = (R/r)³ for spheres',
      example: 'Radius 9 into radius 3: (9/3)³ = **27** balls.',
    },
    {
      title: 'Scaling and percentage change',
      text: 'Multiply every length by k: surface area × k², volume × k³. For x% change in every length, surface area changes 2x + x²/100 percent; volume: apply x% three times.',
      formula: 'Volume factor = (1 + x/100)³',
      example: 'Radius +10%: 1.1³ = 1.331, volume up **33.1%**; surface up 21%.',
    },
  ],
  comparisons: [
    {
      title: 'Cylinder vs cone vs sphere',
      items: ['Cylinder', 'Cone', 'Sphere', 'Hemisphere'],
      rows: [
        { aspect: 'Volume', values: ['πr²h', '1/3 πr²h', '4/3 πr³', '2/3 πr³'], key: true },
        { aspect: 'Curved surface', values: ['2πrh', 'πrl', '4πr²', '2πr²'] },
        { aspect: 'Total surface', values: ['2πr(r + h)', 'πr(l + r)', '4πr²', '3πr²'] },
        { aspect: 'Same r, h = 2r: volume', values: ['2πr³ (ratio 3)', '2/3 πr³ (ratio 1)', '4/3 πr³ (ratio 2)', '2/3 πr³ (ratio 1)'] },
      ],
      reveal: 'A cone is one third of its cylinder. A sphere that fits exactly inside a cylinder is two thirds of it. So cylinder : cone : sphere = 3 : 1 : 2.',
      whenToUse: [
        'Pipes, tanks, wells, rollers and coins.',
        'Tents, ice-cream cones, heaps of grain, and a sector rolled up.',
        'Balls, lead shots and bubbles.',
        'Bowls, domes and the base of a toy.',
      ],
    },
    {
      title: 'Cube vs cuboid',
      items: ['Cube (side a)', 'Cuboid (l, b, h)'],
      rows: [
        { aspect: 'Volume', values: ['a³', 'lbh'] },
        { aspect: 'Total surface', values: ['6a²', '2(lb + bh + hl)'] },
        { aspect: 'Lateral surface (4 walls)', values: ['4a²', '2h(l + b)'] },
        { aspect: 'Diagonal (longest rod)', values: ['a√3', '√(l² + b² + h²)'], key: true },
      ],
      reveal: 'A cube is a cuboid with l = b = h = a. Room questions ask for the four walls, so use the lateral surface.',
      whenToUse: [
        'Dice, boxes of equal sides, and small cubes cut from a block.',
        'Rooms, bricks, tanks and boxes.',
      ],
    },
  ],
  shortcuts: [
    {
      pattern: 'Spheres melted into smaller spheres',
      example: 'A solid sphere of radius 9 cm is melted and recast into small spheres of radius 3 cm. How many small spheres are made?',
      options: ['27', '9', '81', '3'],
      answer: '27',
      ladder: [
        { name: 'Standard', steps: ['Big volume = 4/3 π × 729.', 'Small volume = 4/3 π × 27.', 'n = 729 ÷ 27 = 27.'], seconds: 30 },
        { name: 'Shortcut', steps: ['n = (R/r)³ = 3³ = 27.'], seconds: 5 },
        { name: 'Option elimination', steps: ['Volume goes as the cube of the radius ratio 3.', '9 is only the square and 3 is only the ratio. 27 is the cube.'], seconds: 5 },
      ],
    },
    {
      pattern: 'Cylinder, cone and sphere of the same size',
      example: 'A cylinder, a cone and a sphere have the same radius, and the height of the cylinder and cone equals the diameter of the sphere. Ratio of their volumes?',
      options: ['3 : 1 : 2', '1 : 2 : 3', '3 : 2 : 1', '2 : 1 : 3'],
      answer: '3 : 1 : 2',
      ladder: [
        { name: 'Standard', steps: ['Cylinder: πr² × 2r = 2πr³.', 'Cone: 1/3 × πr² × 2r = 2/3 πr³.', 'Sphere: 4/3 πr³.', 'Ratio 2 : 2/3 : 4/3 = 6 : 2 : 4 = 3 : 1 : 2.'], seconds: 45 },
        { name: 'Shortcut', steps: ['Cone is 1/3 of the cylinder and sphere is 2/3 of it.', '1 : 1/3 : 2/3 = 3 : 1 : 2.'], seconds: 10 },
        { name: 'Option elimination', steps: ['The cylinder is the biggest and the cone the smallest.', 'Only 3 : 1 : 2 has that order.'], seconds: 5 },
      ],
    },
    {
      pattern: 'Percentage change in volume',
      example: 'The radius of a sphere is increased by 20%. By what percent does its volume increase?',
      options: ['60%', '72.8%', '44%', '20%'],
      answer: '72.8%',
      ladder: [
        { name: 'Standard', steps: ['Take r = 10: volume ∝ 1,000.', 'New r = 12: volume ∝ 1,728.', 'Increase 728 on 1,000 = 72.8%.'], seconds: 30 },
        { name: 'Shortcut', steps: ['Apply 20% three times: 20 + 20 + 4 = 44.', '44 + 20 + 8.8 = 72.8%.'], seconds: 15 },
        { name: 'Option elimination', steps: ['Must be more than 3 × 20 = 60%, since the changes compound.', 'Only 72.8% is above 60%.'], seconds: 5 },
      ],
    },
  ],
  qa: [
    {
      q: 'What stays the same when a solid is melted and recast?',
      a: ['The volume.', 'Surface area usually changes.'],
      tag: 'Asked often',
    },
    {
      q: 'How many spheres of radius r come from one of radius R?',
      a: ['(R/r)³.', 'Radius 6 into radius 2: 27 spheres.'],
      tag: 'Shortcut',
    },
    {
      q: 'Total surface area of a solid hemisphere?',
      a: ['3πr²: curved 2πr² plus the flat circle πr².', 'A hollow bowl has only the curved 2πr².'],
      tag: 'Trap',
    },
    {
      q: 'Slant height of a cone?',
      a: ['l = √(r² + h²).', 'Common triplets: (6, 8, 10), (5, 12, 13), (7, 24, 25).'],
    },
    {
      q: 'Radius doubled and height halved: what happens to a cylinder\'s volume?',
      a: ['πr²h becomes π(2r)²(h/2) = 2πr²h.', 'It doubles.'],
      tag: 'Asked often',
    },
    {
      q: 'Every edge of a cube is doubled. What happens to surface area and volume?',
      a: ['Surface area × 4.', 'Volume × 8.'],
      tag: 'Trap',
    },
    {
      q: 'A sector is rolled into a cone. What becomes what?',
      a: ['Sector radius → slant height of the cone.', 'Arc length → base circumference 2πr.'],
    },
    {
      q: 'Water level rise when a solid is dropped into a cylindrical vessel?',
      a: ['Rise × πR² = volume of the solid.', 'R is the radius of the vessel, not of the solid.'],
      tag: 'Asked often',
    },
    {
      q: 'Volume of a frustum?',
      a: ['1/3 πh(R² + r² + Rr).', 'Think of it as a big cone minus a small cone.'],
    },
    {
      q: 'Cylinder, cone and sphere with the same radius and height 2r: volume ratio?',
      a: ['3 : 1 : 2.', 'Cone is 1/3 and sphere is 2/3 of the cylinder.'],
      tag: 'Shortcut',
    },
  ],
  quiz: [
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'The total surface area of a cube is 150 cm². What is its volume?',
      options: ['125 cm³', '216 cm³', '100 cm³', '150 cm³'],
      answer: 0,
      explain: '6a² = 150, so a = 5. Volume = 125 cm³.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'Find the volume of a cylinder of radius 7 cm and height 10 cm. (Take π = 22/7.)',
      options: ['770 cm³', '1,540 cm³', '3,080 cm³', '1,078 cm³'],
      answer: 1,
      explain: '22/7 × 49 × 10 = 1,540 cm³.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'A cone has base radius 6 cm and height 8 cm. What is its curved surface area?',
      options: ['48π cm²', '96π cm²', '60π cm²', '36π cm²'],
      answer: 2,
      explain: 'l = √(36 + 64) = 10. CSA = π × 6 × 10 = 60π cm².',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'A room is 12 m long, 9 m wide and 8 m high. What is the length of the longest rod that can be placed in it?',
      options: ['17 m', '15 m', '19 m', '16 m'],
      answer: 0,
      explain: '√(144 + 81 + 64) = √289 = 17 m.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'A metal sphere of radius 6 cm is melted and drawn into a wire of radius 0.2 cm. How long is the wire?',
      options: ['36 m', '7.2 m', '144 m', '72 m'],
      answer: 3,
      explain: '4/3 π × 216 = π × 0.04 × L, so L = 288 ÷ 0.04 = 7,200 cm = 72 m.',
      shortcut: 'π cancels: L = 4r³/(3 × 0.04) with r³ = 216.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'What is the total surface area of a solid hemisphere of radius 7 cm? (Take π = 22/7.)',
      options: ['308 cm²', '462 cm²', '616 cm²', '231 cm²'],
      answer: 1,
      explain: '3πr² = 3 × 22/7 × 49 = 462 cm².',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'How many cubes of side 3 cm can be cut from a cuboid measuring 12 cm × 9 cm × 6 cm?',
      options: ['24', '36', '18', '48'],
      answer: 0,
      explain: '(12 × 9 × 6) ÷ 27 = 648 ÷ 27 = 24. Each edge divides by 3 exactly: 4 × 3 × 2 = 24.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'A sphere of radius 3 cm is dropped into a cylindrical vessel of radius 6 cm that is partly filled with water. By how much does the water level rise?',
      options: ['1 cm', '2 cm', '0.5 cm', '1.5 cm'],
      answer: 0,
      explain: 'Sphere volume = 4/3 π × 27 = 36π. Rise h: π × 36 × h = 36π, so h = 1 cm.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'A frustum of a cone has end radii 10 cm and 4 cm and height 8 cm. What is its volume?',
      options: ['312π cm³', '448π cm³', '416π cm³', '520π cm³'],
      answer: 2,
      explain: '1/3 π × 8 × (100 + 16 + 40) = 1/3 π × 8 × 156 = 416π cm³.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'The surface area of a sphere is 616 cm². What is its volume? (Take π = 22/7.)',
      options: ['1,386 cm³', '718⅔ cm³', '2,874⅔ cm³', '1,437⅓ cm³'],
      answer: 3,
      explain: '4πr² = 616, so r² = 49 and r = 7. V = 4/3 × 22/7 × 343 = 4,312/3 = 1,437⅓ cm³.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'A pyramid has a square base of side 10 cm and a height of 12 cm. What is its lateral surface area?',
      options: ['240 cm²', '260 cm²', '400 cm²', '520 cm²'],
      answer: 1,
      explain: 'Slant height = √(12² + 5²) = 13. Lateral area = 1/2 × 40 × 13 = 260 cm².',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: 'A sector of radius 25 cm and angle 216° is rolled into a cone. What is the volume of the cone?',
      options: ['1,200π cm³', '1,500π cm³', '2,250π cm³', '1,800π cm³'],
      answer: 1,
      explain: 'Arc = 216/360 × 50π = 30π = 2πr, so r = 15. l = 25, so h = 20. V = 1/3 π × 225 × 20 = 1,500π cm³.',
      shortcut: 'r = θ/360 × R = 3/5 × 25 = 15; then 15-20-25 is a triplet.',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: 'The radius of a sphere is increased by 10%. By what percent does its volume increase?',
      options: ['21%', '30%', '33.1%', '10%'],
      answer: 2,
      explain: '1.1³ = 1.331, so the volume rises 33.1%.',
      shortcut: '10% twice = 21%; 21 + 10 + 2.1 = 33.1%.',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: 'A toy is a cone mounted on a hemisphere of the same radius, 7 cm. The total height of the toy is 31 cm. What is its total surface area? (Take π = 22/7.)',
      options: ['858 cm²', '1,012 cm²', '704 cm²', '770 cm²'],
      answer: 0,
      explain: 'Cone height = 31 − 7 = 24, so l = 25. Area = πrl + 2πr² = 22/7 × 7 × (25 + 14) = 22 × 39 = 858 cm².',
      shortcut: 'Take πr out: πr(l + 2r).',
    },
    {
      type: 'truefalse',
      difficulty: 'easy',
      statement: 'The volume of a cone is one third of the volume of a cylinder with the same base and height.',
      answer: true,
      explain: '1/3 πr²h against πr²h.',
    },
    {
      type: 'truefalse',
      difficulty: 'medium',
      statement: 'If every edge of a cube is doubled, its surface area also doubles.',
      answer: false,
      explain: 'Surface area goes with a², so it becomes 4 times. Volume becomes 8 times.',
    },
  ],
};

export default topic;
