import type { Topic } from '@/content/types';

const topic: Topic = {
  id: 'mensuration-2d',
  title: '2D shapes: area and perimeter',
  level: 'intermediate',
  masteryMinutes: 90,
  reviseMinutes: 30,
  priority: 'high',
  weightage: { tier1: 1, tier2: 1.5 },
  tags: ['area', 'perimeter', 'triangle', "Heron's formula", 'circle', 'sector', 'ring', 'rhombus', 'trapezium', 'path', 'wheel'],
  summary:
    'Learn the area formulas cold and the numbers 22/7, 7, 14, 21 and 154. Most questions are one formula plus one Pythagorean triplet or one percentage-change step.',
  patterns: [
    { name: 'Circle, sector, arc and ring (circular path)', frequency: 'most', example: 'A 7 m wide path runs round a circular garden of radius 21 m. Area of the path?' },
    { name: 'Triangles: equilateral, right and Heron\'s formula', frequency: 'most', example: 'Sides are 17 cm, 25 cm and 28 cm. Find the area.' },
    { name: 'Percentage change in area', frequency: 'often', example: 'Length rises 25% and breadth falls 20%. Change in area?' },
    { name: 'Rectangle and square: diagonal, paths and crossing roads', frequency: 'often', example: 'Two 3 m roads cross a 60 m × 40 m park. Area of the roads?' },
    { name: 'Same wire bent into another shape', frequency: 'often', example: 'A wire bent into a square of area 121 cm² is rebent into a circle. Its area?' },
    { name: 'Inradius and circumradius of triangles', frequency: 'often', example: 'Ratio of the circumcircle to the incircle area of an equilateral triangle?' },
    { name: 'Wheel revolutions', frequency: 'rare', example: 'A wheel of radius 35 cm covers 1.1 km. How many revolutions?' },
  ],
  keyPoints: [
    {
      title: 'Triangle and Heron\'s formula',
      text: 'Use 1/2 × base × height when a height is known. With three sides, use Heron\'s formula with the semi-perimeter s. Remember 13, 14, 15 → 84 and any right triangle: half the product of the legs.',
      formula: 'Area = √(s(s − a)(s − b)(s − c)),  s = (a + b + c)/2',
      example: '17, 25, 28: s = 35, √(35 × 18 × 10 × 7) = √44,100 = **210**.',
    },
    {
      title: 'Equilateral triangle',
      text: 'Side a: height √3/2 × a, area √3/4 × a². The inradius is one third of the height and the circumradius two thirds, so R = 2r.',
      formula: 'Area = √3/4 × a²,  r = a/(2√3),  R = a/√3',
      example: 'a = 8√3: area = √3/4 × 192 = **48√3**.',
    },
    {
      title: 'Right triangle radii',
      text: 'In a right triangle the hypotenuse is a diameter of the circumcircle, so R = h/2. The inradius is (p + b − h)/2, where p and b are the legs.',
      formula: 'r = (p + b − h)/2,  R = h/2',
      example: 'Legs 8 and 15, hypotenuse 17: r = (8 + 15 − 17)/2 = **3**, R = 8.5.',
    },
    {
      title: 'Rectangle, square and paths',
      text: 'Rectangle: area lb, perimeter 2(l + b), diagonal √(l² + b²). Square: area a² = d²/2. A path of width w outside: (l + 2w)(b + 2w) − lb. Two crossing roads of width w: w(l + b − w), since the centre square is counted once.',
      formula: 'Crossing roads = w(l + b − w)',
      example: '60 × 40 park, roads 3 m wide: 3 × (60 + 40 − 3) = **291 m²**.',
    },
    {
      title: 'Circle and semicircle',
      text: 'Area πr², circumference 2πr. A semicircle has area 1/2 × πr² and perimeter πr + 2r, which is 36/7 × r with π = 22/7. Circumference 44 means r = 7; 88 means r = 14.',
      formula: 'Area = πr²,  C = 2πr,  semicircle perimeter = 36/7 × r',
      example: 'Circumference 88: r = 14, area = 22/7 × 196 = **616**.',
    },
    {
      title: 'Sector and arc',
      text: 'A sector of angle θ is θ/360 of the circle. Its perimeter is the arc plus two radii. Sector area is also 1/2 × arc × radius. A minute hand sweeps 6° a minute.',
      formula: 'Arc = θ/360 × 2πr,  Area = θ/360 × πr²',
      example: 'r = 21, θ = 72°: 1/5 × 1,386 = **277.2**.',
    },
    {
      title: 'Ring (circular path)',
      text: 'The area between two circles of radii R and r. Factor it: the sum times the difference of the radii.',
      formula: 'Ring area = π(R² − r²) = π(R + r)(R − r)',
      example: 'R = 28, r = 21: 22/7 × 49 × 7 = **1,078**.',
    },
    {
      title: 'Rhombus, trapezium, wheels and % change in area',
      text: 'Rhombus 1/2 × d₁ × d₂. Trapezium 1/2 × (a + b) × h. Revolutions = distance ÷ circumference. If length and breadth change a% and b%, area changes a + b + ab/100 percent; if every side or the radius changes x%, area changes 2x + x²/100 percent.',
      formula: '% change in area = 2x + x²/100',
      example: 'Radius +10%: 20 + 1 = **21%** more area.',
    },
  ],
  comparisons: [
    {
      title: 'Circle vs semicircle vs sector vs ring',
      items: ['Circle', 'Semicircle', 'Sector (angle θ)', 'Ring'],
      rows: [
        { aspect: 'Area', values: ['πr²', '1/2 × πr²', 'θ/360 × πr²', 'π(R² − r²)'], key: true },
        { aspect: 'Perimeter', values: ['2πr', 'πr + 2r', 'θ/360 × 2πr + 2r', '2π(R + r)'] },
        { aspect: 'Example', values: ['r = 7: area 154', 'r = 7: area 77, perimeter 36', 'r = 7, θ = 90°: area 38.5', 'R = 14, r = 7: area 462'] },
      ],
      reveal: 'Each is a fraction of the full circle. The perimeters trip people up: a semicircle and a sector add the straight edges.',
      whenToUse: [
        'Full round field, wheel or plate.',
        'Half-round window or a semicircular end of a track.',
        'A horse tied to a corner, a clock hand, or a pie slice.',
        'A path round a circular garden, or the cross-section of a pipe.',
      ],
    },
    {
      title: 'Inradius vs circumradius',
      items: ['Equilateral triangle (side a)', 'Right triangle (legs p, b, hypotenuse h)', 'Square (side a)'],
      rows: [
        { aspect: 'Inradius r', values: ['a/(2√3)', '(p + b − h)/2', 'a/2'] },
        { aspect: 'Circumradius R', values: ['a/√3', 'h/2', 'a/√2'], key: true },
        { aspect: 'R : r', values: ['2 : 1', 'Depends on sides', '√2 : 1'] },
        { aspect: 'Area of circumcircle : incircle', values: ['4 : 1', 'Depends on sides', '2 : 1'] },
      ],
      reveal: 'For the equilateral triangle R = 2r, so the areas are 4 : 1. For a square the diagonal is the circumcircle\'s diameter and the side is the incircle\'s diameter.',
      whenToUse: [
        'Circle inside or around an equilateral triangle.',
        'Circle inside or around a right triangle.',
        'Circle inside or around a square.',
      ],
    },
  ],
  shortcuts: [
    {
      pattern: 'Percentage change in the area of a circle',
      example: 'The radius of a circle is increased by 10%. By what percent does its area increase?',
      options: ['20%', '21%', '10%', '11%'],
      answer: '21%',
      ladder: [
        { name: 'Standard', steps: ['Take r = 10: area 100π.', 'New r = 11: area 121π.', 'Increase 21π on 100π = 21%.'], seconds: 30 },
        { name: 'Shortcut', steps: ['2x + x²/100 = 20 + 1 = 21%.'], seconds: 5 },
        { name: 'Option elimination', steps: ['Area grows faster than twice the radius change, so above 20%.', 'Only 21% fits.'], seconds: 5 },
      ],
    },
    {
      pattern: 'Area of a scalene triangle from its sides',
      example: 'Find the area of a triangle whose sides are 13 cm, 14 cm and 15 cm.',
      options: ['84 cm²', '72 cm²', '91 cm²', '96 cm²'],
      answer: '84 cm²',
      ladder: [
        { name: 'Standard', steps: ["Heron's formula: s = 21.", '√(21 × 8 × 7 × 6) = √7,056 = 84.'], seconds: 45 },
        { name: 'Shortcut', steps: ['Drop the height 12 on side 14: it splits 14 into 5 + 9.', '5-12-13 and 9-12-15 are triplets, so area = 1/2 × 14 × 12 = 84.'], seconds: 15 },
        { name: 'Memory', steps: ['13-14-15 is a standard triangle: area 84. Worth remembering.'], seconds: 3 },
      ],
    },
    {
      pattern: 'Wheel revolutions',
      example: 'A wheel of radius 35 cm covers a distance of 1.1 km. How many revolutions does it make?',
      options: ['500', '250', '550', '1,000'],
      answer: '500',
      ladder: [
        { name: 'Standard', steps: ['Circumference = 2 × 22/7 × 35 = 220 cm.', '1.1 km = 1,10,000 cm.', '1,10,000 ÷ 220 = 500.'], seconds: 30 },
        { name: 'Shortcut', steps: ['Work in metres: circumference 2.2 m.', '1,100 ÷ 2.2 = 500.'], seconds: 12 },
        { name: 'Option elimination', steps: ['Diameter 0.7 m, so one turn is a little over 2 m.', '1,100 ÷ 2.2 is about 500; 250 and 1,000 are off by a factor of 2.'], seconds: 10 },
      ],
    },
  ],
  qa: [
    {
      q: "State Heron's formula.",
      a: ['Area = √(s(s − a)(s − b)(s − c)).', 's = (a + b + c)/2, the semi-perimeter.'],
      tag: 'Asked often',
    },
    {
      q: 'Area of an equilateral triangle of side a?',
      a: ['√3/4 × a².', 'Height = √3/2 × a.'],
      tag: 'Asked often',
    },
    {
      q: 'If the radius is doubled, what happens to the area?',
      a: ['It becomes 4 times.', 'Area scales with the square of the radius.'],
      tag: 'Trap',
    },
    {
      q: 'Perimeter of a semicircle of radius r?',
      a: ['πr + 2r, not just πr.', 'With π = 22/7 it is 36/7 × r. r = 7 gives 36.'],
      tag: 'Trap',
    },
    {
      q: 'Area of a sector in terms of arc length?',
      a: ['1/2 × arc × radius.', 'Like a triangle with base = arc and height = radius.'],
      tag: 'Shortcut',
    },
    {
      q: 'Area of the path when two roads cross a rectangular park?',
      a: ['w(l + b − w).', 'Subtract w² because the crossing square is counted twice.'],
      tag: 'Trap',
    },
    {
      q: 'Area of a square from its diagonal?',
      a: ['d²/2.', 'Diagonal 16 gives area 128.'],
    },
    {
      q: 'All sides of a square rise by 20%. Change in area?',
      a: ['2x + x²/100 = 40 + 4 = 44% increase.', 'Same rule for the radius of a circle.'],
      tag: 'Shortcut',
    },
    {
      q: 'Inradius of a right triangle with legs p, b and hypotenuse h?',
      a: ['(p + b − h)/2.', 'Legs 6 and 8, hypotenuse 10: r = 2.'],
    },
    {
      q: 'Which radii make π = 22/7 cancel neatly?',
      a: ['Multiples of 7: 7, 14, 21, 28, 35.', 'r = 7: area 154, circumference 44.'],
    },
  ],
  quiz: [
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'What is the area of an equilateral triangle with side 8√3 cm?',
      options: ['48√3 cm²', '64√3 cm²', '36√3 cm²', '24√3 cm²'],
      answer: 0,
      explain: '√3/4 × (8√3)² = √3/4 × 192 = 48√3 cm².',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'The circumference of a circle is 88 cm. What is its area? (Take π = 22/7.)',
      options: ['154 cm²', '616 cm²', '308 cm²', '1,232 cm²'],
      answer: 1,
      explain: '2πr = 88, so r = 14. Area = 22/7 × 196 = 616 cm².',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'A rectangle is 24 cm long and 7 cm wide. What is the length of its diagonal?',
      options: ['26 cm', '24 cm', '25 cm', '31 cm'],
      answer: 2,
      explain: '√(24² + 7²) = √625 = 25 cm.',
      shortcut: '7-24-25 is a triplet.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'The diagonal of a square is 16 cm. What is its area?',
      options: ['256 cm²', '128 cm²', '64 cm²', '112 cm²'],
      answer: 1,
      explain: 'Area = d²/2 = 256/2 = 128 cm².',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'Find the area of a triangle whose sides are 17 cm, 25 cm and 28 cm.',
      options: ['210 cm²', '180 cm²', '240 cm²', '196 cm²'],
      answer: 0,
      explain: 's = 35. Area = √(35 × 18 × 10 × 7) = √44,100 = 210 cm².',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'Find the area of a sector of a circle of radius 21 cm with a central angle of 72°. (Take π = 22/7.)',
      options: ['138.6 cm²', '231 cm²', '277.2 cm²', '554.4 cm²'],
      answer: 2,
      explain: '72/360 = 1/5. Circle area = 22/7 × 441 = 1,386. Sector = 1,386 ÷ 5 = 277.2 cm².',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'A path 7 m wide runs around the outside of a circular garden of radius 21 m. What is the area of the path? (Take π = 22/7.)',
      options: ['924 m²', '1,078 m²', '1,386 m²', '1,232 m²'],
      answer: 1,
      explain: 'Outer radius 28. Area = π(28² − 21²) = 22/7 × 343 = 1,078 m².',
      shortcut: 'π(R + r)(R − r) = 22/7 × 49 × 7 = 1,078.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'The length of a rectangle is increased by 25% and its breadth is decreased by 20%. What is the change in its area?',
      options: ['5% increase', '5% decrease', 'No change', '1% decrease'],
      answer: 2,
      explain: '25 − 20 + (25 × −20)/100 = 25 − 20 − 5 = 0. No change.',
      shortcut: '5/4 × 4/5 = 1.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'The area of a trapezium is 180 cm² and its parallel sides are 16 cm and 20 cm. What is the distance between them?',
      options: ['9 cm', '10 cm', '12 cm', '8 cm'],
      answer: 1,
      explain: '180 = 1/2 × (16 + 20) × h = 18h, so h = 10 cm.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'A rectangular park is 60 m long and 40 m wide. Two roads, each 3 m wide, run through the middle parallel to the sides. What is the total area of the roads?',
      options: ['300 m²', '294 m²', '297 m²', '291 m²'],
      answer: 3,
      explain: 'Roads = 60 × 3 + 40 × 3 − 3 × 3 = 180 + 120 − 9 = 291 m².',
      shortcut: 'w(l + b − w) = 3 × 97 = 291.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'The legs of a right triangle are 8 cm and 15 cm. What is the radius of its incircle?',
      options: ['4 cm', '2.5 cm', '3.5 cm', '3 cm'],
      answer: 3,
      explain: 'Hypotenuse 17. r = (8 + 15 − 17)/2 = 3 cm.',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: 'What is the ratio of the area of the circumcircle to the area of the incircle of an equilateral triangle?',
      options: ['2 : 1', '4 : 1', '3 : 1', '√3 : 1'],
      answer: 1,
      explain: 'R = a/√3 and r = a/(2√3), so R = 2r. Areas go as squares: 4 : 1.',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: 'A wire bent into a square encloses 121 cm². The same wire is bent into a circle. What area does the circle enclose? (Take π = 22/7.)',
      options: ['176 cm²', '132 cm²', '154 cm²', '144 cm²'],
      answer: 2,
      explain: 'Side 11, so the wire is 44 cm. 2πr = 44 gives r = 7. Area = 154 cm².',
      shortcut: 'Wire 44 is the circumference for r = 7, the most common radius.',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: 'Four circles of radius 7 cm are placed so that each touches two others, their centres forming a square. What is the area of the region enclosed between them? (Take π = 22/7.)',
      options: ['42 cm²', '49 cm²', '56 cm²', '35 cm²'],
      answer: 0,
      explain: 'Centres form a square of side 14: area 196. Inside it are four quarter circles = one full circle = 154. Gap = 196 − 154 = 42 cm².',
    },
    {
      type: 'truefalse',
      difficulty: 'easy',
      statement: 'If the radius of a circle is doubled, its area is also doubled.',
      answer: false,
      explain: 'Area goes with r², so it becomes 4 times.',
    },
    {
      type: 'truefalse',
      difficulty: 'medium',
      statement: 'The area of a square is half the square of its diagonal.',
      answer: true,
      explain: 'd = a√2, so d² = 2a² and a² = d²/2.',
    },
  ],
};

export default topic;
