import type { Topic } from '@/content/types';

const topic: Topic = {
  id: 'number-system',
  title: 'Number system',
  level: 'intermediate',
  masteryMinutes: 180,
  reviseMinutes: 60,
  priority: 'high',
  weightage: { tier1: 1, tier2: 2 },
  tags: ['divisibility', 'remainder', 'unit digit', 'factors', 'trailing zeros', 'recurring decimals', 'series'],
  summary:
    'Most questions test one of five tools: divisibility rules, remainders, unit digit cycles, counting factors and trailing zeros. Learn each rule with one example and the chapter becomes quick marks.',
  patterns: [
    { name: 'Missing digit for divisibility', frequency: 'most', example: 'If the 5-digit number x479y is divisible by 72, find x + y.' },
    { name: 'Remainders of large powers and sums', frequency: 'most', example: 'Find the remainder when 2³¹ is divided by 5.' },
    { name: 'Unit digit of a power or product', frequency: 'often', example: 'Find the unit digit of 2137⁷⁵⁴.' },
    { name: 'Number and sum of factors', frequency: 'often', example: 'How many factors does 720 have?' },
    { name: 'Trailing zeros in n!', frequency: 'often', example: 'How many zeros are at the end of 100!?' },
    { name: 'Counting multiples in a range', frequency: 'often', example: 'How many numbers from 100 to 500 are divisible by 7?' },
    { name: 'Recurring decimal to fraction', frequency: 'rare', example: 'Write 0.363636… as a fraction.' },
  ],
  keyPoints: [
    {
      title: 'Divisibility rules',
      text: '**2**: last digit even. **3** and **9**: digit sum divisible by 3 or 9. **4**: last two digits. **8**: last three digits. **5**: ends in 0 or 5. **11**: (sum of odd-place digits) − (sum of even-place digits) is 0 or a multiple of 11. For a composite divisor, split it into co-prime parts: 6 = 2 × 3, 12 = 3 × 4, 72 = 8 × 9, 88 = 8 × 11.',
      formula: '72 = 8 × 9, 88 = 8 × 11 (co-prime parts)',
      example: 'x479y divisible by 72: 8 needs 79y divisible by 8, so y = 2. Then 9 needs x + 22 divisible by 9, so x = 5.',
    },
    {
      title: 'Division and remainders',
      text: 'Every division obeys one line. If a number leaves remainder r with divisor d, and a smaller divisor k divides d, the remainder with k is simply the remainder of r ÷ k.',
      formula: 'Dividend = Divisor × Quotient + Remainder',
      example: 'N leaves 19 when divided by 119. Since 119 = 7 × 17, N leaves 19 − 17 = **2** when divided by 17.',
    },
    {
      title: 'Remainders of powers',
      text: 'The remainder of a product is the product of the remainders. For powers, look for a remainder of 1 or −1. (x + 1)ⁿ ÷ x always leaves 1. (x − 1)ⁿ ÷ x leaves 1 for even n and x − 1 for odd n. Also aⁿ + bⁿ is divisible by a + b when n is odd.',
      formula: '(x + 1)ⁿ ÷ x → remainder 1',
      example: '2⁴ = 16 leaves −1 with 17, so 2⁸ leaves 1 and 2²⁵⁶ = (2⁸)³² leaves **1**.',
    },
    {
      title: 'Unit digit cycles',
      text: 'Digits 0, 1, 5, 6 repeat themselves. 4 and 9 cycle every 2 (odd power keeps the digit). 2, 3, 7 and 8 cycle every 4. Divide the power by 4 and use the remainder; a remainder of 0 means use the 4th power.',
      formula: 'unit digit of aⁿ = unit digit of aʳ, r = n mod 4 (r = 0 → use 4)',
      example: '7⁹⁵: 95 = 4 × 23 + 3, so it ends like 7³ = 343: **3**.',
    },
    {
      title: 'Number and sum of factors',
      text: 'Write N = pᵃ × qᵇ × rᶜ with p, q, r prime. The number of factors is (a + 1)(b + 1)(c + 1). The sum of factors multiplies one geometric sum per prime. Even factors: take at least one 2, so use a instead of a + 1 for the power of 2.',
      formula: 'factors = (a + 1)(b + 1)(c + 1); sum = (pᵃ⁺¹ − 1)/(p − 1) × (qᵇ⁺¹ − 1)/(q − 1)',
      example: '720 = 2⁴ × 3² × 5: 5 × 3 × 2 = **30** factors, of which 4 × 3 × 2 = 24 are even.',
    },
    {
      title: 'Trailing zeros of n!',
      text: 'Each zero needs a 2 and a 5; 5s are fewer, so count the 5s. Keep dividing by 5 and add the whole-number parts.',
      formula: 'zeros = n/5 + n/25 + n/125 + … (whole parts only)',
      example: '100!: 20 + 4 = **24** zeros. 150!: 30 + 6 + 1 = **37**.',
    },
    {
      title: 'Counting multiples and series sums',
      text: 'Multiples of k from 1 to N: the whole part of N ÷ k. Between a and b: count up to b minus count up to a − 1. Sums of the first n natural numbers, squares and cubes come up in series questions.',
      formula: '1 + 2 + … + n = (n(n + 1))/2; squares: (n(n + 1)(2n + 1))/6; cubes: (n²(n + 1)²)/4',
      example: 'Multiples of 7 from 100 to 500: 71 − 14 = **57**.',
    },
    {
      title: 'Recurring decimals',
      text: 'A pure recurring decimal: write the repeating block over as many 9s as it has digits. A mixed one: (all digits − non-repeating digits) over 9s followed by 0s (one 9 per repeating digit, one 0 per non-repeating digit).',
      formula: '0.ababab… = ab/99; 0.abbb… = (ab − a)/90',
      example: '0.3636… = 36/99 = **4/11**. 0.1666… = (16 − 1)/90 = 15/90 = **1/6**.',
    },
  ],
  comparisons: [
    {
      title: 'Unit digit cycles',
      items: ['0, 1, 5, 6', '4 and 9', '2, 3, 7 and 8'],
      rows: [
        { aspect: 'Cycle length', values: ['1', '2', '4'], key: true },
        { aspect: 'Pattern', values: ['Always the same digit', '4 → 6 → 4, 9 → 1 → 9', '2 → 4 → 8 → 6, 3 → 9 → 7 → 1'] },
        { aspect: 'What to check', values: ['Nothing', 'Is the power odd or even?', 'Power mod 4'] },
        { aspect: 'Example', values: ['6¹⁰⁰ ends in 6', '9⁴⁷ ends in 9 (odd)', '7⁹⁵ ends in 3'] },
      ],
      reveal: 'Only the last digit of the base matters. The cycle length decides whether you look at nothing, odd or even, or the remainder on 4.',
      whenToUse: [
        'Answer at once.',
        'Odd power keeps the digit; even power gives 6 (for 4) or 1 (for 9).',
        'Divide the power by 4; remainder 0 means the 4th term of the cycle.',
      ],
    },
    {
      title: '(x + 1)ⁿ vs (x − 1)ⁿ divided by x',
      items: ['(x + 1)ⁿ ÷ x', '(x − 1)ⁿ ÷ x'],
      rows: [
        { aspect: 'Remainder', values: ['Always 1', '1 if n is even, x − 1 if n is odd'], key: true },
        { aspect: 'Example', values: ['17²³ ÷ 16 → 1', '15²³ ÷ 16 → 15'] },
        { aspect: 'Why', values: ['Every term but the last has x in it', 'The last term is (−1)ⁿ'] },
      ],
      reveal: 'Rewrite the base as a multiple of the divisor plus or minus 1. Then only the sign and the parity of n matter.',
      whenToUse: ['Base is one more than the divisor (or a multiple plus 1).', 'Base is one less than the divisor; check whether n is odd.'],
    },
  ],
  shortcuts: [
    {
      pattern: 'Unit digit of a large power',
      example: 'What is the unit digit of 7⁹⁵?',
      options: ['1', '3', '7', '9'],
      answer: '3',
      ladder: [
        {
          name: 'Standard',
          steps: ['Write the powers: 7, 49, 343, 2401, 16807…', 'Unit digits repeat 7, 9, 3, 1.', 'Count 95 terms along the cycle to reach 3.'],
          seconds: 50,
        },
        { name: 'Shortcut', steps: ['95 ÷ 4 leaves 3.', '7³ = 343 ends in 3.'], seconds: 10 },
        {
          name: 'Option elimination',
          steps: ['Odd powers of 7 end in 7 or 3; even powers end in 9 or 1. Drop 1 and 9.', '95 = 4k + 3, the third term of the cycle: 3.'],
          seconds: 8,
        },
      ],
    },
    {
      pattern: 'Trailing zeros in a factorial',
      example: 'How many zeros are at the end of 100!?',
      options: ['20', '24', '25', '22'],
      answer: '24',
      ladder: [
        {
          name: 'Standard',
          steps: ['Count multiples of 5 up to 100: 20.', '25, 50, 75 and 100 each give one extra 5: 4 more.', 'Total 5s = 24, and 2s are plenty.'],
          seconds: 45,
        },
        { name: 'Shortcut', steps: ['100 ÷ 5 = 20, 20 ÷ 5 = 4, 4 ÷ 5 = 0.', '20 + 4 = 24.'], seconds: 10 },
        {
          name: 'Option elimination',
          steps: ['It is at least 20 (multiples of 5) and more because of 25s: drop 20 and 22.', '125 > 100, so no third term: 24, not 25.'],
          seconds: 10,
        },
      ],
    },
    {
      pattern: 'Missing digit for divisibility by 11',
      example: 'The 6-digit number 7x5462 is divisible by 11. Find x.',
      options: ['1', '3', '5', '9'],
      answer: '1',
      ladder: [
        { name: 'Standard', steps: ['Try each option in long division by 11.', 'Only 715462 = 11 × 65042 divides exactly.'], seconds: 90 },
        {
          name: 'Shortcut',
          steps: ['Odd places from the right: 2 + 4 + x = 6 + x.', 'Even places: 6 + 5 + 7 = 18.', '(6 + x) − 18 = x − 12 must be 0 or ±11, so x = 1.'],
          seconds: 20,
        },
        { name: 'Put values', steps: ['Alternate sum with x = 1: 2 − 6 + 4 − 5 + 1 − 7 = −11. Divisible.'], seconds: 15 },
      ],
    },
  ],
  qa: [
    {
      q: 'Rule for divisibility by 11?',
      a: ['Sum of digits in odd places minus sum in even places.', 'The difference must be 0 or a multiple of 11.', '1,21,605: (1 + 1 + 0) − (2 + 6 + 5) = −11, divisible.'],
      tag: 'Asked often',
    },
    {
      q: 'Why can you not test 24 using the rules for 4 and 6?',
      a: ['4 and 6 share the factor 2, so they are not co-prime.', '12 passes both tests but is not divisible by 24.', 'Use co-prime parts: 24 = 3 × 8.'],
      tag: 'Trap',
    },
    {
      q: 'Which digits have a unit digit cycle of 4?',
      a: ['2, 3, 7 and 8.', '4 and 9 cycle every 2; 0, 1, 5, 6 never change.'],
      tag: 'Shortcut',
    },
    {
      q: 'Power ÷ 4 leaves remainder 0. Which unit digit do you take?',
      a: ['The 4th term of the cycle, not the 0th.', '3⁸⁰ ends like 3⁴ = 81: unit digit 1.'],
      tag: 'Trap',
    },
    {
      q: 'Number of factors of N = pᵃ × qᵇ?',
      a: ['(a + 1)(b + 1).', '72 = 2³ × 3²: 4 × 3 = 12 factors.'],
      tag: 'Asked often',
    },
    {
      q: 'How do you count trailing zeros of n!?',
      a: ['Divide n by 5, then by 25, 125… and add the whole parts.', '50!: 10 + 2 = 12 zeros.'],
      tag: 'Asked often',
    },
    {
      q: 'Remainder when 17²³ is divided by 16?',
      a: ['17 = 16 + 1, so 17²³ leaves 1²³ = 1.', 'Any (x + 1)ⁿ ÷ x leaves 1.'],
      tag: 'Shortcut',
    },
    {
      q: 'When is aⁿ + bⁿ divisible by a + b?',
      a: ['When n is odd.', 'aⁿ − bⁿ is divisible by a + b when n is even, and by a − b always.'],
    },
    {
      q: 'Convert 0.1666… to a fraction.',
      a: ['Mixed recurring: (16 − 1)/90.', '15/90 = 1/6.'],
    },
    {
      q: 'Is 1 a prime number? Smallest prime?',
      a: ['1 is neither prime nor composite.', '2 is the smallest prime and the only even prime.'],
      tag: 'Trap',
    },
  ],
  quiz: [
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'What is the unit digit of 7⁹⁵?',
      options: ['1', '3', '7', '9'],
      answer: 1,
      explain: 'Cycle of 7 is 7, 9, 3, 1. 95 ÷ 4 leaves 3, so the digit is the third term: 3.',
      shortcut: 'Power mod 4 = 3 → 7³ = 343.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'Which of these numbers is divisible by 11?',
      options: ['72,359', '48,214', '65,142', '53,916'],
      answer: 2,
      explain: '65142: odd places 2 + 1 + 6 = 9, even places 4 + 5 = 9. Difference 0, so divisible by 11.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'A number leaves remainder 19 when divided by 119. What remainder does it leave when divided by 17?',
      options: ['2', '7', '19', '3'],
      answer: 0,
      explain: '119 = 7 × 17, so the multiple of 119 is also a multiple of 17. Remainder = 19 ÷ 17 → 2.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'How many numbers from 100 to 500 are divisible by 7?',
      options: ['56', '57', '58', '71'],
      answer: 1,
      explain: 'Up to 500: 71 multiples. Up to 99: 14 multiples. 71 − 14 = 57.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'Which fraction equals 0.363636…?',
      options: ['36/100', '9/25', '4/11', '3/11'],
      answer: 2,
      explain: 'Two repeating digits: 36/99 = 4/11.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'How many factors does 720 have?',
      options: ['24', '28', '30', '36'],
      answer: 2,
      explain: '720 = 2⁴ × 3² × 5. Factors = (4 + 1)(2 + 1)(1 + 1) = 30.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'How many zeros are there at the end of 150!?',
      options: ['30', '36', '39', '37'],
      answer: 3,
      explain: '150 ÷ 5 = 30, 150 ÷ 25 = 6, 150 ÷ 125 = 1. Total 37.',
      shortcut: 'Divide by 5 again and again: 30, 6, 1 → 37.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'What is the remainder when 2³¹ is divided by 5?',
      options: ['1', '2', '4', '3'],
      answer: 3,
      explain: 'Remainders of 2ⁿ ÷ 5 cycle 2, 4, 3, 1. 31 ÷ 4 leaves 3, so the remainder is 3.',
      shortcut: 'Remainder with 5 = unit digit rule: 2³¹ ends in 8, and 8 ÷ 5 leaves 3.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'If the 5-digit number x479y is divisible by 72, what is x + y?',
      options: ['7', '9', '11', '6'],
      answer: 0,
      explain: '72 = 8 × 9. For 8: 79y must be divisible by 8, so y = 2 (792 = 8 × 99). For 9: x + 4 + 7 + 9 + 2 = x + 22, so x = 5. x + y = 7.',
      shortcut: 'Always fix the 8-test digit first; it leaves only one or two choices.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'What is the remainder when 15²³ + 23²³ is divided by 19?',
      options: ['4', '0', '1', '15'],
      answer: 1,
      explain: 'For odd n, aⁿ + bⁿ is divisible by a + b = 38 = 2 × 19. So the remainder is 0.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'What is the unit digit of 2137⁷⁵⁴?',
      options: ['1', '3', '7', '9'],
      answer: 3,
      explain: 'Only the last digit 7 matters. 754 ÷ 4 leaves 2, so it ends like 7² = 49: 9.',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: 'What is the sum of all the factors of 72?',
      options: ['195', '180', '168', '210'],
      answer: 0,
      explain: '72 = 2³ × 3². Sum = (1 + 2 + 4 + 8)(1 + 3 + 9) = 15 × 13 = 195.',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: 'What is the remainder when 2²⁵⁶ is divided by 17?',
      options: ['16', '2', '1', '0'],
      answer: 2,
      explain: '2⁴ = 16 leaves −1 with 17, so 2⁸ leaves 1. 2²⁵⁶ = (2⁸)³² leaves 1³² = 1.',
      shortcut: 'Hunt for a power that leaves 1 or −1, then use the exponent rule.',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: 'How many even factors does 720 have?',
      options: ['30', '24', '20', '6'],
      answer: 1,
      explain: '720 = 2⁴ × 3² × 5. An even factor needs at least one 2: 4 choices for the power of 2, then 3 × 2. 4 × 3 × 2 = 24.',
      shortcut: 'Odd factors = 3 × 2 = 6. Even = 30 − 6 = 24.',
    },
    {
      type: 'truefalse',
      difficulty: 'easy',
      statement: 'Every number divisible by both 4 and 6 is divisible by 24.',
      answer: false,
      explain: '12 is divisible by 4 and 6 but not by 24. 4 and 6 are not co-prime; their LCM is 12.',
    },
    {
      type: 'truefalse',
      difficulty: 'medium',
      statement: 'The product of any three consecutive natural numbers is divisible by 6.',
      answer: true,
      explain: 'Among three consecutive numbers one is even and one is a multiple of 3, so 2 × 3 = 6 divides the product.',
    },
  ],
};

export default topic;
