import type { Topic } from '@/content/types';

const topic: Topic = {
  id: 'percentage',
  title: 'Percentage',
  level: 'beginner',
  masteryMinutes: 120,
  reviseMinutes: 40,
  priority: 'high',
  weightage: { tier1: 1, tier2: 1.5 },
  tags: ['percent', 'successive change', 'price consumption', 'population', 'depreciation', 'election', 'percentage points'],
  summary:
    'Percent means "out of 100". Learn the fraction table by heart and most questions become one line: change over base, or two changes multiplied.',
  patterns: [
    { name: 'Successive percentage changes', frequency: 'most', example: 'A price rises 20% and then falls 20%. Net change?' },
    { name: 'Price up, consumption down', frequency: 'most', example: 'Sugar costs 25% more. Cut consumption by how much?' },
    { name: '"More than" vs "less than"', frequency: 'often', example: "A earns 25% more than B. B earns how much less than A?" },
    { name: 'Population growth and depreciation', frequency: 'often', example: 'A machine loses 10% a year. Value after 2 years?' },
    { name: 'Elections and pass marks', frequency: 'often', example: 'Winner gets 60% and wins by 1,200. Total valid votes?' },
    { name: 'Percentage of a percentage', frequency: 'rare', example: '30% of 40% of 500 = ?' },
  ],
  keyPoints: [
    {
      title: 'Fractions you must know as percentages',
      text: '1/2 = 50%, 1/3 = 33⅓%, 1/4 = 25%, 1/5 = 20%, 1/6 = 16⅔%, 1/7 = 14 2/7%, 1/8 = 12.5%, 1/9 = 11 1/9%, 1/11 = 9 1/11%, 1/12 = 8⅓%.',
      example: '37.5% = 3/8, so 37.5% of 640 = 240.',
    },
    {
      title: 'Percentage change is always over the old value',
      text: 'Change as a percentage = (new − old) ÷ old × 100. The base is the value you start from.',
      formula: '% change = (new − old)/old × 100',
      example: '₹20,000 → ₹25,000 is a 5,000/20,000 = **25%** rise.',
    },
    {
      title: 'Two changes in a row',
      text: 'Changes of a% then b% (use a minus sign for a fall) give a net change of a + b + ab/100. It also works for successive discounts and for length × breadth.',
      formula: 'net = a + b + ab/100',
      example: '+20% then −20%: 20 − 20 − 400/100 = **−4%**.',
    },
    {
      title: 'Price up, consumption down',
      text: 'To keep spending the same after a price rise of r%, cut consumption by r/(100 + r) × 100%. After a price fall of r%, you can raise it by r/(100 − r) × 100%.',
      formula: 'cut = r/(100 + r) × 100',
      example: 'Price +25%: cut 25/125 = **20%**. As fractions: up by 1/4 means down by 1/5.',
    },
    {
      title: 'More than vs less than',
      text: 'If A is r% more than B, then B is r/(100 + r) × 100% less than A. The two percentages differ because the bases differ.',
      example: 'A is 25% more than B, so B is 25/125 = **20%** less than A.',
    },
    {
      title: 'Growth and depreciation',
      text: 'A population growing r% a year for n years becomes P(1 + r/100)ⁿ. A value falling r% a year becomes P(1 − r/100)ⁿ. Same formula as compound interest.',
      formula: 'P × (1 ± r/100)ⁿ',
      example: '50,000 at +10% for 2 years: 50,000 × 1.21 = **60,500**.',
    },
    {
      title: 'Elections and pass marks',
      text: 'Turn the gap into a percentage. Winner 60%, loser 40% of valid votes: the 20% gap is the winning margin. A pass mark of 40% means 40% of the maximum marks.',
      example: 'Winning margin 1,200 = 20% of valid votes, so valid votes = **6,000**.',
    },
  ],
  comparisons: [
    {
      title: 'Percentage change vs percentage points',
      items: ['Percentage change', 'Percentage points'],
      rows: [
        { aspect: 'What it measures', values: ['Change relative to the old value', 'Plain difference between two percentages'] },
        { aspect: 'Rate goes 10% → 12%', values: ['(12 − 10)/10 = **20%** rise', '12 − 10 = **2 points**'], key: true },
        { aspect: 'Needs a base', values: ['Yes, the old value', 'No'] },
        { aspect: 'Where you see it', values: ['Price, salary, population changes', 'Interest rates, vote shares, pass rates'] },
      ],
      reveal: 'Both describe the same move from 10% to 12%. Points subtract; percentage change divides by the old rate.',
      whenToUse: [
        'The question asks "by what percent did it increase".',
        'The question compares two rates or shares directly ("by how many percentage points").',
      ],
    },
    {
      title: '"A is r% more than B" vs "B is r% less than A"',
      items: ['A more than B', 'B less than A'],
      rows: [
        { aspect: 'Base', values: ['B', 'A'], key: true },
        { aspect: 'A = 125, B = 100', values: ['25/100 = 25%', '25/125 = 20%'] },
        { aspect: 'Formula from the other', values: ['r/(100 − r) × 100', 'r/(100 + r) × 100'] },
      ],
      reveal: 'The gap is the same 25; only the base changes. "More than B" divides by B, "less than A" divides by A.',
      whenToUse: ['Read the word after "than": that value is the base.', 'Same rule: the value after "than" is the base.'],
    },
  ],
  shortcuts: [
    {
      pattern: 'Price rises, keep spending the same',
      example: 'Sugar costs 25% more. By what percent must a family cut consumption to keep its spending the same?',
      options: ['20%', '25%', '22.5%', '15%'],
      answer: '20%',
      ladder: [
        {
          name: 'Standard',
          steps: [
            'Take price 100, consumption 100: spend 10,000.',
            'New price 125, so consumption = 10,000 ÷ 125 = 80.',
            'Fall from 100 to 80 = 20%.',
          ],
          seconds: 45,
        },
        { name: 'Shortcut', steps: ['r/(100 + r) × 100 = 25/125 × 100 = 20%.'], seconds: 10 },
        { name: 'Fractions', steps: ['25% = 1/4 up, so consumption goes 1/5 down = 20%.'], seconds: 5 },
      ],
    },
    {
      pattern: 'Two successive changes',
      example: 'A price rises 20% and then falls 20%. What is the net change?',
      options: ['No change', '4% decrease', '4% increase', '2% decrease'],
      answer: '4% decrease',
      ladder: [
        { name: 'Standard', steps: ['100 → 120 after the rise.', '120 → 96 after the 20% fall.', 'Net 4 down on 100 = 4% decrease.'], seconds: 30 },
        { name: 'Shortcut', steps: ['a + b + ab/100 = 20 − 20 − 400/100 = −4%.'], seconds: 10 },
        {
          name: 'Option elimination',
          steps: ['Equal rise and fall always ends lower, since the fall is taken on a bigger number.', 'Only "4% decrease" and "2% decrease" survive; the loss is r²/100 = 4%.'],
          seconds: 8,
        },
      ],
    },
    {
      pattern: 'More than, so how much less?',
      example: "A's salary is 25% more than B's. By what percent is B's salary less than A's?",
      options: ['25%', '20%', '30%', '15%'],
      answer: '20%',
      ladder: [
        { name: 'Standard', steps: ['Take B = 100, so A = 125.', 'Gap 25 on base A: 25/125 × 100 = 20%.'], seconds: 30 },
        { name: 'Fractions', steps: ['25% = 1/4 more, so B is 1/(4 + 1) = 1/5 less = 20%.'], seconds: 5 },
      ],
    },
  ],
  qa: [
    {
      q: 'What is the base when a question says "x is 20% more than y"?',
      a: ['y, the value after "than".', 'x = 1.2y.'],
      tag: 'Trap',
    },
    {
      q: 'A number rises 10% and then falls 10%. Is it back where it started?',
      a: ['No, it ends 1% lower.', '10 − 10 − 100/100 = −1%.', 'Equal rise and fall always lose r²/100 percent.'],
      tag: 'Asked often',
    },
    {
      q: 'Formula for a single change equal to a% then b%?',
      a: ['a + b + ab/100, with falls taken as negative.', 'Successive discounts of 20% and 10%: −20 − 10 + 200/100 = −28%, a 28% single discount.'],
      tag: 'Shortcut',
    },
    {
      q: 'Price rises r%. How much must consumption fall to keep spending the same?',
      a: ['r/(100 + r) × 100 percent.', 'Price +20%: cut 20/120 = 16⅔%.'],
      tag: 'Asked often',
    },
    {
      q: 'Price falls r%. How much more can you buy for the same money?',
      a: ['r/(100 − r) × 100 percent.', 'Price −20%: buy 20/80 = 25% more.'],
    },
    {
      q: 'What is the difference between a 2% rise and a 2 percentage point rise?',
      a: ['2% is relative: 10% becomes 10.2%.', '2 percentage points is absolute: 10% becomes 12%.'],
      tag: 'Trap',
    },
    {
      q: 'Write 1/7, 1/9 and 1/11 as percentages.',
      a: ['1/7 = 14 2/7% ≈ 14.29%.', '1/9 = 11 1/9% ≈ 11.11%.', '1/11 = 9 1/11% ≈ 9.09%.'],
    },
    {
      q: 'How do you find the original value after a known percentage change?',
      a: ['Divide the new value by the multiplier.', 'After a 20% rise the value is 1.2 × original, so original = new ÷ 1.2.'],
    },
    {
      q: 'Length rises 20% and breadth falls 10%. What happens to the area?',
      a: ['Area = length × breadth, so use successive change.', '20 − 10 − 200/100 = +8%.'],
      tag: 'Shortcut',
    },
    {
      q: 'In an election question, which total is the base: votes polled or valid votes?',
      a: ['Read carefully: shares are usually of valid votes.', 'Invalid votes are subtracted from the votes polled first.'],
      tag: 'Trap',
    },
  ],
  quiz: [
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'What is 30% of 40% of 500?',
      options: ['60', '50', '120', '90'],
      answer: 0,
      explain: '40% of 500 = 200; 30% of 200 = 60.',
      shortcut: '0.3 × 0.4 = 0.12, and 12% of 500 = 60.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'A salary goes up from ₹20,000 to ₹25,000. What is the percentage increase?',
      options: ['20%', '25%', '30%', '15%'],
      answer: 1,
      explain: 'Increase 5,000 on the old salary 20,000 = 25%.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'If 40% of a number is 72, what is 65% of the number?',
      options: ['108', '117', '126', '130'],
      answer: 1,
      explain: 'Number = 72 ÷ 0.4 = 180. 65% of 180 = 117.',
      shortcut: '1% = 72/40 = 1.8, so 65% = 65 × 1.8 = 117.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'The price of sugar rises by 25%. By what percent must a family reduce its consumption so that its expenditure stays the same?',
      options: ['25%', '20%', '22.5%', '15%'],
      answer: 1,
      explain: '25/(100 + 25) × 100 = 20%.',
      shortcut: 'Up by 1/4 means down by 1/5 = 20%.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: "A's income is 25% more than B's. By what percent is B's income less than A's?",
      options: ['25%', '20%', '30%', '18%'],
      answer: 1,
      explain: 'Take B = 100, A = 125. Gap 25 on base 125 = 20%.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'The price of an item is first raised by 20% and then reduced by 20%. What is the net effect?',
      options: ['No change', '4% increase', '4% decrease', '2% decrease'],
      answer: 2,
      explain: '20 − 20 − (20 × 20)/100 = −4%, a 4% decrease.',
      shortcut: 'Equal rise and fall: loss of r²/100 = 4%.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: "A town's population is 50,000 and grows at 10% a year. What will it be after 2 years?",
      options: ['60,000', '60,500', '61,000', '55,000'],
      answer: 1,
      explain: '50,000 × 1.1 × 1.1 = 60,500.',
      shortcut: 'Two years at 10% = 21% in all (10 + 10 + 1). 21% of 50,000 = 10,500.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'In an election between two candidates, the winner gets 60% of the valid votes and wins by 1,200 votes. How many valid votes were cast?',
      options: ['5,000', '6,000', '7,200', '4,800'],
      answer: 1,
      explain: 'Gap = 60% − 40% = 20% of valid votes = 1,200, so valid votes = 6,000.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'A student needs 40% to pass. She scores 180 marks and fails by 20 marks. What are the maximum marks?',
      options: ['450', '500', '400', '550'],
      answer: 1,
      explain: 'Pass mark = 180 + 20 = 200 = 40% of the maximum, so maximum = 500.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'The length of a rectangle rises by 20% and its breadth falls by 10%. What is the change in its area?',
      options: ['10% increase', '8% increase', '12% increase', '2% decrease'],
      answer: 1,
      explain: '20 − 10 + (20 × −10)/100 = 20 − 10 − 2 = +8%.',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: 'After a 20% cut in the price of petrol, a person can buy 5 litres more for ₹2,000. What was the original price per litre?',
      options: ['₹80', '₹100', '₹120', '₹90'],
      answer: 1,
      explain: 'The 20% saved on ₹2,000 is ₹400, which buys the extra 5 litres, so the new price is ₹80. Original = 80 ÷ 0.8 = ₹100.',
      shortcut: 'Saving ÷ extra quantity gives the new price directly.',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: 'A machine loses 10% of its value every year. After 2 years it is worth ₹81,000. What was it worth at the start?',
      options: ['₹97,200', '₹1,00,000', '₹1,01,250', '₹99,000'],
      answer: 1,
      explain: 'Value = P × 0.9 × 0.9 = 0.81P = 81,000, so P = 1,00,000.',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: 'Two successive discounts of 20% and 10% are equal to a single discount of:',
      options: ['30%', '28%', '27%', '32%'],
      answer: 1,
      explain: '−20 − 10 + (20 × 10)/100 = −28%, a single discount of 28%.',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: 'If A is 125% of B, then B is what percent of A?',
      options: ['75%', '80%', '85%', '125%'],
      answer: 1,
      explain: 'A = 1.25B, so B = A ÷ 1.25 = 0.8A = 80% of A.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'A man saves 25% of his income. His income rises by 20% and his expenditure rises by 10%. By what percent do his savings rise?',
      options: ['30%', '40%', '50%', '45%'],
      answer: 2,
      explain: 'Take income 100: expenditure 75, savings 25. New income 120, new expenditure 75 × 1.1 = 82.5, new savings 120 − 82.5 = 37.5. Rise = 12.5/25 × 100 = 50%.',
      shortcut: 'Savings = income − expenditure. Always work out the new income and new expenditure first, then subtract.',
    },
    {
      type: 'truefalse',
      difficulty: 'easy',
      statement: 'A number increased by 10% and then decreased by 10% returns to its original value.',
      answer: false,
      explain: 'It ends 1% lower: 100 → 110 → 99.',
    },
    {
      type: 'truefalse',
      difficulty: 'medium',
      statement: 'A rate going from 10% to 12% is a rise of 2 percentage points and also a rise of 20%.',
      answer: true,
      explain: '12 − 10 = 2 points; 2/10 × 100 = 20%.',
    },
  ],
};

export default topic;
