import type { Topic } from '@/content/types';

const topic: Topic = {
  id: 'probability',
  title: 'Probability',
  level: 'intermediate',
  masteryMinutes: 60,
  reviseMinutes: 20,
  priority: 'low',
  tiers: ['T2'],
  tags: ['probability', 'coins', 'dice', 'cards', 'balls', 'complement', 'addition rule', 'permutation', 'combination'],
  summary:
    'Probability = favourable outcomes over total outcomes. Know the sample spaces for coins, dice and cards, use "1 − P(none)" for "at least one", and count balls with combinations.',
  patterns: [
    { name: 'Two dice: sum, doublet or product', frequency: 'most', example: 'Two dice are thrown. Probability that the sum is 9?' },
    { name: 'Drawing balls from a bag', frequency: 'often', example: 'Bag has 4 red and 6 black balls. Two drawn. Probability both red?' },
    { name: 'Cards from a pack of 52', frequency: 'often', example: 'One card is drawn. Probability it is a king or a red card?' },
    { name: 'Coins tossed together', frequency: 'often', example: 'Three coins are tossed. Probability of exactly two heads?' },
    { name: '"At least one" by complement', frequency: 'often', example: 'Three balls are drawn. Probability that at least one is green?' },
    { name: 'Calendar and other classics', frequency: 'rare', example: 'Probability that a leap year has 53 Sundays?' },
  ],
  keyPoints: [
    {
      title: 'The basic definition',
      text: 'Count the outcomes that suit you and divide by all equally likely outcomes. A probability always lies between 0 (impossible) and 1 (certain).',
      formula: 'P(E) = (favourable outcomes)/(total outcomes)',
      example: 'One die, a prime number (2, 3, 5): 3/6 = **1/2**.',
    },
    {
      title: 'Complement: the "at least one" tool',
      text: 'P(not E) = 1 − P(E). "At least one" is 1 minus "none", which is usually one short calculation.',
      formula: 'P(at least one) = 1 − P(none)',
      example: 'Three coins, at least one tail: 1 − 1/8 = **7/8**.',
    },
    {
      title: 'Addition rule for "or"',
      text: 'For A or B, add the two and subtract the overlap once. If A and B cannot happen together, the overlap is 0.',
      formula: 'P(A ∪ B) = P(A) + P(B) − P(A ∩ B)',
      example: 'King or red card: 4/52 + 26/52 − 2/52 = 28/52 = **7/13**.',
    },
    {
      title: 'Coins',
      text: 'n coins give 2ⁿ outcomes. Exactly r heads can happen in ⁿCᵣ ways.',
      formula: 'P(exactly r heads) = ⁿCᵣ/2ⁿ',
      example: 'Three coins, exactly two heads: ³C₂/8 = **3/8**.',
    },
    {
      title: 'Dice',
      text: 'One die: 6 outcomes. Two dice: 36. Ways to get a sum s with two dice: s − 1 for s up to 7, and 13 − s for s from 7 to 12. Sum 7 is the most likely (6 ways). There are 6 doublets.',
      formula: 'ways(sum s) = s − 1 (s ≤ 7), 13 − s (s ≥ 7)',
      example: 'Sum 9: 13 − 9 = 4 ways, so 4/36 = **1/9**.',
    },
    {
      title: 'Cards',
      text: '52 cards, 4 suits of 13. Spades and clubs are black, hearts and diamonds red (26 each). 12 face cards (J, Q, K in each suit), 4 aces, 4 of each rank.',
      example: 'A face card: 12/52 = **3/13**.',
    },
    {
      title: 'Balls from a bag',
      text: 'Drawing several balls at once is a combination count. Draw without replacement unless the question says otherwise.',
      formula: 'P = (ways to choose the wanted balls)/(ways to choose any balls)',
      example: '4 red, 6 black, two drawn, both red: ⁴C₂/¹⁰C₂ = 6/45 = **2/15**.',
    },
    {
      title: 'Permutation and combination counts',
      text: 'Arrangements (order matters) use ⁿPᵣ; selections (order does not matter) use ⁿCᵣ. ⁿPᵣ = ⁿCᵣ × r!.',
      formula: 'ⁿPᵣ = (n!)/((n − r)!); ⁿCᵣ = (n!)/(r! × (n − r)!)',
      example: '⁷P₃ = 210 and ⁷C₃ = 35.',
    },
  ],
  comparisons: [
    {
      title: 'Permutation vs combination',
      items: ['Permutation', 'Combination'],
      rows: [
        { aspect: 'Order', values: ['Matters (AB ≠ BA)', 'Does not matter (AB = BA)'], key: true },
        { aspect: 'Formula', values: ['(n!)/((n − r)!)', '(n!)/(r! × (n − r)!)'] },
        { aspect: '3 from 7', values: ['⁷P₃ = 210', '⁷C₃ = 35'] },
        { aspect: 'Key words', values: ['Arrange, order, rank, password', 'Choose, select, committee, draw'] },
      ],
      reveal: 'Every selection of r items can be arranged in r! ways, so ⁿPᵣ = ⁿCᵣ × r!.',
      whenToUse: ['Seating, codes, first and second prizes.', 'Balls drawn from a bag, cards in a hand, a team.'],
    },
    {
      title: 'With replacement vs without replacement',
      items: ['With replacement', 'Without replacement'],
      rows: [
        { aspect: 'Total after the first draw', values: ['Same as before', 'One less'], key: true },
        { aspect: '4 red of 10, two red in a row', values: ['4/10 × 4/10 = 4/25', '4/10 × 3/9 = 2/15'] },
        { aspect: 'Draws independent?', values: ['Yes', 'No'] },
      ],
      reveal: 'Without replacement, both the count of the colour and the total fall by one after each draw.',
      whenToUse: ['The ball is put back before the next draw.', 'Balls are drawn together or not put back (the default).'],
    },
  ],
  shortcuts: [
    {
      pattern: 'Two dice, a given sum',
      example: 'Two dice are thrown. What is the probability that the sum is 9?',
      options: ['1/6', '1/9', '5/36', '1/12'],
      answer: '1/9',
      ladder: [
        { name: 'Standard', steps: ['List pairs: (3, 6), (4, 5), (5, 4), (6, 3).', '4 of 36 outcomes: 4/36 = 1/9.'], seconds: 30 },
        { name: 'Shortcut', steps: ['Sum above 7: ways = 13 − 9 = 4.', '4/36 = 1/9.'], seconds: 8 },
      ],
    },
    {
      pattern: 'At least one',
      example: 'A bag has 5 red and 4 green balls. Three balls are drawn at random. What is the probability that at least one is green?',
      options: ['5/42', '37/42', '10/21', '31/42'],
      answer: '37/42',
      ladder: [
        {
          name: 'Standard',
          steps: ['Add the cases 1, 2 and 3 green: ⁴C₁ × ⁵C₂ + ⁴C₂ × ⁵C₁ + ⁴C₃ = 40 + 30 + 4 = 74.', '74 out of ⁹C₃ = 84: 74/84 = 37/42.'],
          seconds: 75,
        },
        { name: 'Shortcut', steps: ['No green means all three red: ⁵C₃/⁹C₃ = 10/84 = 5/42.', '1 − 5/42 = 37/42.'], seconds: 25 },
        {
          name: 'Option elimination',
          steps: ['5/42 is the "none" case, a trap.', 'At least one of 4 green in 3 draws is very likely, so pick the largest: 37/42.'],
          seconds: 10,
        },
      ],
    },
    {
      pattern: 'Card: A or B',
      example: 'One card is drawn from a pack of 52. What is the probability that it is a king or a red card?',
      options: ['15/26', '7/13', '8/13', '1/2'],
      answer: '7/13',
      ladder: [
        { name: 'Standard', steps: ['Red cards 26, black kings 2 more: 28 favourable.', '28/52 = 7/13.'], seconds: 30 },
        { name: 'Shortcut', steps: ['4/52 + 26/52 − 2/52 (red kings counted twice) = 28/52 = 7/13.'], seconds: 15 },
        { name: 'Option elimination', steps: ['Red alone is 1/2, and kings add a little: must be just above 1/2.', '15/26 (30 cards) forgets the overlap. 7/13 is it.'], seconds: 12 },
      ],
    },
  ],
  qa: [
    {
      q: 'How many outcomes do two dice and three coins have?',
      a: ['Two dice: 6 × 6 = 36.', 'Three coins: 2³ = 8.'],
      tag: 'Asked often',
    },
    {
      q: 'Which sum is most likely with two dice?',
      a: ['7, with 6 ways: probability 1/6.', 'Ways fall by one each side: 6 and 8 have 5 ways.'],
      tag: 'Shortcut',
    },
    {
      q: 'Fastest way to find "at least one"?',
      a: ['1 − P(none).', 'At least one head in 3 coins: 1 − 1/8 = 7/8.'],
      tag: 'Shortcut',
    },
    {
      q: 'How many face cards are in a pack?',
      a: ['12: jack, queen and king of each of 4 suits.', 'Aces are not face cards.'],
      tag: 'Trap',
    },
    {
      q: 'Why subtract in P(king or red)?',
      a: ['The 2 red kings are counted in both groups.', 'Subtract the overlap once: 4 + 26 − 2 = 28.'],
      tag: 'Trap',
    },
    {
      q: 'Probability that a leap year has 53 Sundays?',
      a: ['A leap year has 52 weeks and 2 extra days.', 'Of 7 possible pairs, 2 contain a Sunday: 2/7.'],
      tag: 'Asked often',
    },
    {
      q: 'Can a probability be more than 1 or negative?',
      a: ['No. 0 ≤ P(E) ≤ 1.', 'An option like 7/5 can be struck off at once.'],
    },
    {
      q: 'Permutation or combination for drawing 2 balls from a bag?',
      a: ['Combination. The order of the balls does not matter.', 'Two red from 4 red: ⁴C₂ = 6 ways.'],
    },
    {
      q: 'Relation between ⁿPᵣ and ⁿCᵣ?',
      a: ['ⁿPᵣ = ⁿCᵣ × r!.', '⁷C₃ = 35, so ⁷P₃ = 35 × 6 = 210.'],
    },
    {
      q: 'Two dice: probability that the product is even?',
      a: ['Product is odd only if both are odd: 3/6 × 3/6 = 1/4.', 'Even = 1 − 1/4 = 3/4.'],
      tag: 'Shortcut',
    },
  ],
  quiz: [
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'Two coins are tossed together. What is the probability of getting at least one head?',
      options: ['1/2', '1/4', '3/4', '1'],
      answer: 2,
      explain: 'Outcomes HH, HT, TH, TT. Only TT has no head. 1 − 1/4 = 3/4.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'A die is thrown once. What is the probability of getting a prime number?',
      options: ['1/2', '1/3', '2/3', '1/6'],
      answer: 0,
      explain: 'Primes on a die: 2, 3, 5. 3/6 = 1/2.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'Two dice are thrown together. What is the probability that the sum is 7?',
      options: ['1/9', '5/36', '7/36', '1/6'],
      answer: 3,
      explain: '(1, 6), (2, 5), (3, 4), (4, 3), (5, 2), (6, 1): 6 of 36 = 1/6.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'Two dice are thrown together. What is the probability that the sum is 9?',
      options: ['1/9', '1/12', '5/36', '1/6'],
      answer: 0,
      explain: '(3, 6), (4, 5), (5, 4), (6, 3): 4 of 36 = 1/9.',
      shortcut: 'Sum above 7: 13 − 9 = 4 ways.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'A card is drawn from a well-shuffled pack of 52. What is the probability that it is a king or a red card?',
      options: ['15/26', '1/2', '7/13', '8/13'],
      answer: 2,
      explain: '4/52 + 26/52 − 2/52 = 28/52 = 7/13. The 2 red kings are counted once.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'A card is drawn from a pack of 52. What is the probability that it is a face card?',
      options: ['1/13', '3/13', '4/13', '3/26'],
      answer: 1,
      explain: '12 face cards (J, Q, K of 4 suits). 12/52 = 3/13.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'A bag has 5 red, 3 blue and 2 green balls. One ball is drawn at random. What is the probability that it is blue?',
      options: ['1/3', '3/7', '1/5', '3/10'],
      answer: 3,
      explain: '3 blue out of 10 balls: 3/10.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'A bag has 4 red and 6 black balls. Two balls are drawn at random. What is the probability that both are red?',
      options: ['2/15', '4/25', '2/5', '1/15'],
      answer: 0,
      explain: '⁴C₂/¹⁰C₂ = 6/45 = 2/15.',
      shortcut: 'One after another: 4/10 × 3/9 = 2/15.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'Three coins are tossed. What is the probability of getting exactly two heads?',
      options: ['1/4', '3/8', '1/2', '1/8'],
      answer: 1,
      explain: 'HHT, HTH, THH: 3 of 8 outcomes = 3/8.',
      shortcut: '³C₂/2³ = 3/8.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'Two dice are thrown. What is the probability that the product of the numbers is even?',
      options: ['1/2', '1/4', '2/3', '3/4'],
      answer: 3,
      explain: 'Odd product needs both odd: 9 of 36 = 1/4. Even = 1 − 1/4 = 3/4.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'If P(A) = 0.4, P(B) = 0.5 and P(A and B) = 0.2, what is P(A or B)?',
      options: ['0.9', '0.7', '0.2', '0.5'],
      answer: 1,
      explain: 'P(A or B) = 0.4 + 0.5 − 0.2 = 0.7.',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: 'A bag has 5 red and 4 green balls. Three balls are drawn at random. What is the probability that at least one is green?',
      options: ['5/42', '31/42', '37/42', '10/21'],
      answer: 2,
      explain: 'None green = ⁵C₃/⁹C₃ = 10/84 = 5/42. At least one green = 1 − 5/42 = 37/42.',
      shortcut: 'Use 1 − P(none).',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: 'What is the probability that a leap year, chosen at random, has 53 Sundays?',
      options: ['1/7', '2/7', '3/7', '53/366'],
      answer: 1,
      explain: '366 days = 52 weeks + 2 days. The 2 extra days form one of 7 pairs (Sun-Mon, …, Sat-Sun); 2 contain Sunday. 2/7.',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: 'A number is chosen at random from 1 to 50. What is the probability that it is divisible by 3 or 5?',
      options: ['23/50', '13/25', '9/25', '1/2'],
      answer: 0,
      explain: 'Multiples of 3: 16. Multiples of 5: 10. Multiples of 15 (counted twice): 3. 16 + 10 − 3 = 23, so 23/50.',
      shortcut: 'Addition rule: subtract the overlap (multiples of 15) once.',
    },
    {
      type: 'truefalse',
      difficulty: 'easy',
      statement: 'The probability of an event can be 1.2 if the event is very likely.',
      answer: false,
      explain: 'Every probability lies between 0 and 1. A certain event has probability exactly 1.',
    },
    {
      type: 'truefalse',
      difficulty: 'medium',
      statement: 'The number of ways to choose 3 people from 7 is greater than the number of ways to arrange 3 of 7 people in a row.',
      answer: false,
      explain: '⁷C₃ = 35 but ⁷P₃ = 210. Arranging counts each selection 3! = 6 times.',
    },
  ],
};

export default topic;
