import type { Topic } from '@/content/types';

const topic: Topic = {
  id: 'quadrilaterals',
  title: 'Quadrilaterals and polygons',
  level: 'intermediate',
  masteryMinutes: 60,
  reviseMinutes: 20,
  priority: 'medium',
  tags: ['polygon', 'interior angle', 'exterior angle', 'diagonals', 'parallelogram', 'rhombus', 'trapezium', 'square', 'rectangle'],
  summary:
    'Two facts carry most polygon questions: exterior angles add to 360° and diagonals number n(n − 3)/2. For quadrilaterals, know what each shape\'s diagonals do.',
  patterns: [
    { name: 'Regular polygon: find angle or number of sides', frequency: 'most', example: 'Each exterior angle of a regular polygon is 24°. How many sides?' },
    { name: 'Rhombus: side, diagonals and area', frequency: 'most', example: 'Diagonals of a rhombus are 16 cm and 30 cm. Find its perimeter.' },
    { name: 'Interior to exterior angle ratio or difference', frequency: 'often', example: 'Interior angle is 5 times the exterior angle. Number of sides?' },
    { name: 'Number of diagonals', frequency: 'often', example: 'A polygon has 44 diagonals. How many sides does it have?' },
    { name: 'Parallelogram angles and diagonals', frequency: 'often', example: 'In parallelogram ABCD, ∠A : ∠B = 2 : 3. Find ∠D.' },
    { name: 'Trapezium area and height', frequency: 'often', example: 'Parallel sides 20 cm and 12 cm, height 8 cm. Area?' },
    { name: 'Angle between angle bisectors in a quadrilateral', frequency: 'rare', example: '∠A = 100°, ∠D = 60°. Bisectors of ∠B and ∠C meet at O. Find ∠BOC.' },
  ],
  keyPoints: [
    {
      title: 'Sum of interior angles',
      text: 'A polygon with n sides splits into (n − 2) triangles, so its interior angles add to (n − 2) × 180°. In a regular polygon every interior angle is that sum divided by n.',
      formula: 'Each interior angle = ((n − 2) × 180°)/n',
      example: 'Octagon: 6 × 180° = 1,080°, so each angle = 1,080°/8 = **135°**.',
    },
    {
      title: 'Exterior angles always add to 360°',
      text: 'For any convex polygon the exterior angles sum to 360°. In a regular polygon each exterior angle is 360°/n, and interior + exterior = 180°. This is the fastest way to find n.',
      formula: 'Each exterior angle = 360°/n,  n = 360°/exterior',
      example: 'Exterior angle 24°: n = 360/24 = **15** sides.',
    },
    {
      title: 'Number of diagonals',
      text: 'Each vertex joins to n − 3 others by a diagonal, and each diagonal is counted twice.',
      formula: 'Diagonals = n(n − 3)/2',
      example: 'Decagon: 10 × 7/2 = **35** diagonals. Hexagon: 6 × 3/2 = 9.',
    },
    {
      title: 'Interior : exterior = p : q',
      text: 'Interior and exterior add to 180°, so the exterior angle is 180° × q/(p + q). Then n = 360° ÷ exterior, which simplifies to n = 2(p + q)/q. For a ratio k : 1, n = 2(k + 1).',
      formula: 'n = 2(p + q)/q',
      example: 'Interior = 5 × exterior: n = 2(5 + 1) = **12**.',
    },
    {
      title: 'Parallelogram',
      text: 'Opposite sides and opposite angles are equal. Adjacent angles add to 180°. Diagonals bisect each other but are not equal. Area = base × height. Sides a, b and diagonals d₁, d₂ satisfy the parallelogram law.',
      formula: 'd₁² + d₂² = 2(a² + b²)',
      example: 'Sides 7 and 9, one diagonal 8: d₂² = 2(49 + 81) − 64 = 196, so d₂ = **14**.',
    },
    {
      title: 'Rhombus',
      text: 'All four sides are equal. Diagonals bisect each other at 90°, so half-diagonals and the side make a right triangle. Area is half the product of the diagonals.',
      formula: 'Area = 1/2 × d₁ × d₂,  4a² = d₁² + d₂²',
      example: 'Diagonals 16 and 30: side = √(8² + 15²) = 17, perimeter **68**, area 240.',
    },
    {
      title: 'Rectangle and square',
      text: 'Rectangle diagonals are equal and bisect each other. Square diagonals are equal, perpendicular and bisect the angles. A square\'s diagonal is a√2, so its area is d²/2.',
      formula: 'Square: d = a√2,  Area = d²/2',
      example: 'Square with diagonal 10 cm: area = 100/2 = **50 cm²**.',
    },
    {
      title: 'Trapezium and angle bisectors',
      text: 'Trapezium area = half the sum of parallel sides × the distance between them. The line joining the midpoints of the slant sides is (a + b)/2. In any quadrilateral ABCD, bisectors of ∠B and ∠C meet at an angle of (∠A + ∠D)/2.',
      formula: 'Trapezium area = 1/2 × (a + b) × h',
      example: 'Parallel sides 20 and 12, height 8: 1/2 × 32 × 8 = **128**.',
    },
  ],
  comparisons: [
    {
      title: 'Parallelogram vs rectangle vs rhombus vs square',
      items: ['Parallelogram', 'Rectangle', 'Rhombus', 'Square'],
      rows: [
        { aspect: 'Diagonals', values: ['Bisect each other', 'Equal, bisect each other', 'Perpendicular bisectors', 'Equal and perpendicular bisectors'], key: true },
        { aspect: 'Sides', values: ['Opposite sides equal', 'Opposite sides equal', 'All four equal', 'All four equal'] },
        { aspect: 'Angles', values: ['Opposite angles equal', 'All 90°', 'Opposite angles equal', 'All 90°'] },
        { aspect: 'Area', values: ['base × height', 'l × b', '1/2 × d₁ × d₂', 'a² or d²/2'] },
        { aspect: 'Cyclic?', values: ['No (unless a rectangle)', 'Yes', 'No (unless a square)', 'Yes'] },
      ],
      reveal: 'Every square is a rectangle and a rhombus. Equal diagonals means a rectangle; perpendicular diagonals means a rhombus; both means a square.',
      whenToUse: [
        'Only parallel opposite sides are given: use base × height and the parallelogram law.',
        'Right angles given: use Pythagoras on the diagonal.',
        'Diagonals given: half-diagonals and the side form a right triangle.',
        'Diagonal given: area = d²/2 directly.',
      ],
    },
    {
      title: 'Regular polygon quick table',
      items: ['Pentagon', 'Hexagon', 'Octagon', 'Decagon', 'Dodecagon'],
      rows: [
        { aspect: 'Sides n', values: ['5', '6', '8', '10', '12'] },
        { aspect: 'Each exterior angle', values: ['72°', '60°', '45°', '36°', '30°'], key: true },
        { aspect: 'Each interior angle', values: ['108°', '120°', '135°', '144°', '150°'] },
        { aspect: 'Diagonals', values: ['5', '9', '20', '35', '54'] },
      ],
      reveal: 'Know the exterior column and the rest follows: interior = 180° − exterior.',
      whenToUse: [
        'Interior 108° or exterior 72°.',
        'Interior 120°; a hexagon splits into 6 equilateral triangles.',
        'Interior 135° or exterior 45°.',
        'Interior 144° or exterior 36°.',
        'Interior 150° or exterior 30°.',
      ],
    },
  ],
  shortcuts: [
    {
      pattern: 'Interior angle is k times the exterior angle',
      example: 'Each interior angle of a regular polygon is 4 times its exterior angle. How many sides does it have?',
      options: ['8', '10', '12', '9'],
      answer: '10',
      ladder: [
        { name: 'Standard', steps: ['Let exterior = x, interior = 4x.', '4x + x = 180°, so x = 36°.', 'n = 360/36 = 10.'], seconds: 30 },
        { name: 'Shortcut', steps: ['n = 2(k + 1) = 2 × 5 = 10.'], seconds: 5 },
        { name: 'Option elimination', steps: ['Exterior must be 180/5 = 36°.', 'Only a decagon (10 sides) has a 36° exterior angle.'], seconds: 10 },
      ],
    },
    {
      pattern: 'Sides from the number of diagonals',
      example: 'A polygon has 54 diagonals. How many sides does it have?',
      options: ['9', '10', '12', '11'],
      answer: '12',
      ladder: [
        { name: 'Standard', steps: ['n(n − 3)/2 = 54, so n² − 3n − 108 = 0.', '(n − 12)(n + 9) = 0, so n = 12.'], seconds: 40 },
        { name: 'Shortcut', steps: ['n(n − 3) = 108: find two numbers 3 apart with product 108.', '12 × 9 = 108, so n = 12.'], seconds: 12 },
        { name: 'Put values', steps: ['Try options in n(n − 3)/2: 12 × 9/2 = 54. Done.'], seconds: 10 },
      ],
    },
    {
      pattern: 'Rhombus perimeter from diagonals',
      example: 'The diagonals of a rhombus are 24 cm and 10 cm. What is its perimeter?',
      options: ['52 cm', '68 cm', '48 cm', '56 cm'],
      answer: '52 cm',
      ladder: [
        { name: 'Standard', steps: ['Half-diagonals: 12 and 5.', 'Side = √(144 + 25) = √169 = 13.', 'Perimeter = 4 × 13 = 52 cm.'], seconds: 30 },
        { name: 'Shortcut', steps: ['Perimeter = 2√(d₁² + d₂²) = 2√(576 + 100) = 2 × 26 = 52.'], seconds: 15 },
        { name: 'Triplet', steps: ['12, 5 is the 5-12-13 triplet, so side 13 and perimeter 52.'], seconds: 5 },
      ],
    },
  ],
  qa: [
    {
      q: 'Sum of the exterior angles of a polygon with 20 sides?',
      a: ['360°, the same as any convex polygon.', 'The number of sides does not matter.'],
      tag: 'Trap',
    },
    {
      q: 'How do you find n from one exterior angle?',
      a: ['n = 360° ÷ exterior angle.', 'Exterior 40° gives n = 9.'],
      tag: 'Asked often',
    },
    {
      q: 'How do you find n from one interior angle?',
      a: ['First find exterior = 180° − interior.', 'Then n = 360° ÷ exterior. Interior 150°: exterior 30°, n = 12.'],
      tag: 'Shortcut',
    },
    {
      q: 'Formula for the number of diagonals?',
      a: ['n(n − 3)/2.', 'Pentagon 5, hexagon 9, octagon 20, decagon 35.'],
      tag: 'Asked often',
    },
    {
      q: 'Can a regular polygon have an exterior angle of 25°?',
      a: ['No. 360/25 = 14.4 is not a whole number.', 'The exterior angle must divide 360° exactly.'],
      tag: 'Trap',
    },
    {
      q: 'Which quadrilaterals have perpendicular diagonals?',
      a: ['Rhombus and square (also a kite).', 'Rectangle and parallelogram diagonals are not perpendicular in general.'],
    },
    {
      q: 'How is the side of a rhombus linked to its diagonals?',
      a: ['Half-diagonals and the side form a right triangle.', '4a² = d₁² + d₂².'],
      tag: 'Asked often',
    },
    {
      q: 'State the parallelogram law for diagonals.',
      a: ['d₁² + d₂² = 2(a² + b²).', 'For a rhombus (a = b) it becomes 4a² = d₁² + d₂².'],
    },
    {
      q: 'Bisectors of two adjacent angles of a parallelogram meet at what angle?',
      a: ['90°.', 'Adjacent angles add to 180°, so their halves add to 90°, leaving 90° at the meeting point.'],
      tag: 'Shortcut',
    },
    {
      q: 'Area of a square from its diagonal?',
      a: ['d²/2.', 'A square is a rhombus with equal diagonals: 1/2 × d × d.'],
    },
  ],
  quiz: [
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'What is each interior angle of a regular octagon?',
      options: ['120°', '135°', '140°', '144°'],
      answer: 1,
      explain: 'Exterior = 360/8 = 45°, so interior = 180 − 45 = 135°.',
      shortcut: 'Go through the exterior angle: 180 − 360/n.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'How many diagonals does a decagon have?',
      options: ['45', '40', '30', '35'],
      answer: 3,
      explain: 'n(n − 3)/2 = 10 × 7/2 = 35.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'Each exterior angle of a regular polygon is 24°. How many sides does it have?',
      options: ['12', '18', '15', '20'],
      answer: 2,
      explain: 'n = 360/24 = 15.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'The diagonals of a rhombus are 16 cm and 12 cm. What is its area?',
      options: ['192 cm²', '96 cm²', '48 cm²', '100 cm²'],
      answer: 1,
      explain: 'Area = 1/2 × 16 × 12 = 96 cm².',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'The diagonals of a rhombus are 16 cm and 30 cm. What is its perimeter?',
      options: ['68 cm', '60 cm', '72 cm', '64 cm'],
      answer: 0,
      explain: 'Half-diagonals 8 and 15, so side = √(64 + 225) = 17. Perimeter = 4 × 17 = 68 cm.',
      shortcut: '8-15-17 is a Pythagorean triplet.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'Each interior angle of a regular polygon is 5 times its exterior angle. How many sides does it have?',
      options: ['10', '14', '12', '15'],
      answer: 2,
      explain: 'Exterior = 180/6 = 30°, so n = 360/30 = 12.',
      shortcut: 'n = 2(k + 1) = 2 × 6 = 12.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'In parallelogram ABCD, ∠A : ∠B = 2 : 3. What is ∠D?',
      options: ['72°', '108°', '144°', '54°'],
      answer: 1,
      explain: '∠A + ∠B = 180°, so ∠A = 72° and ∠B = 108°. ∠D is opposite ∠B, so ∠D = 108°.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'The parallel sides of a trapezium are 20 cm and 12 cm, and the distance between them is 8 cm. What is its area?',
      options: ['96 cm²', '144 cm²', '128 cm²', '160 cm²'],
      answer: 2,
      explain: '1/2 × (20 + 12) × 8 = 128 cm².',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'A polygon has 44 diagonals. How many sides does it have?',
      options: ['10', '12', '11', '9'],
      answer: 2,
      explain: 'n(n − 3)/2 = 44, so n(n − 3) = 88 = 11 × 8. n = 11.',
      shortcut: 'Look for two numbers 3 apart whose product is 2 × diagonals.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'The sides of a parallelogram are 7 cm and 9 cm, and one diagonal is 8 cm. What is the other diagonal?',
      options: ['12 cm', '14 cm', '16 cm', '10 cm'],
      answer: 1,
      explain: 'd₁² + d₂² = 2(a² + b²): 64 + d₂² = 2(49 + 81) = 260, so d₂² = 196 and d₂ = 14 cm.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'Each side of a rhombus is 13 cm and one diagonal is 10 cm. What is its area?',
      options: ['130 cm²', '120 cm²', '240 cm²', '60 cm²'],
      answer: 1,
      explain: 'Half of the other diagonal = √(169 − 25) = 12, so it is 24 cm. Area = 1/2 × 10 × 24 = 120 cm².',
      shortcut: '5-12-13 triplet gives the half-diagonal 12 at once.',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: 'The difference between the interior and exterior angles of a regular polygon is 108°. How many sides does it have?',
      options: ['8', '12', '10', '9'],
      answer: 2,
      explain: 'I + E = 180 and I − E = 108, so E = 36°. n = 360/36 = 10.',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: 'In quadrilateral ABCD, ∠A = 100° and ∠D = 60°. The bisectors of ∠B and ∠C meet at O. What is ∠BOC?',
      options: ['80°', '100°', '60°', '70°'],
      answer: 0,
      explain: '∠B + ∠C = 360 − 160 = 200°. ∠BOC = 180 − (∠B + ∠C)/2 = 180 − 100 = 80°.',
      shortcut: '∠BOC = (∠A + ∠D)/2 = 160/2 = 80°.',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: 'The numbers of sides of two regular polygons are in the ratio 5 : 4, and their interior angles differ by 6°. How many sides do they have?',
      options: ['10 and 8', '20 and 16', '25 and 20', '15 and 12'],
      answer: 3,
      explain: 'Interior angles differ as much as exterior angles: 360/(4k) − 360/(5k) = 18/k = 6, so k = 3. Sides 15 and 12.',
      shortcut: 'Check options: 360/12 − 360/15 = 30 − 24 = 6. Done.',
    },
    {
      type: 'truefalse',
      difficulty: 'easy',
      statement: 'The diagonals of a rhombus are always equal.',
      answer: false,
      explain: 'They are perpendicular bisectors, but equal only when the rhombus is a square.',
    },
    {
      type: 'truefalse',
      difficulty: 'medium',
      statement: 'The exterior angles of any convex polygon add up to 360°.',
      answer: true,
      explain: 'Walking round the polygon you turn through one full turn, 360°, whatever the number of sides.',
    },
  ],
};

export default topic;
