import type { Topic } from '@/content/types';

const topic: Topic = {
  id: 'simplification',
  title: 'Simplification, surds and indices',
  level: 'beginner',
  masteryMinutes: 90,
  reviseMinutes: 30,
  priority: 'high',
  weightage: { tier1: 1, tier2: 2 },
  tags: ['BODMAS', 'VBODMAS', 'surds', 'indices', 'exponents', 'rationalising', 'continued fraction', 'nested roots'],
  summary:
    'Follow the order of operations without skipping a step, use the laws of indices to make bases match, and clear roots from a denominator with the conjugate. Speed comes from spotting the pattern, not from long arithmetic.',
  patterns: [
    { name: 'BODMAS with brackets and "of"', frequency: 'most', example: '48 ÷ 12 of 2 + 3 × (8 − 5) = ?' },
    { name: 'Laws of indices and exponent equations', frequency: 'most', example: 'If 3ˣ⁻² = 81, find x.' },
    { name: 'Rationalising and telescoping sums', frequency: 'often', example: '1/(√1 + √2) + 1/(√2 + √3) + … + 1/(√99 + √100) = ?' },
    { name: 'Square root of a + 2√b', frequency: 'often', example: '√(7 + 4√3) = ?' },
    { name: 'Comparing surds of different orders', frequency: 'often', example: 'Which is the largest: √3, ∛4 or ∜6?' },
    { name: 'Continued fractions and nested roots', frequency: 'rare', example: '√(12 + √(12 + √(12 + …))) = ?' },
  ],
  keyPoints: [
    {
      title: 'Order of operations (VBODMAS)',
      text: 'Vinculum (bar) first, then Brackets in the order ( ), { }, [ ], then **Of**, then Division and Multiplication from left to right, then Addition and Subtraction from left to right. "Of" is done before ÷.',
      formula: 'V → B → O → D and M (left to right) → A and S (left to right)',
      example: '48 ÷ 12 of 2 + 3 × (8 − 5) = 48 ÷ 24 + 3 × 3 = 2 + 9 = **11**.',
    },
    {
      title: 'Laws of indices',
      text: 'Same base: add powers when multiplying, subtract when dividing, multiply for a power of a power. Any non-zero number to the power 0 is 1. A negative power flips the number. A fractional power is a root.',
      formula: 'aᵐ × aⁿ = aᵐ⁺ⁿ; aᵐ ÷ aⁿ = aᵐ⁻ⁿ; (aᵐ)ⁿ = aᵐⁿ; a⁰ = 1; a⁻ⁿ = 1/aⁿ',
      example: '27 to the power 2/3 = (∛27)² = **9**. (0.2)⁻² = (1/0.2)² = 5² = **25**.',
    },
    {
      title: 'Exponent equations: make the bases equal',
      text: 'Write both sides as powers of the same prime, then equate the powers. For two unknowns, you get two linear equations.',
      formula: 'aˣ = aʸ → x = y',
      example: '3ˣ⁻² = 81 = 3⁴, so x − 2 = 4 and x = **6**.',
    },
    {
      title: 'Rationalising the denominator',
      text: 'Multiply the top and bottom by the conjugate (change the middle sign). The bottom becomes a − b, a whole number.',
      formula: '1/(√a + √b) = (√a − √b)/(a − b)',
      example: '1/(√3 + √2) = (√3 − √2)/(3 − 2) = **√3 − √2**.',
    },
    {
      title: 'Telescoping sums',
      text: 'Each term 1/(√n + √(n + 1)) rationalises to √(n + 1) − √n. In a chain, every middle term cancels and only the last and first roots remain.',
      formula: 'sum = √(last) − √(first)',
      example: '1/(√1 + √2) + … + 1/(√99 + √100) = √100 − √1 = **9**.',
    },
    {
      title: 'Square root of a + 2√b',
      text: 'Find two numbers x and y with x + y = a and xy = b. Then the root is √x + √y (take x > y for a − 2√b, giving √x − √y). Make the middle term 2√b first.',
      formula: '√(a + 2√b) = √x + √y, where x + y = a and xy = b',
      example: '√(7 + 4√3) = √(7 + 2√12): 4 + 3 = 7 and 4 × 3 = 12, so it is **2 + √3**.',
    },
    {
      title: 'Comparing surds of different orders',
      text: 'Raise every surd to the LCM of the root orders so they all become whole numbers, then compare.',
      formula: 'Compare √a, ∛b, ∜c by raising to the 12th power: a⁶, b⁴, c³',
      example: '√3, ∛4, ∜6 → 3⁶ = 729, 4⁴ = 256, 6³ = 216. So **√3** is the largest.',
    },
    {
      title: 'Nested roots and continued fractions',
      text: 'Infinite √(x + √(x + …)): if x = n(n + 1), the value is n + 1. Infinite √(x √(x √(x …))) = x. A continued fraction is solved from the bottom up.',
      formula: '√(n(n + 1) + √(n(n + 1) + …)) = n + 1',
      example: '√(12 + √(12 + …)) = 4, since 12 = 3 × 4. 1 + 1/(1 + 1/(1 + 1/2)) = **8/5**.',
    },
  ],
  comparisons: [
    {
      title: '"of" vs "÷"',
      items: ['of', '÷'],
      rows: [
        { aspect: 'Priority', values: ['Before ÷ and ×', 'Left to right with ×'] },
        { aspect: '48 ÷ 12 of 2', values: ['12 of 2 = 24 first, then 48 ÷ 24 = **2**', 'Read wrongly as 48 ÷ 12 × 2 = **8**'], key: true },
        { aspect: 'Meaning', values: ['Multiplication that binds tightly', 'Division'] },
      ],
      reveal: '"Of" is a multiplication, but it is done before division. Treating it as a plain × changes the answer.',
      whenToUse: ['Always evaluate "of" as soon as brackets are cleared.', 'Work ÷ and × together from left to right.'],
    },
    {
      title: '√a + √b vs √(a + b)',
      items: ['√a + √b', '√(a + b)'],
      rows: [
        { aspect: 'a = 9, b = 16', values: ['3 + 4 = 7', '√25 = 5'], key: true },
        { aspect: 'Which is bigger', values: ['Always bigger for positive a, b', 'Smaller'] },
        { aspect: 'Rule that does hold', values: ['√a × √b = √(ab)', '√a ÷ √b = √(a/b)'] },
      ],
      reveal: 'Roots split over × and ÷, never over + or −.',
      whenToUse: ['Add only like surds: 2√3 + 5√3 = 7√3.', 'Simplify the sum inside first, then take the root.'],
    },
  ],
  shortcuts: [
    {
      pattern: 'Telescoping sum of reciprocal roots',
      example: 'Find 1/(√1 + √2) + 1/(√2 + √3) + … + 1/(√99 + √100).',
      options: ['9', '10', '11', '99'],
      answer: '9',
      ladder: [
        {
          name: 'Standard',
          steps: ['Rationalise each term: 1/(√n + √(n + 1)) = √(n + 1) − √n.', 'Write out: (√2 − √1) + (√3 − √2) + … + (√100 − √99).', 'Middle terms cancel: √100 − √1 = 9.'],
          seconds: 50,
        },
        { name: 'Shortcut', steps: ['Answer = √(last) − √(first) = √100 − √1 = 9.'], seconds: 8 },
      ],
    },
    {
      pattern: 'Square root of a + 2√b',
      example: 'Find √(7 + 4√3).',
      options: ['3 + √2', '2 + √3', '1 + 2√3', '4 + √3'],
      answer: '2 + √3',
      ladder: [
        {
          name: 'Standard',
          steps: ['Let √(7 + 4√3) = √x + √y. Square: x + y + 2√(xy) = 7 + 4√3.', 'x + y = 7 and 2√(xy) = 4√3, so xy = 12.', 'x = 4, y = 3: answer 2 + √3.'],
          seconds: 50,
        },
        { name: 'Shortcut', steps: ['4√3 = 2√12. Two numbers with sum 7 and product 12: 4 and 3.', '√4 + √3 = 2 + √3.'], seconds: 15 },
        { name: 'Put values', steps: ['Square each option: (2 + √3)² = 4 + 3 + 4√3 = 7 + 4√3. Match.'], seconds: 15 },
      ],
    },
    {
      pattern: 'Largest of surds with different roots',
      example: 'Which is the largest: √3, ∛4 or ∜6?',
      options: ['√3', '∛4', '∜6', 'All equal'],
      answer: '√3',
      ladder: [
        { name: 'Standard', steps: ['Estimate decimals: √3 ≈ 1.732, ∛4 ≈ 1.587, ∜6 ≈ 1.565.', 'Largest: √3.'], seconds: 60 },
        { name: 'Shortcut', steps: ['LCM of 2, 3, 4 = 12. Raise to the 12th power.', '3⁶ = 729, 4⁴ = 256, 6³ = 216.', 'Largest: √3.'], seconds: 20 },
        { name: 'Option elimination', steps: ['√3 is about 1.73; 1.6³ = 4.1 > 4, so ∛4 < 1.6.', '1.6⁴ = 6.55 > 6, so ∜6 < 1.6. √3 wins.'], seconds: 20 },
      ],
    },
  ],
  qa: [
    {
      q: 'What does VBODMAS stand for?',
      a: ['Vinculum, Brackets, Of, Division, Multiplication, Addition, Subtraction.', 'D and M share a level (left to right); so do A and S.'],
      tag: 'Asked often',
    },
    {
      q: 'Is "of" the same as ×?',
      a: ['It means multiply, but it is done before ÷ and ×.', '60 ÷ 5 of 3 = 60 ÷ 15 = 4, not 36.'],
      tag: 'Trap',
    },
    {
      q: 'What is a⁰? What is a⁻ⁿ?',
      a: ['a⁰ = 1 for any non-zero a.', 'a⁻ⁿ = 1/aⁿ.'],
    },
    {
      q: 'How do you solve 2ˣ × 4ʸ = 128?',
      a: ['Change 4 to 2²: 2ˣ⁺²ʸ = 2⁷.', 'So x + 2y = 7.'],
      tag: 'Shortcut',
    },
    {
      q: 'Conjugate of √5 + √3? Why use it?',
      a: ['√5 − √3.', 'Their product is 5 − 3 = 2, a whole number, so the root leaves the denominator.'],
      tag: 'Asked often',
    },
    {
      q: 'Is √9 + √16 equal to √25?',
      a: ['No: 3 + 4 = 7, but √25 = 5.', 'Roots never split over addition.'],
      tag: 'Trap',
    },
    {
      q: 'How do you find √(a + 2√b) quickly?',
      a: ['Find x + y = a and xy = b.', 'The answer is √x + √y.'],
      tag: 'Shortcut',
    },
    {
      q: 'Value of √(20 + √(20 + √(20 + …)))?',
      a: ['20 = 4 × 5, so the value is 5.', 'Check: √(20 + 5) = 5.'],
      tag: 'Shortcut',
    },
    {
      q: 'How do you compare ∛2 and √(1.5)?',
      a: ['Raise both to the 6th power: 2² = 4 and 1.5³ = 3.375.', 'So ∛2 is larger.'],
    },
    {
      q: 'In what order do you solve a continued fraction?',
      a: ['From the bottom line upward.', 'Turn each "1 + 1/x" into one fraction before moving up.'],
    },
  ],
  quiz: [
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'Simplify: 48 ÷ 12 of 2 + 3 × (8 − 5)',
      options: ['17', '11', '21', '15'],
      answer: 1,
      explain: 'Brackets: 8 − 5 = 3. Of: 12 of 2 = 24. Then 48 ÷ 24 = 2 and 3 × 3 = 9. Total 11.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'If 3ˣ⁻² = 81, what is x?',
      options: ['4', '5', '6', '8'],
      answer: 2,
      explain: '81 = 3⁴, so x − 2 = 4 and x = 6.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'What is 1/(√3 + √2) equal to?',
      options: ['√3 − √2', '√3 + √2', '(√3 − √2)/5', '1/√5'],
      answer: 0,
      explain: 'Multiply by √3 − √2 top and bottom: the bottom becomes 3 − 2 = 1.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'What is the value of (0.2)⁻²?',
      options: ['0.04', '4', '5', '25'],
      answer: 3,
      explain: '(0.2)⁻² = (1/0.2)² = 5² = 25.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'Simplify: 0.1 × 0.01 × 0.001 × 10⁷',
      options: ['1', '10', '100', '0.1'],
      answer: 1,
      explain: '0.1 × 0.01 × 0.001 = 10⁻⁶. 10⁻⁶ × 10⁷ = 10¹ = 10.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'What is √(7 + 4√3)?',
      options: ['3 + √2', '1 + 2√3', '2 + √3', '4 + √3'],
      answer: 2,
      explain: '7 + 4√3 = 7 + 2√12. Numbers with sum 7 and product 12: 4 and 3. So √4 + √3 = 2 + √3.',
      shortcut: 'Square the option: (2 + √3)² = 7 + 4√3.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'Find 1/(√2 + √3) + 1/(√3 + √4) + … + 1/(√8 + √9).',
      options: ['3 − √2', '3 + √2', '√2 − 1', '1'],
      answer: 0,
      explain: 'Each term is √(n + 1) − √n. The sum telescopes to √9 − √2 = 3 − √2.',
      shortcut: '√(last) − √(first).',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'Simplify: 1 + 1/(1 + 1/(1 + 1/2))',
      options: ['5/3', '8/5', '13/8', '3/2'],
      answer: 1,
      explain: 'Bottom up: 1 + 1/2 = 3/2. Then 1 + 2/3 = 5/3. Then 1 + 3/5 = 8/5.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'What is the value of √(12 + √(12 + √(12 + …))) (infinitely)?',
      options: ['3', '2√3', '6', '4'],
      answer: 3,
      explain: 'Let the value be y. Then y² = 12 + y, so y² − y − 12 = 0 and y = 4.',
      shortcut: '12 = 3 × 4, so the value is the larger factor: 4.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'Which of these is the smallest: √2, ∛3, ∜5?',
      options: ['√2', '∛3', '∜5', 'All are equal'],
      answer: 0,
      explain: 'Raise to the 12th power: 2⁶ = 64, 3⁴ = 81, 5³ = 125. Smallest is √2.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'Simplify: 18 − [5 − {6 + 2(7 − 8 − 5)}]',
      options: ['7', '29', '−5', '19'],
      answer: 0,
      explain: '7 − 8 − 5 = −6. 2 × (−6) = −12. 6 − 12 = −6. 5 − (−6) = 11. 18 − 11 = 7.',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: 'If x = 3 + 2√2, what is √x + 1/√x?',
      options: ['2', '2√2', '6', '3√2'],
      answer: 1,
      explain: '3 + 2√2 = (√2 + 1)², so √x = √2 + 1 and 1/√x = √2 − 1. Sum = 2√2.',
      shortcut: '(√x + 1/√x)² = x + 1/x + 2 = 6 + 2 = 8, so the answer is √8 = 2√2.',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: 'If 2ˣ × 4ʸ = 128 and 3²ˣ ÷ 9ʸ = 9, what is x + y?',
      options: ['4', '6', '5', '7'],
      answer: 2,
      explain: '2ˣ⁺²ʸ = 2⁷ gives x + 2y = 7. 3²ˣ⁻²ʸ = 3² gives x − y = 1. So y = 2, x = 3, x + y = 5.',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: 'Simplify: (√5 + √3)/(√5 − √3)',
      options: ['8 + √15', '4 − √15', '4 + √15', '2 + √15'],
      answer: 2,
      explain: 'Multiply by √5 + √3 top and bottom: (5 + 3 + 2√15)/(5 − 3) = (8 + 2√15)/2 = 4 + √15.',
    },
    {
      type: 'truefalse',
      difficulty: 'easy',
      statement: '√9 + √16 = √25',
      answer: false,
      explain: '√9 + √16 = 3 + 4 = 7, but √25 = 5. Roots do not split over addition.',
    },
    {
      type: 'truefalse',
      difficulty: 'medium',
      statement: 'The value of 60 ÷ 5 of 3 is 4.',
      answer: true,
      explain: '"Of" comes before ÷: 5 of 3 = 15, and 60 ÷ 15 = 4.',
    },
  ],
};

export default topic;
