import type { Topic } from '@/content/types';

const topic: Topic = {
  id: 'simple-interest',
  title: 'Simple interest',
  level: 'beginner',
  masteryMinutes: 45,
  reviseMinutes: 15,
  priority: 'medium',
  weightage: { tier1: 0.5, tier2: 1 },
  tags: ['simple interest', 'principal', 'rate', 'time', 'amount', 'becomes n times', 'instalments'],
  summary:
    'Simple interest is charged only on the original principal, so it is the same every year. One formula, PRT/100, and the idea that "interest per year is fixed" answer almost every question.',
  patterns: [
    { name: 'Sum becomes n times', frequency: 'most', example: 'A sum doubles in 8 years at SI. In how many years will it become 4 times?' },
    { name: 'Two amounts after two different times', frequency: 'most', example: 'A sum amounts to ₹7,200 in 2 years and ₹8,400 in 4 years. Find the rate.' },
    { name: 'Find principal, rate or time from the formula', frequency: 'often', example: 'At what rate will ₹2,500 earn ₹600 in 4 years?' },
    { name: 'Rate or time changes', frequency: 'often', example: 'Had the rate been 3% higher, the interest for 4 years would be ₹720 more. Find the sum.' },
    { name: 'Sum lent in two parts at different rates', frequency: 'often', example: '₹10,000 is lent partly at 8% and partly at 10%. Yearly interest ₹920. Split?' },
    { name: 'Rate equals time', frequency: 'rare', example: 'SI is 4/9 of the sum and the rate equals the number of years. Find the rate.' },
    { name: 'Equal annual instalments at SI', frequency: 'rare', example: 'What annual instalment clears ₹6,450 due in 4 years at 5% SI?' },
  ],
  keyPoints: [
    {
      title: 'The one formula',
      text: 'Interest is on the original principal P only, at R% a year for T years. Time must be in years: 146 days = 146/365 = 0.4 year, 9 months = 3/4 year.',
      formula: 'SI = (P × R × T)/100',
      example: '₹5,000 at 8% for 3 years: 5,000 × 8 × 3/100 = **₹1,200**.',
    },
    {
      title: 'Amount = principal + interest',
      text: 'The amount is what is paid back at the end. Each year adds the same R% of P, so A = P × (1 + RT/100).',
      formula: 'A = P(1 + RT/100)',
      example: '₹6,000 at 10% for 2 years: 6,000 × 1.2 = **₹7,200**.',
    },
    {
      title: 'Turn the formula around',
      text: 'Any one of P, R and T comes from the other two and SI.',
      formula: 'R = (100 × SI)/(P × T),  T = (100 × SI)/(P × R),  P = (100 × SI)/(R × T)',
      example: '₹2,500 earns ₹600 in 4 years: R = 60,000/10,000 = **6%**.',
    },
    {
      title: 'Sum becomes n times',
      text: 'Becoming n times means the interest is (n − 1) × P. So R × T = (n − 1) × 100. Time is proportional to (n − 1).',
      formula: 'R × T = (n − 1) × 100',
      example: 'Doubles (n − 1 = 1) in 8 years, so 4 times (n − 1 = 3) takes **24 years**. Rate = 100/8 = 12.5%.',
    },
    {
      title: 'Two amounts after two times',
      text: 'The amount grows by the same interest every year. Subtract the two amounts to get the interest for the gap, then go back to year 0.',
      formula: 'SI per year = (A₂ − A₁)/(t₂ − t₁)',
      example: '₹7,200 after 2 years, ₹8,400 after 4: 1,200/2 = 600 a year. P = 7,200 − 1,200 = **₹6,000**, R = 600/6,000 = 10%.',
    },
    {
      title: 'Change in rate or time',
      text: 'Extra interest comes only from the change. If the rate rises by ΔR, the extra interest is P × ΔR × T/100.',
      formula: 'extra SI = (P × ΔR × T)/100',
      example: '3% more for 4 years gives ₹720 more: P = 72,000/12 = **₹6,000**.',
    },
    {
      title: 'Sum split at two rates: use alligation',
      text: 'Alligation is the mixing rule: the further a rate is from the average, the smaller its share. Find the average rate (total interest ÷ total sum × 100). Then lower-rate part : higher-rate part = (higher − average) : (average − lower).',
      example: '₹10,000, ₹920 a year: average 9.2%. At 8% : at 10% = 0.8 : 1.2 = 2 : 3, so **₹4,000** at 8% and ₹6,000 at 10%.',
    },
    {
      title: 'Rate equals time',
      text: 'When R and T are the same number, SI = P × R²/100, so R = √(100 × SI/P).',
      formula: 'R = T = √((100 × SI)/P)',
      example: 'SI = 4/9 of P: R² = 400/9, so R = 20/3 = **6⅔%**.',
    },
  ],
  comparisons: [
    {
      title: 'Becoming n times: SI vs CI',
      items: ['Simple interest', 'Compound interest'],
      rows: [
        { aspect: 'How the sum grows', values: ['Adds the same amount every year', 'Multiplies by the same factor every year'] },
        { aspect: 'Doubles in 5 years, 4 times in', values: ['15 years (3 lots of P)', '10 years (2 × 2)'], key: true },
        { aspect: 'Doubles in 5 years, 8 times in', values: ['35 years (7 lots of P)', '15 years (2 × 2 × 2)'] },
        { aspect: 'Rule', values: ['Time is proportional to n − 1', 'Time is proportional to the number of doublings'] },
      ],
      reveal: 'SI counts how many extra principals are earned (n − 1). CI counts how many doublings happen.',
      whenToUse: ['The question says "at simple interest": count the extra principals.', 'The question says "at compound interest": count the doublings or triplings.'],
    },
  ],
  shortcuts: [
    {
      pattern: 'Sum becomes n times',
      example: 'A sum doubles in 6 years at simple interest. In how many years will it become 5 times?',
      options: ['24 years', '30 years', '18 years', '20 years'],
      answer: '24 years',
      ladder: [
        {
          name: 'Standard',
          steps: ['Doubling: SI = P in 6 years, so R = 100/6 = 16⅔%.', '5 times: SI = 4P.', 'T = (100 × 4)/(50/3) = 24 years.'],
          seconds: 45,
        },
        { name: 'Shortcut', steps: ['Interest of 1P takes 6 years.', 'Interest of 4P takes 4 × 6 = 24 years.'], seconds: 10 },
        { name: 'Option elimination', steps: ['30 years is the trap (5 × 6). The interest needed is 4P, not 5P.', 'Only 24 = 4 × 6 fits.'], seconds: 8 },
      ],
    },
    {
      pattern: 'Two amounts after two times',
      example: 'A sum amounts to ₹7,200 in 2 years and to ₹8,400 in 4 years at simple interest. Find the rate.',
      options: ['10%', '12%', '8%', '15%'],
      answer: '10%',
      ladder: [
        {
          name: 'Standard',
          steps: ['P + 2I = 7,200 and P + 4I = 8,400, where I is the yearly interest.', 'Subtract: 2I = 1,200, so I = 600 and P = 6,000.', 'R = 600/6,000 × 100 = 10%.'],
          seconds: 50,
        },
        { name: 'Shortcut', steps: ['2 years of SI = 8,400 − 7,200 = 1,200.', 'P = 7,200 − 1,200 = 6,000; R = 600/6,000 = 10%.'], seconds: 20 },
        { name: 'Put values', steps: ['Try 10%: 2 years gives 1.2P = 7,200, so P = 6,000.', '4 years gives 1.4 × 6,000 = 8,400. It fits.'], seconds: 20 },
      ],
    },
    {
      pattern: 'Sum lent in two parts at two rates',
      example: '₹10,000 is lent partly at 8% and the rest at 10% simple interest. The total interest for one year is ₹920. How much was lent at 8%?',
      options: ['₹4,000', '₹6,000', '₹5,000', '₹4,500'],
      answer: '₹4,000',
      ladder: [
        {
          name: 'Standard',
          steps: ['Let x be at 8%: 0.08x + 0.10(10,000 − x) = 920.', '1,000 − 0.02x = 920, so x = 4,000.'],
          seconds: 45,
        },
        {
          name: 'Shortcut',
          steps: ['Average rate = 920/10,000 = 9.2%.', 'Alligation: 8% part : 10% part = (10 − 9.2) : (9.2 − 8) = 2 : 3.', '2/5 × 10,000 = ₹4,000.'],
          seconds: 20,
        },
        { name: 'Option elimination', steps: ['9.2% is nearer 10% than 8%, so less than half is at 8%.', 'Only ₹4,000 and ₹4,500 are below ₹5,000; 4,000 × 8% + 6,000 × 10% = 920.'], seconds: 15 },
      ],
    },
  ],
  qa: [
    {
      q: 'Why is simple interest the same every year?',
      a: ['It is always taken on the original principal.', 'Interest earned is never added to the principal.'],
    },
    {
      q: 'A sum doubles in t years at SI. When does it become 3 times and 4 times?',
      a: ['3 times needs 2P of interest: 2t years.', '4 times needs 3P of interest: 3t years.'],
      tag: 'Asked often',
    },
    {
      q: 'A sum doubles in 5 years at SI. Someone answers "4 times in 10 years". What went wrong?',
      a: ['That is the CI rule.', 'At SI, 4 times needs 3P of interest, so 15 years.'],
      tag: 'Trap',
    },
    {
      q: 'How do you find P from two amounts at two times?',
      a: ['Difference of amounts ÷ difference of years = SI per year.', 'P = first amount − (its years × SI per year).'],
      tag: 'Shortcut',
    },
    {
      q: 'How do you convert days and months into years for SI?',
      a: ['Days: divide by 365 (73 days = 1/5 year, 146 days = 2/5 year).', 'Months: divide by 12 (9 months = 3/4 year).'],
      tag: 'Trap',
    },
    {
      q: 'The rate rises by 2% and the interest for 3 years goes up by ₹360. What is the sum?',
      a: ['Extra SI = P × 2 × 3/100 = 360.', 'P = 36,000/6 = ₹6,000.'],
    },
    {
      q: 'What is the quick way to split a sum lent at two rates?',
      a: ['Average rate = total interest ÷ total sum × 100.', 'Parts are (high − average) : (average − low), as in alligation.'],
      tag: 'Shortcut',
    },
    {
      q: 'When the rate and the time are the same number, how do you find it?',
      a: ['SI = P × R²/100.', 'So R = √(100 × SI/P).'],
    },
    {
      q: 'What is the relation between R and T when a sum becomes n times?',
      a: ['R × T = (n − 1) × 100.', 'Doubles in 8 years: R = 100/8 = 12.5%.'],
      tag: 'Asked often',
    },
    {
      q: 'How does an equal annual instalment work at simple interest?',
      a: [
        'Each instalment x earns SI from the day it is paid until the end.',
        'For n instalments: debt = nx + x × R × (0 + 1 + … + (n − 1))/100.',
        '₹6,450 in 4 years at 5%: 4x + 0.3x = 4.3x, so x = ₹1,500.',
      ],
    },
  ],
  quiz: [
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'Find the simple interest on ₹8,000 at 6% per annum for 3 years.',
      options: ['₹1,240', '₹1,440', '₹1,540', '₹1,600'],
      answer: 1,
      explain: 'SI = 8,000 × 6 × 3/100 = ₹1,440.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'At what rate per annum will ₹2,500 earn a simple interest of ₹600 in 4 years?',
      options: ['5%', '8%', '7.5%', '6%'],
      answer: 3,
      explain: 'R = (100 × 600)/(2,500 × 4) = 60,000/10,000 = 6%.',
      shortcut: 'Interest per year = 150, which is 6% of 2,500.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'A sum of money doubles itself in 10 years at simple interest. What is the rate of interest?',
      options: ['8%', '12%', '10%', '5%'],
      answer: 2,
      explain: 'Doubling means SI = P. So R × 10 = 100 and R = 10%.',
      shortcut: 'R × T = (n − 1) × 100 = 100.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'Find the simple interest on ₹12,000 at 10% per annum for 146 days.',
      options: ['₹480', '₹438', '₹500', '₹520'],
      answer: 0,
      explain: '146 days = 146/365 = 2/5 year. SI = 12,000 × 10 × 2/5 ÷ 100 = ₹480.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'A sum amounts to ₹9,440 in 3 years and to ₹10,400 in 5 years at simple interest. Find the sum.',
      options: ['₹7,800', '₹8,000', '₹8,200', '₹8,400'],
      answer: 1,
      explain: '2 years of SI = 10,400 − 9,440 = 960, so 480 a year. P = 9,440 − 3 × 480 = ₹8,000.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'A sum becomes 3 times itself in 12 years at simple interest. In how many years will it become 7 times itself?',
      options: ['28 years', '42 years', '30 years', '36 years'],
      answer: 3,
      explain: '3 times means SI = 2P in 12 years, so P of interest takes 6 years. 7 times needs 6P: 36 years.',
      shortcut: 'Time ∝ (n − 1): 12 × 6/2 = 36.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'Had the rate of simple interest been 3% higher, the interest on a sum for 4 years would have been ₹720 more. Find the sum.',
      options: ['₹6,000', '₹5,000', '₹7,200', '₹4,800'],
      answer: 0,
      explain: 'Extra SI = P × 3 × 4/100 = 720, so P = 72,000/12 = ₹6,000.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: '₹15,000 is lent in two parts, one at 6% and the other at 10% simple interest. The total interest for one year is ₹1,260. How much was lent at 10%?',
      options: ['₹6,000', '₹8,000', '₹9,000', '₹7,500'],
      answer: 2,
      explain: 'Average rate = 1,260/15,000 = 8.4%. 6% part : 10% part = (10 − 8.4) : (8.4 − 6) = 2 : 3. So 3/5 × 15,000 = ₹9,000 at 10%.',
      shortcut: 'Check: 6,000 × 6% + 9,000 × 10% = 360 + 900 = 1,260.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'The simple interest on a sum is 4/9 of the sum, and the rate percent equals the number of years. Find the rate.',
      options: ['5%', '7½%', '8%', '6⅔%'],
      answer: 3,
      explain: 'SI = P × R²/100 = 4P/9, so R² = 400/9 and R = 20/3 = 6⅔%.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'A sum lent at 5% per annum simple interest amounts to ₹6,000 in 4 years. Find the sum.',
      options: ['₹4,800', '₹5,000', '₹5,200', '₹5,500'],
      answer: 1,
      explain: 'A = P × (1 + 5 × 4/100) = 1.2P = 6,000, so P = ₹5,000.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'A borrows ₹20,000 at 6% simple interest for the first 2 years, 8% for the next 3 years and 10% after that. How much interest does he pay for 7 years?',
      options: ['₹10,800', '₹11,200', '₹12,000', '₹11,600'],
      answer: 1,
      explain: 'Total rate-years = 6 × 2 + 8 × 3 + 10 × 2 = 56. SI = 20,000 × 56/100 = ₹11,200.',
      shortcut: 'Add the rate-years first, then take that percent once.',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: 'The simple interest on a sum for 5 years at 7% exceeds the simple interest on the same sum for 3 years at 9% by ₹1,600. Find the sum.',
      options: ['₹16,000', '₹18,000', '₹20,000', '₹25,000'],
      answer: 2,
      explain: '5 × 7 = 35% and 3 × 9 = 27%. The gap 8% of P = 1,600, so P = ₹20,000.',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: '₹8,100 is divided into two parts so that the amount of the first part after 2 years equals the amount of the second part after 5 years, both at 10% simple interest. Find the first part.',
      options: ['₹3,600', '₹4,050', '₹4,500', '₹4,800'],
      answer: 2,
      explain: 'First × 1.2 = second × 1.5, so first : second = 1.5 : 1.2 = 5 : 4. First = 5/9 × 8,100 = ₹4,500.',
      shortcut: 'Parts are in the inverse ratio of their multipliers (1 + RT/100).',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: 'What equal annual instalment will discharge a debt of ₹6,450 due in 4 years at 5% simple interest?',
      options: ['₹1,500', '₹1,550', '₹1,600', '₹1,450'],
      answer: 0,
      explain: 'Instalments earn interest for 3, 2, 1 and 0 years. 4x + x × 5 × 6/100 = 4.3x = 6,450, so x = ₹1,500.',
    },
    {
      type: 'truefalse',
      difficulty: 'easy',
      statement: 'Under simple interest, the interest earned is the same every year.',
      answer: true,
      explain: 'It is always R% of the original principal.',
    },
    {
      type: 'truefalse',
      difficulty: 'medium',
      statement: 'If a sum doubles in 5 years at simple interest, it becomes 4 times in 10 years.',
      answer: false,
      explain: '4 times needs 3P of interest, which takes 3 × 5 = 15 years.',
    },
  ],
};

export default topic;
