import type { Topic } from '@/content/types';

const topic: Topic = {
  id: 'triangles',
  title: 'Triangles',
  level: 'advanced',
  masteryMinutes: 180,
  reviseMinutes: 60,
  priority: 'high',
  weightage: { tier1: 1.5, tier2: 2 },
  tags: ['centroid', 'incentre', 'circumcentre', 'orthocentre', 'similar triangles', 'congruence', 'angle bisector theorem', 'Apollonius', 'Pythagorean triplets', 'equilateral triangle', 'Heron'],
  summary:
    'Four centres, similar triangles and a handful of right-triangle facts carry most of the marks. Learn each centre with its one angle formula and you can answer in seconds.',
  patterns: [
    { name: 'Angle at the incentre, orthocentre or circumcentre', frequency: 'most', example: 'I is the incentre of △ABC and ∠A = 70°. Find ∠BIC.' },
    { name: 'Similar triangles: BPT and area ratios', frequency: 'most', example: 'DE ∥ BC and AD : DB = 2 : 3. Find area △ADE : area DECB.' },
    { name: 'Equilateral triangle: height, area, inradius, circumradius', frequency: 'often', example: 'Side 12 cm. Find the circumradius.' },
    { name: 'Medians and centroid (Apollonius, area split)', frequency: 'often', example: 'AB = 7, AC = 9, BC = 8. Find the median AD.' },
    { name: 'Right triangles and Pythagorean triplets', frequency: 'often', example: 'Legs 9 and 12. Find the inradius.' },
    { name: 'Angle bisector theorem', frequency: 'often', example: 'AB = 6, AC = 9, BC = 10. The bisector of ∠A meets BC at D. Find BD.' },
    { name: 'Angle sum, exterior angle and side rules', frequency: 'rare', example: 'Sides 7, 8 and 12. Acute, right or obtuse?' },
  ],
  keyPoints: [
    {
      title: 'Angles and sides',
      text: 'Angles add to 180°. An exterior angle equals the sum of the two interior opposite angles. The larger side faces the larger angle. Any side is less than the sum and more than the difference of the other two. With c the longest side: c² < a² + b² acute, = right, > obtuse.',
      formula: '|b − c| < a < b + c',
      example: 'Sides 7, 8, 12: 49 + 64 = 113 < 144, so the triangle is **obtuse**.',
    },
    {
      title: 'Congruence and similarity tests',
      text: 'Congruent (same shape and size): SSS, SAS, ASA, AAS, RHS. Similar (same shape): AA, SSS in the same ratio, SAS with the included angle equal. AAA proves similarity only, never congruence.',
      example: 'Two triangles with angles 50°, 60°, 70° are similar, not necessarily congruent.',
    },
    {
      title: 'Similar triangles and the basic proportionality theorem',
      text: 'If DE ∥ BC in △ABC, then AD/DB = AE/EC and △ADE ~ △ABC. In similar triangles, sides, heights, medians and perimeters are in ratio k, and areas are in ratio k².',
      formula: 'area₁/area₂ = (side₁/side₂)²',
      example: 'AD : DB = 2 : 3 gives AD : AB = 2 : 5, areas 4 : 25, so △ADE : DECB = **4 : 21**.',
    },
    {
      title: 'Right triangles and triplets',
      text: 'Know the triplets 3-4-5, 5-12-13, 8-15-17, 7-24-25, 20-21-29, 9-40-41, 12-35-37, 11-60-61 and their multiples. For legs a, b and hypotenuse c: altitude to the hypotenuse = ab/c, inradius = (a + b − c)/2, circumradius = c/2.',
      formula: 'r = (a + b − c)/2; R = c/2; altitude = ab/c',
      example: 'Legs 9 and 12: c = 15, r = (9 + 12 − 15)/2 = **3**, R = **7.5**.',
    },
    {
      title: 'The four centres and their angle formulas',
      text: 'Centroid G: medians meet. Incentre I: angle bisectors meet. Circumcentre O: perpendicular bisectors of the sides meet. Orthocentre H: altitudes meet. The excentre opposite A gives 90° − A/2.',
      formula: '∠BIC = 90° + A/2; ∠BOC = 2A (acute); ∠BHC = 180° − A',
      example: '∠A = 70°: ∠BIC = **125°**, ∠BOC = **140°**, ∠BHC = **110°**.',
    },
    {
      title: 'Medians, centroid and Apollonius',
      text: 'The centroid divides each median 2 : 1 from the vertex. The three medians cut the triangle into 6 equal areas. For median AD: AB² + AC² = 2(AD² + BD²). The squares of the medians add to 3/4 of the squares of the sides.',
      formula: 'AD² = (2b² + 2c² − a²)/4',
      example: 'AB = 7, AC = 9, BC = 8: AD² = (98 + 162 − 64)/4 = 49, so AD = **7**.',
    },
    {
      title: 'Angle bisector theorem',
      text: 'The bisector of ∠A cuts BC in the ratio of the other two sides. So BD = a × c/(b + c).',
      formula: 'BD/DC = AB/AC',
      example: 'AB = 6, AC = 9, BC = 10: BD = 10 × 6/15 = **4**.',
    },
    {
      title: 'Area formulas and the equilateral triangle',
      text: 'Area = 1/2 × base × height. Heron: area = √(s(s − a)(s − b)(s − c)) with s the half-perimeter. Inradius r = (area)/s, circumradius R = abc/(4 × area). Equilateral triangle of side a: height √3/2 × a, area √3/4 × a², R = a/√3, r = a/(2√3), so R = 2r. All four centres coincide.',
      formula: 'Equilateral: area = √3/4 × a², R = a/√3, r = a/(2√3)',
      example: 'Sides 13, 14, 15: s = 21, area = √(21 × 8 × 7 × 6) = **84**.',
    },
  ],
  comparisons: [
    {
      title: 'Centroid vs incentre vs circumcentre vs orthocentre',
      items: ['Centroid (G)', 'Incentre (I)', 'Circumcentre (O)', 'Orthocentre (H)'],
      rows: [
        { aspect: 'Meeting point of', values: ['Medians', 'Angle bisectors', 'Perpendicular bisectors of sides', 'Altitudes'] },
        { aspect: 'Angle at the centre', values: ['No simple rule', '∠BIC = 90° + A/2', '∠BOC = 2A', '∠BHC = 180° − A'], key: true },
        { aspect: 'Special property', values: ['Divides each median 2 : 1', 'Equidistant from the sides (r)', 'Equidistant from the vertices (R)', 'Vertex of the right angle in a right triangle'] },
        { aspect: 'Position', values: ['Always inside', 'Always inside', 'Inside if acute, midpoint of hypotenuse if right, outside if obtuse', 'Inside if acute, at the right-angle vertex if right, outside if obtuse'] },
        { aspect: '∠A = 60°', values: ['Not asked', '120°', '120°', '120°'] },
      ],
      reveal: 'Each centre has its own angle formula. At ∠A = 60° the last three all give 120°, which is why that value is a favourite trap.',
      whenToUse: [
        'The question mentions medians or divides a median.',
        'The question mentions angle bisectors or an inscribed circle.',
        'The question mentions a circle through all three vertices.',
        'The question mentions altitudes or perpendiculars from the vertices.',
      ],
    },
    {
      title: 'Congruent vs similar triangles',
      items: ['Congruent (≅)', 'Similar (~)'],
      rows: [
        { aspect: 'Same', values: ['Shape and size', 'Shape only'] },
        { aspect: 'Tests', values: ['SSS, SAS, ASA, AAS, RHS', 'AA, SSS ratio, SAS ratio'] },
        { aspect: 'Does AAA work?', values: ['No', 'Yes'] },
        { aspect: 'Ratio of areas', values: ['1 : 1', 'k² : 1 for sides k : 1'], key: true },
      ],
      reveal: 'Similar triangles scale every length by k but the area by k². Congruent is the case k = 1.',
      whenToUse: ['Proving two parts are equal in length.', 'Any parallel line inside a triangle, or a ratio of sides or areas.'],
    },
  ],
  shortcuts: [
    {
      pattern: 'Angle at the incentre',
      example: 'I is the incentre of △ABC and ∠A = 70°. Find ∠BIC.',
      options: ['110°', '125°', '140°', '145°'],
      answer: '125°',
      ladder: [
        { name: 'Standard', steps: ['∠B + ∠C = 180 − 70 = 110°.', '∠IBC + ∠ICB = 110/2 = 55°.', '∠BIC = 180 − 55 = 125°.'], seconds: 30 },
        { name: 'Option elimination', steps: ['∠BIC is always more than 90° and less than 180°.', '140 is 2A (circumcentre) and 110 is 180 − A (orthocentre). 125 is left.'], seconds: 8 },
        { name: 'Shortcut', steps: ['90° + A/2 = 90 + 35 = 125°.'], seconds: 5 },
      ],
    },
    {
      pattern: 'Parallel line cuts a triangle: area ratio',
      example: 'In △ABC, DE ∥ BC with D on AB and E on AC. If AD : DB = 2 : 3, find area △ADE : area of trapezium DECB.',
      options: ['4 : 25', '2 : 3', '4 : 9', '4 : 21'],
      answer: '4 : 21',
      ladder: [
        { name: 'Standard', steps: ['△ADE ~ △ABC with AD : AB = 2 : 5.', 'Areas 4 : 25.', 'Trapezium = 25 − 4 = 21, so the ratio is 4 : 21.'], seconds: 35 },
        { name: 'Shortcut', steps: ['Square the small part over the whole: 2² : 5² = 4 : 25.', 'Subtract: 4 : 21.'], seconds: 12 },
        { name: 'Option elimination', steps: ['4 : 25 compares with the whole triangle, not the trapezium.', '4 : 9 squares the wrong ratio. Only 4 : 21 is left.'], seconds: 8 },
      ],
    },
    {
      pattern: 'Equilateral triangle radius',
      example: 'Find the circumradius of an equilateral triangle of side 12 cm.',
      options: ['2√3 cm', '4√3 cm', '6√3 cm', '8 cm'],
      answer: '4√3 cm',
      ladder: [
        { name: 'Standard', steps: ['Height = √3/2 × 12 = 6√3.', 'The circumcentre is the centroid, 2/3 of the way down.', 'R = 2/3 × 6√3 = 4√3 cm.'], seconds: 35 },
        { name: 'Option elimination', steps: ['R is less than the height 6√3 ≈ 10.4, which rules out 6√3.', 'R = 2r and r = 2√3, so 4√3.'], seconds: 10 },
        { name: 'Shortcut', steps: ['R = a/√3 = 12/√3 = 4√3 cm.'], seconds: 8 },
      ],
    },
  ],
  qa: [
    {
      q: 'Angle formulas at the incentre, circumcentre and orthocentre?',
      a: ['∠BIC = 90° + A/2.', '∠BOC = 2A (acute triangle).', '∠BHC = 180° − A.'],
      tag: 'Asked often',
    },
    {
      q: 'In what ratio does the centroid divide a median?',
      a: ['2 : 1, the longer part next to the vertex.', 'So AG = 2/3 of the median AD.'],
      tag: 'Asked often',
    },
    {
      q: 'Where is the circumcentre of a right triangle?',
      a: ['At the midpoint of the hypotenuse.', 'So R = hypotenuse/2.'],
      tag: 'Shortcut',
    },
    {
      q: 'Where is the orthocentre of a right triangle?',
      a: ['At the vertex with the right angle.', 'The two legs are already altitudes.'],
      tag: 'Trap',
    },
    {
      q: 'Two similar triangles have sides in ratio 2 : 3. Ratio of areas?',
      a: ['4 : 9, the square of the side ratio.', 'Perimeters, heights and medians stay 2 : 3.'],
      tag: 'Trap',
    },
    {
      q: 'State the angle bisector theorem.',
      a: ['The bisector of ∠A meets BC at D with BD/DC = AB/AC.', 'BD = a × c/(b + c).'],
    },
    {
      q: 'State Apollonius theorem.',
      a: ['For median AD: AB² + AC² = 2(AD² + BD²).', 'So AD² = (2b² + 2c² − a²)/4.'],
    },
    {
      q: 'Equilateral triangle of side a: inradius and circumradius?',
      a: ['r = a/(2√3), R = a/√3.', 'R = 2r, and the height is 3r.'],
      tag: 'Shortcut',
    },
    {
      q: 'Inradius of a right triangle with legs a, b and hypotenuse c?',
      a: ['r = (a + b − c)/2.', '3-4-5 triangle: r = 1.'],
      tag: 'Shortcut',
    },
    {
      q: 'Is AAA a congruence test?',
      a: ['No. Equal angles give the same shape, not the same size.', 'AAA (really AA) proves similarity only.'],
      tag: 'Trap',
    },
  ],
  quiz: [
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'The angles of a triangle are in the ratio 2 : 3 : 4. What is the largest angle?',
      options: ['60°', '80°', '90°', '100°'],
      answer: 1,
      explain: '9 parts = 180°, so one part = 20°. Largest = 4 × 20 = 80°.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'An exterior angle of a triangle is 110° and one of the interior opposite angles is 45°. What is the other interior opposite angle?',
      options: ['65°', '70°', '55°', '135°'],
      answer: 0,
      explain: 'Exterior angle = sum of the interior opposite angles: 110 − 45 = 65°.',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'What is the area of an equilateral triangle of side 8 cm?',
      options: ['8√3 cm²', '16√3 cm²', '32√3 cm²', '64 cm²'],
      answer: 1,
      explain: '√3/4 × 8² = √3/4 × 64 = 16√3 cm².',
    },
    {
      type: 'mcq',
      difficulty: 'easy',
      question: 'I is the incentre of △ABC and ∠A = 70°. What is ∠BIC?',
      options: ['110°', '140°', '125°', '145°'],
      answer: 2,
      explain: '∠BIC = 90° + A/2 = 90 + 35 = 125°.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'H is the orthocentre of an acute triangle ABC with ∠A = 65°. What is ∠BHC?',
      options: ['115°', '130°', '65°', '122.5°'],
      answer: 0,
      explain: '∠BHC = 180° − A = 115°.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'O is the circumcentre of an acute triangle ABC with ∠A = 50°. What is ∠BOC?',
      options: ['50°', '100°', '130°', '80°'],
      answer: 1,
      explain: 'The angle at the centre is twice the angle at the circumference: ∠BOC = 2 × 50 = 100°.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'In △ABC, AB = 6 cm, AC = 9 cm and BC = 10 cm. The bisector of ∠A meets BC at D. What is BD?',
      options: ['4 cm', '6 cm', '5 cm', '3.6 cm'],
      answer: 0,
      explain: 'BD : DC = 6 : 9 = 2 : 3. BD = 10 × 2/5 = 4 cm.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'In △ABC, AB = 7 cm, AC = 9 cm and BC = 8 cm. What is the length of the median AD?',
      options: ['6 cm', '√65 cm', '7 cm', '8 cm'],
      answer: 2,
      explain: 'AD² = (2 × 49 + 2 × 81 − 64)/4 = 196/4 = 49, so AD = 7 cm.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'The legs of a right triangle are 9 cm and 12 cm. What is the radius of its incircle?',
      options: ['4 cm', '6 cm', '7.5 cm', '3 cm'],
      answer: 3,
      explain: 'Hypotenuse = 15 (3-4-5 × 3). r = (9 + 12 − 15)/2 = 3 cm.',
      shortcut: 'Or r = (area)/s = 54/18 = 3.',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'What is the area of a triangle with sides 13 cm, 14 cm and 15 cm?',
      options: ['72 cm²', '84 cm²', '90 cm²', '96 cm²'],
      answer: 1,
      explain: 's = 21. Area = √(21 × 8 × 7 × 6) = √7056 = 84 cm².',
    },
    {
      type: 'mcq',
      difficulty: 'medium',
      question: 'The sides of a triangle are 7 cm, 8 cm and 12 cm. The triangle is:',
      options: ['Acute', 'Right', 'Obtuse', 'Equilateral'],
      answer: 2,
      explain: 'Longest side squared is 144. 7² + 8² = 113 < 144, so the angle opposite 12 is obtuse.',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: 'In △ABC, DE ∥ BC with D on AB and E on AC. If AD : DB = 2 : 3, what is area △ADE : area of trapezium DECB?',
      options: ['4 : 25', '2 : 3', '4 : 9', '4 : 21'],
      answer: 3,
      explain: 'AD : AB = 2 : 5, so the areas of △ADE and △ABC are 4 : 25. The trapezium is 25 − 4 = 21 parts.',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: 'G is the centroid of △ABC, whose area is 72 cm². D is the midpoint of BC. What is the area of △BGD?',
      options: ['24 cm²', '18 cm²', '9 cm²', '12 cm²'],
      answer: 3,
      explain: 'The three medians split the triangle into 6 equal parts. △BGD is one of them: 72 ÷ 6 = 12 cm².',
    },
    {
      type: 'mcq',
      difficulty: 'hard',
      question: 'The inradius of an equilateral triangle is 4 cm. What is its area?',
      options: ['48√3 cm²', '16√3 cm²', '64√3 cm²', '36√3 cm²'],
      answer: 0,
      explain: 'r = a/(2√3), so a = 8√3. Area = √3/4 × 192 = 48√3 cm².',
      shortcut: 'Area of an equilateral triangle = 3√3 × r² = 3√3 × 16 = 48√3.',
    },
    {
      type: 'truefalse',
      difficulty: 'easy',
      statement: 'In an equilateral triangle, the circumradius is twice the inradius.',
      answer: true,
      explain: 'R = a/√3 and r = a/(2√3), so R = 2r.',
    },
    {
      type: 'truefalse',
      difficulty: 'medium',
      statement: 'Two triangles with all three angles equal are always congruent.',
      answer: false,
      explain: 'Equal angles only make them similar. One can be a scaled-up copy of the other.',
    },
  ],
};

export default topic;
